import CKLaneM06.CapSubrow
import CKLaneM06.CapSec
import CKLaneM06.CapXHB.B000
import CKLaneM06.CapXHB.B001
import CKLaneM06.CapXHB.B002
import CKLaneM06.CapXHB.B003
import CKLaneM06.CapXHB.B004
import CKLaneM06.CapXHB.B005
import CKLaneM06.CapXHB.B006
import CKLaneM06.CapXHB.B007
import CKLaneM06.CapXHB.B008
import CKLaneM06.CapXHB.B009
import CKLaneM06.CapXHB.B010
import CKLaneM06.CapXHB.B011
import CKLaneM06.CapXHB.B012
import CKLaneM06.CapXHB.B013
import CKLaneM06.CapXHB.B014
import CKLaneM06.CapXHB.B015
import CKLaneM06.CapXHB.B016
import CKLaneM06.CapXHB.B017
import CKLaneM06.CapXHB.B018
import CKLaneM06.CapXHB.B019
import CKLaneM06.CapXHB.B020
import CKLaneM06.CapXHB.B021
import CKLaneM06.CapXHB.B022
import CKLaneM06.CapXHB.B023
import CKLaneM06.CapXHB.B024
import CKLaneM06.CapXHB.B025
import CKLaneM06.CapXH.C000
import CKLaneM06.CapXH.C001
import CKLaneM06.CapXH.C002
import CKLaneM06.CapXH.C003
import CKLaneM06.CapXH.C004
import CKLaneM06.CapXH.C005
import CKLaneM06.CapXH.C006
import CKLaneM06.CapXH.C007
import CKLaneM06.CapXH.C008
import CKLaneM06.CapXH.C009
import CKLaneM06.CapXH.C010
import CKLaneM06.CapXH.C011
import CKLaneM06.CapXH.C012
import CKLaneM06.CapXH.C013
import CKLaneM06.CapXH.C014
import CKLaneM06.CapXH.C015
import CKLaneM06.CapXH.C016
import CKLaneM06.CapXH.C017
import CKLaneM06.CapXH.C018
import CKLaneM06.CapXH.C019
import CKLaneM06.CapXH.C020
import CKLaneM06.CapXH.C021
import CKLaneM06.CapXH.C022
import CKLaneM06.CapXH.C023
import CKLaneM06.CapXH.C024
import CKLaneM06.CapXH.C025
import CKLaneM06.CapXH.C026
import CKLaneM06.CapXH.C027
import CKLaneM06.CapXH.C028
import CKLaneM06.CapXH.C029
import CKLaneM06.CapXH.C030
import CKLaneM06.CapXH.C031

/-!
# Lane M06: cap cover `cross` aggregation (root `xhRoot`, depth `3/40`)

14525 archived leaves (11516 non-vacuous checker leaves, 3593 secant) in
186 cut subtrees (`CKLaneM06.CapXH.Cnnn`, each one reflective kernel check of a `CTree2`);
merges above the cut by `CapOn.merge_path`.  Generated by M06/work/gen_cap_fleet2.py; re-bundled by M06/work/rebundle_xh.py.
-/

set_option autoImplicit false

namespace CKLaneM06.Cap.CapXHAgg

open GeneralCK CKLaneM06.Cap

theorem n_020212020202 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 0, 2]) (ax := 0) (by decide) CapXHB.B002.cap_1 CapXHB.B002.cap_2

theorem n_020212020212 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 1, 2]) (ax := 0) (by decide) CapXHB.B002.cap_4 CapXHB.B002.cap_5

theorem n_020212021202 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 1, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 1, 2, 0, 2]) (ax := 0) (by decide) CapXHB.B003.cap_3 CapXHB.B003.cap_4

theorem n_020212021212 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 1, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 1, 2, 1, 2]) (ax := 0) (by decide) CapXHB.B004.cap_0 CapXHB.B004.cap_1

theorem n_02021202021 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 1]) (ax := 1) (by decide) n_020212020212 CapXHB.B003.cap_0

theorem n_02021202121 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 1, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 1, 2, 1]) (ax := 1) (by decide) n_020212021212 CapXHB.B004.cap_2

theorem n_02021202120 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 1, 2, 0]) (ax := 1) (by decide) n_020212021202 CapXHB.B003.cap_5

theorem n_02021212021 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1]) (ax := 1) (by decide) CapXHB.B005.cap_3 CapXHB.B005.cap_4

theorem n_02021202020 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 0]) (ax := 1) (by decide) n_020212020202 CapXHB.B002.cap_3

theorem n_02020212131 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2, 1, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2, 1, 3, 1]) (ax := 1) (by decide) CapXH.C020.cap CapXH.C021.cap

theorem n_02021212020 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 1, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 1, 2, 0, 2, 0]) (ax := 1) (by decide) CapXHB.B005.cap_1 CapXHB.B005.cap_2

theorem n_02020212021 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2, 0, 2, 1]) (ax := 1) (by decide) CapXH.C011.cap CapXH.C012.cap

theorem n_02020212121 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2, 1, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2, 1, 2, 1]) (ax := 1) (by decide) CapXH.C017.cap CapXH.C018.cap

theorem n_02020212120 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2, 1, 2, 0]) (ax := 1) (by decide) CapXH.C015.cap CapXH.C016.cap

theorem n_0202020212 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 0, 2, 1, 2]) (ax := 0) (by decide) CapXH.C002.cap CapXH.C003.cap

theorem n_0202020213 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 0, 2, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 0, 2, 1, 3]) (ax := 0) (by decide) CapXH.C004.cap CapXH.C005.cap

theorem n_0202121202 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 1, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 1, 2, 0, 2]) (ax := 0) (by decide) n_02021212020 n_02021212021

theorem n_0202021213 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2, 1, 3]) (ax := 0) (by decide) CapXH.C019.cap n_02020212131

theorem n_0212020202 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2, 0, 2, 0, 2]) (ax := 0) (by decide) CapXHB.B010.cap_0 CapXHB.B010.cap_1

theorem n_0212020212 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2, 0, 2, 1, 2]) (ax := 0) (by decide) CapXHB.B010.cap_3 CapXHB.B010.cap_4

theorem n_0202120202 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 0, 2]) (ax := 0) (by decide) n_02021202020 n_02021202021

theorem n_0202021303 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 3, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 3, 0, 3]) (ax := 0) (by decide) CapXH.C024.cap CapXH.C025.cap

theorem n_0202021312 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 3, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 3, 1, 2]) (ax := 0) (by decide) CapXH.C026.cap CapXH.C027.cap

theorem n_0202021202 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2, 0, 2]) (ax := 0) (by decide) CapXH.C010.cap n_02020212021

theorem n_0202021313 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 3, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 3, 1, 3]) (ax := 0) (by decide) CapXH.C028.cap CapXH.C029.cap

theorem n_0202120213 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 1, 3]) (ax := 0) (by decide) CapXHB.B004.cap_3 CapXHB.B004.cap_4

theorem n_0202021302 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 3, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 3, 0, 2]) (ax := 0) (by decide) CapXH.C022.cap CapXH.C023.cap

theorem n_0202021212 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2, 1, 2]) (ax := 0) (by decide) n_02020212120 n_02020212121

theorem n_0202120212 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 1, 2]) (ax := 0) (by decide) n_02021202120 n_02021202121

theorem n_0202121212 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 1, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 1, 2, 1, 2]) (ax := 0) (by decide) CapXHB.B006.cap_1 CapXHB.B006.cap_2

theorem n_0202021203 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2, 0, 3]) (ax := 0) (by decide) CapXH.C013.cap CapXH.C014.cap

theorem n_0202120203 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 0, 3]) (ax := 0) (by decide) CapXHB.B003.cap_1 CapXHB.B003.cap_2

theorem n_020202130 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 3, 0]) (ax := 1) (by decide) n_0202021302 n_0202021303

theorem n_020202030 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 0, 3, 0]) (ax := 1) (by decide) CapXH.C006.cap CapXH.C007.cap

theorem n_020202120 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2, 0]) (ax := 1) (by decide) n_0202021202 n_0202021203

theorem n_020202121 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2, 1]) (ax := 1) (by decide) n_0202021212 n_0202021213

theorem n_020212121 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 1, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 1, 2, 1]) (ax := 1) (by decide) n_0202121212 CapXHB.B006.cap_3

theorem n_020212020 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 0]) (ax := 1) (by decide) n_0202120202 n_0202120203

theorem n_021202121 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2, 1, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2, 1, 2, 1]) (ax := 1) (by decide) CapXHB.B011.cap_2 CapXHB.B011.cap_3

theorem n_020212030 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 3, 0]) (ax := 1) (by decide) CapXHB.B004.cap_5 CapXHB.B004.cap_6

theorem n_020203021 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 0, 2, 1]) (ax := 1) (by decide) CapXH.C031.cap CapXHB.B000.cap_0

theorem n_020212120 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 1, 2, 0]) (ax := 1) (by decide) n_0202121202 CapXHB.B006.cap_0

theorem n_020212021 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2, 1]) (ax := 1) (by decide) n_0202120212 n_0202120213

theorem n_020202021 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 0, 2, 1]) (ax := 1) (by decide) n_0202020212 n_0202020213

theorem n_020203130 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 1, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 1, 3, 0]) (ax := 1) (by decide) CapXHB.B001.cap_2 CapXHB.B001.cap_3

theorem n_021202120 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2, 1, 2, 0]) (ax := 1) (by decide) CapXHB.B011.cap_0 CapXHB.B011.cap_1

theorem n_021202021 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2, 0, 2, 1]) (ax := 1) (by decide) n_0212020212 CapXHB.B010.cap_5

theorem n_020202020 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 0, 2, 0]) (ax := 1) (by decide) CapXH.C000.cap CapXH.C001.cap

theorem n_020203031 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 0, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 0, 3, 1]) (ax := 1) (by decide) CapXHB.B000.cap_2 CapXHB.B000.cap_3

theorem n_020203120 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 1, 2, 0]) (ax := 1) (by decide) CapXHB.B000.cap_4 CapXHB.B000.cap_5

theorem n_020202131 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 3, 1]) (ax := 1) (by decide) n_0202021312 n_0202021313

theorem n_020203131 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 1, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 1, 3, 1]) (ax := 1) (by decide) CapXHB.B001.cap_4 CapXHB.B002.cap_0

theorem n_021202020 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2, 0, 2, 0]) (ax := 1) (by decide) n_0212020202 CapXHB.B010.cap_2

theorem n_020203121 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 1, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 1, 2, 1]) (ax := 1) (by decide) CapXHB.B001.cap_0 CapXHB.B001.cap_1

theorem n_020202031 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 0, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 0, 3, 1]) (ax := 1) (by decide) CapXH.C008.cap CapXH.C009.cap

theorem n_030202131 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 2, 1, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 2, 1, 3, 1]) (ax := 1) (by decide) CapXHB.B014.cap_3 CapXHB.B014.cap_4

theorem n_030203031 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 0, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 0, 3, 1]) (ax := 1) (by decide) CapXHB.B015.cap_3 CapXHB.B015.cap_4

theorem n_030203120 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 1, 2, 0]) (ax := 1) (by decide) CapXHB.B016.cap_0 CapXHB.B016.cap_1

theorem n_030203121 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 1, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 1, 2, 1]) (ax := 1) (by decide) CapXHB.B016.cap_2 CapXHB.B016.cap_3

theorem n_030203130 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 1, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 1, 3, 0]) (ax := 1) (by decide) CapXHB.B016.cap_4 CapXHB.B016.cap_5

theorem n_030203131 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 1, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 1, 3, 1]) (ax := 1) (by decide) CapXHB.B017.cap_0 CapXHB.B017.cap_1

theorem n_030212030 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1, 2, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1, 2, 0, 3, 0]) (ax := 1) (by decide) CapXHB.B017.cap_3 CapXHB.B017.cap_4

theorem n_030302020 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 0, 2, 0]) (ax := 1) (by decide) CapXHB.B019.cap_3 CapXHB.B019.cap_4

theorem n_030302021 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 0, 2, 1]) (ax := 1) (by decide) CapXHB.B019.cap_5 CapXHB.B020.cap_0

theorem n_030302030 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 0, 3, 0]) (ax := 1) (by decide) CapXHB.B020.cap_1 CapXHB.B020.cap_2

theorem n_030302031 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 0, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 0, 3, 1]) (ax := 1) (by decide) CapXHB.B020.cap_3 CapXHB.B020.cap_4

theorem n_030302120 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 1, 2, 0]) (ax := 1) (by decide) CapXHB.B020.cap_5 CapXHB.B021.cap_0

theorem n_030302130 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 1, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 1, 3, 0]) (ax := 1) (by decide) CapXHB.B021.cap_2 CapXHB.B021.cap_3

theorem n_030303020 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 3, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 3, 0, 2, 0]) (ax := 1) (by decide) CapXHB.B021.cap_5 CapXHB.B022.cap_0

theorem n_030303021 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 3, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 3, 0, 2, 1]) (ax := 1) (by decide) CapXHB.B022.cap_1 CapXHB.B022.cap_2

theorem n_030303030 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 3, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 3, 0, 3, 0]) (ax := 1) (by decide) CapXHB.B022.cap_3 CapXHB.B022.cap_4

theorem n_02121202 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 1, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 1, 2, 0, 2]) (ax := 0) (by decide) CapXHB.B012.cap_0 CapXHB.B012.cap_1

theorem n_02021213 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 1, 3]) (ax := 0) (by decide) CapXHB.B006.cap_4 CapXHB.B007.cap_0

theorem n_02020212 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 2]) (ax := 0) (by decide) n_020202120 n_020202121

theorem n_02020213 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1, 3]) (ax := 0) (by decide) n_020202130 n_020202131

theorem n_02021203 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 3]) (ax := 0) (by decide) n_020212030 CapXHB.B005.cap_0

theorem n_02021212 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 1, 2]) (ax := 0) (by decide) n_020212120 n_020212121

theorem n_02021303 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 3, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 3, 0, 3]) (ax := 0) (by decide) CapXHB.B007.cap_3 CapXHB.B007.cap_4

theorem n_02020202 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 0, 2]) (ax := 0) (by decide) n_020202020 n_020202021

theorem n_02020302 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 0, 2]) (ax := 0) (by decide) CapXH.C030.cap n_020203021

theorem n_02020312 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 1, 2]) (ax := 0) (by decide) n_020203120 n_020203121

theorem n_02020203 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 0, 3]) (ax := 0) (by decide) n_020202030 n_020202031

theorem n_02020303 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 0, 3]) (ax := 0) (by decide) CapXHB.B000.cap_1 n_020203031

theorem n_02120202 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2, 0, 2]) (ax := 0) (by decide) n_021202020 n_021202021

theorem n_02121212 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 1, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 1, 2, 1, 2]) (ax := 0) (by decide) CapXHB.B012.cap_3 CapXHB.B012.cap_4

theorem n_12020202 : CapOn (cpathBox xhRoot [1, 2, 0, 2, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [1, 2, 0, 2, 0, 2, 0, 2]) (ax := 0) (by decide) CapXHB.B024.cap_1 CapXHB.B024.cap_2

theorem n_02020313 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 1, 3]) (ax := 0) (by decide) n_020203130 n_020203131

theorem n_02021302 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 3, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 3, 0, 2]) (ax := 0) (by decide) CapXHB.B007.cap_1 CapXHB.B007.cap_2

theorem n_02120212 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2, 1, 2]) (ax := 0) (by decide) n_021202120 n_021202121

theorem n_02021202 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0, 2]) (ax := 0) (by decide) n_020212020 n_020212021

theorem n_02030302 : CapOn (cpathBox xhRoot [0, 2, 0, 3, 0, 3, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3, 0, 3, 0, 2]) (ax := 0) (by decide) CapXHB.B008.cap_3 CapXHB.B008.cap_4

theorem n_02030303 : CapOn (cpathBox xhRoot [0, 2, 0, 3, 0, 3, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3, 0, 3, 0, 3]) (ax := 0) (by decide) CapXHB.B008.cap_5 CapXHB.B009.cap_0

theorem n_02030313 : CapOn (cpathBox xhRoot [0, 2, 0, 3, 0, 3, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3, 0, 3, 1, 3]) (ax := 0) (by decide) CapXHB.B009.cap_2 CapXHB.B009.cap_3

theorem n_03020202 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 2, 0, 2]) (ax := 0) (by decide) CapXHB.B013.cap_2 CapXHB.B013.cap_3

theorem n_03020203 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 2, 0, 3]) (ax := 0) (by decide) CapXHB.B013.cap_4 CapXHB.B013.cap_5

theorem n_03020212 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 2, 1, 2]) (ax := 0) (by decide) CapXHB.B014.cap_0 CapXHB.B014.cap_1

theorem n_03020213 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 2, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 2, 1, 3]) (ax := 0) (by decide) CapXHB.B014.cap_2 n_030202131

theorem n_03020302 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 0, 2]) (ax := 0) (by decide) CapXHB.B015.cap_0 CapXHB.B015.cap_1

theorem n_03020303 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 0, 3]) (ax := 0) (by decide) CapXHB.B015.cap_2 n_030203031

theorem n_03020312 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 1, 2]) (ax := 0) (by decide) n_030203120 n_030203121

theorem n_03020313 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 1, 3]) (ax := 0) (by decide) n_030203130 n_030203131

theorem n_03021203 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1, 2, 0, 3]) (ax := 0) (by decide) n_030212030 CapXHB.B017.cap_5

theorem n_03021302 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1, 3, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1, 3, 0, 2]) (ax := 0) (by decide) CapXHB.B018.cap_1 CapXHB.B018.cap_2

theorem n_03021303 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1, 3, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1, 3, 0, 3]) (ax := 0) (by decide) CapXHB.B018.cap_3 CapXHB.B018.cap_4

theorem n_03021313 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1, 3, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1, 3, 1, 3]) (ax := 0) (by decide) CapXHB.B019.cap_1 CapXHB.B019.cap_2

theorem n_03030202 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 0, 2]) (ax := 0) (by decide) n_030302020 n_030302021

theorem n_03030203 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 0, 3]) (ax := 0) (by decide) n_030302030 n_030302031

theorem n_03030212 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 1, 2]) (ax := 0) (by decide) n_030302120 CapXHB.B021.cap_1

theorem n_03030213 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 1, 3]) (ax := 0) (by decide) n_030302130 CapXHB.B021.cap_4

theorem n_03030302 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 3, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 3, 0, 2]) (ax := 0) (by decide) n_030303020 n_030303021

theorem n_03030303 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 3, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 3, 0, 3]) (ax := 0) (by decide) n_030303030 CapXHB.B022.cap_5

theorem n_03031202 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 1, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 1, 2, 0, 2]) (ax := 0) (by decide) CapXHB.B023.cap_1 CapXHB.B023.cap_2

theorem n_0202021 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 1]) (ax := 1) (by decide) n_02020212 n_02020213

theorem n_0202031 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 1]) (ax := 1) (by decide) n_02020312 n_02020313

theorem n_0202120 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 0]) (ax := 1) (by decide) n_02021202 n_02021203

theorem n_1202020 : CapOn (cpathBox xhRoot [1, 2, 0, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [1, 2, 0, 2, 0, 2, 0]) (ax := 1) (by decide) n_12020202 CapXHB.B024.cap_3

theorem n_0202020 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2, 0]) (ax := 1) (by decide) n_02020202 n_02020203

theorem n_0212021 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2, 1]) (ax := 1) (by decide) n_02120212 CapXHB.B011.cap_4

theorem n_0212120 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 1, 2, 0]) (ax := 1) (by decide) n_02121202 CapXHB.B012.cap_2

theorem n_0202121 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2, 1]) (ax := 1) (by decide) n_02021212 n_02021213

theorem n_0202130 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 3, 0]) (ax := 1) (by decide) n_02021302 n_02021303

theorem n_0212121 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 1, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 1, 2, 1]) (ax := 1) (by decide) n_02121212 CapXHB.B012.cap_5

theorem n_0202030 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3, 0]) (ax := 1) (by decide) n_02020302 n_02020303

theorem n_0212020 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2, 0]) (ax := 1) (by decide) n_02120202 CapXHB.B010.cap_6

theorem n_0202131 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 3, 1]) (ax := 1) (by decide) CapXHB.B007.cap_5 CapXHB.B008.cap_0

theorem n_0203030 : CapOn (cpathBox xhRoot [0, 2, 0, 3, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3, 0, 3, 0]) (ax := 1) (by decide) n_02030302 n_02030303

theorem n_0203031 : CapOn (cpathBox xhRoot [0, 2, 0, 3, 0, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3, 0, 3, 1]) (ax := 1) (by decide) CapXHB.B009.cap_1 n_02030313

theorem n_0302020 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 2, 0]) (ax := 1) (by decide) n_03020202 n_03020203

theorem n_0302021 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 2, 1]) (ax := 1) (by decide) n_03020212 n_03020213

theorem n_0302030 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 0]) (ax := 1) (by decide) n_03020302 n_03020303

theorem n_0302031 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3, 1]) (ax := 1) (by decide) n_03020312 n_03020313

theorem n_0302120 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1, 2, 0]) (ax := 1) (by decide) CapXHB.B017.cap_2 n_03021203

theorem n_0302130 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1, 3, 0]) (ax := 1) (by decide) n_03021302 n_03021303

theorem n_0302131 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1, 3, 1]) (ax := 1) (by decide) CapXHB.B019.cap_0 n_03021313

theorem n_0303020 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 0]) (ax := 1) (by decide) n_03030202 n_03030203

theorem n_0303021 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2, 1]) (ax := 1) (by decide) n_03030212 n_03030213

theorem n_0303030 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 3, 0]) (ax := 1) (by decide) n_03030302 n_03030303

theorem n_0303120 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 1, 2, 0]) (ax := 1) (by decide) n_03031202 CapXHB.B023.cap_3

theorem n_020203 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 3]) (ax := 0) (by decide) n_0202030 n_0202031

theorem n_021212 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 1, 2]) (ax := 0) (by decide) n_0212120 n_0212121

theorem n_021202 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 2]) (ax := 0) (by decide) n_0212020 n_0212021

theorem n_120212 : CapOn (cpathBox xhRoot [1, 2, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [1, 2, 0, 2, 1, 2]) (ax := 0) (by decide) CapXHB.B024.cap_6 CapXHB.B025.cap_0

theorem n_120202 : CapOn (cpathBox xhRoot [1, 2, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [1, 2, 0, 2, 0, 2]) (ax := 0) (by decide) n_1202020 CapXHB.B024.cap_4

theorem n_020212 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 2]) (ax := 0) (by decide) n_0202120 n_0202121

theorem n_020213 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1, 3]) (ax := 0) (by decide) n_0202130 n_0202131

theorem n_021203 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0, 3]) (ax := 0) (by decide) CapXHB.B011.cap_5 CapXHB.B011.cap_6

theorem n_020202 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0, 2]) (ax := 0) (by decide) n_0202020 n_0202021

theorem n_020302 : CapOn (cpathBox xhRoot [0, 2, 0, 3, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3, 0, 2]) (ax := 0) (by decide) CapXHB.B008.cap_1 CapXHB.B008.cap_2

theorem n_020303 : CapOn (cpathBox xhRoot [0, 2, 0, 3, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3, 0, 3]) (ax := 0) (by decide) n_0203030 n_0203031

theorem n_020313 : CapOn (cpathBox xhRoot [0, 2, 0, 3, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3, 1, 3]) (ax := 0) (by decide) CapXHB.B009.cap_5 CapXHB.B009.cap_6

theorem n_030202 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 2]) (ax := 0) (by decide) n_0302020 n_0302021

theorem n_030203 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0, 3]) (ax := 0) (by decide) n_0302030 n_0302031

theorem n_030212 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1, 2]) (ax := 0) (by decide) n_0302120 CapXHB.B018.cap_0

theorem n_030213 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1, 3]) (ax := 0) (by decide) n_0302130 n_0302131

theorem n_030302 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 2]) (ax := 0) (by decide) n_0303020 n_0303021

theorem n_030303 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0, 3]) (ax := 0) (by decide) n_0303030 CapXHB.B023.cap_0

theorem n_030312 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 1, 2]) (ax := 0) (by decide) n_0303120 CapXHB.B023.cap_4

theorem n_02120 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 0]) (ax := 1) (by decide) n_021202 n_021203

theorem n_02020 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 0]) (ax := 1) (by decide) n_020202 n_020203

theorem n_12021 : CapOn (cpathBox xhRoot [1, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [1, 2, 0, 2, 1]) (ax := 1) (by decide) n_120212 CapXHB.B025.cap_1

theorem n_12020 : CapOn (cpathBox xhRoot [1, 2, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [1, 2, 0, 2, 0]) (ax := 1) (by decide) n_120202 CapXHB.B024.cap_5

theorem n_02121 : CapOn (cpathBox xhRoot [0, 2, 1, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2, 1]) (ax := 1) (by decide) n_021212 CapXHB.B013.cap_0

theorem n_02021 : CapOn (cpathBox xhRoot [0, 2, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2, 1]) (ax := 1) (by decide) n_020212 n_020213

theorem n_02030 : CapOn (cpathBox xhRoot [0, 2, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3, 0]) (ax := 1) (by decide) n_020302 n_020303

theorem n_02031 : CapOn (cpathBox xhRoot [0, 2, 0, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3, 1]) (ax := 1) (by decide) CapXHB.B009.cap_4 n_020313

theorem n_03020 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 0]) (ax := 1) (by decide) n_030202 n_030203

theorem n_03021 : CapOn (cpathBox xhRoot [0, 3, 0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2, 1]) (ax := 1) (by decide) n_030212 n_030213

theorem n_03030 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 0]) (ax := 1) (by decide) n_030302 n_030303

theorem n_03031 : CapOn (cpathBox xhRoot [0, 3, 0, 3, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3, 1]) (ax := 1) (by decide) n_030312 CapXHB.B023.cap_5

theorem n_1202 : CapOn (cpathBox xhRoot [1, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [1, 2, 0, 2]) (ax := 0) (by decide) n_12020 n_12021

theorem n_0202 : CapOn (cpathBox xhRoot [0, 2, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 2]) (ax := 0) (by decide) n_02020 n_02021

theorem n_0212 : CapOn (cpathBox xhRoot [0, 2, 1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1, 2]) (ax := 0) (by decide) n_02120 n_02121

theorem n_0203 : CapOn (cpathBox xhRoot [0, 2, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0, 3]) (ax := 0) (by decide) n_02030 n_02031

theorem n_0302 : CapOn (cpathBox xhRoot [0, 3, 0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 2]) (ax := 0) (by decide) n_03020 n_03021

theorem n_0303 : CapOn (cpathBox xhRoot [0, 3, 0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0, 3]) (ax := 0) (by decide) n_03030 n_03031

theorem n_020 : CapOn (cpathBox xhRoot [0, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 0]) (ax := 1) (by decide) n_0202 n_0203

theorem n_120 : CapOn (cpathBox xhRoot [1, 2, 0]) (3 / 40) :=
  CapOn.merge_path (p := [1, 2, 0]) (ax := 1) (by decide) n_1202 CapXHB.B025.cap_2

theorem n_021 : CapOn (cpathBox xhRoot [0, 2, 1]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2, 1]) (ax := 1) (by decide) n_0212 CapXHB.B013.cap_1

theorem n_030 : CapOn (cpathBox xhRoot [0, 3, 0]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3, 0]) (ax := 1) (by decide) n_0302 n_0303

theorem n_12 : CapOn (cpathBox xhRoot [1, 2]) (3 / 40) :=
  CapOn.merge_path (p := [1, 2]) (ax := 0) (by decide) n_120 CapXHB.B025.cap_3

theorem n_02 : CapOn (cpathBox xhRoot [0, 2]) (3 / 40) :=
  CapOn.merge_path (p := [0, 2]) (ax := 0) (by decide) n_020 n_021

theorem n_03 : CapOn (cpathBox xhRoot [0, 3]) (3 / 40) :=
  CapOn.merge_path (p := [0, 3]) (ax := 0) (by decide) n_030 CapXHB.B024.cap_0

theorem n_1 : CapOn (cpathBox xhRoot [1]) (3 / 40) :=
  CapOn.merge_path (p := [1]) (ax := 1) (by decide) n_12 CapXHB.B025.cap_4

theorem n_0 : CapOn (cpathBox xhRoot [0]) (3 / 40) :=
  CapOn.merge_path (p := [0]) (ax := 1) (by decide) n_02 n_03

theorem n_root : CapOn (cpathBox xhRoot []) (3 / 40) :=
  CapOn.merge_path (p := []) (ax := 0) (by decide) n_0 n_1

/-- `CapOn` on the whole archived root. -/
theorem capOn_root : CapOn xhRoot (3 / 40) := n_root

/-- **Cross-half cap rectangle** (`EXPANDED_CAP` root `[1/10,1/2]×[1/2,9/10]`, `s ≤ 3/40`). -/
theorem capCross : CapCross := by
  intro k μ hab hsum ha ha2 hb hs
  rcases lt_or_eq_of_le hab with hlt | heq
  · have h := capOn_root k μ hlt hsum
    simp only [xhRoot] at h
    push_cast at h
    exact h ha ha2 hb (by linarith) hs
  · exact psi_gap_le_cost_of_eq μ heq

end CKLaneM06.Cap.CapXHAgg
