import CKLaneA3X.StepH_HcG_13
import CKLaneA3X.StepH_HcG_12
import CKLaneA3X.StepH_HcG_11
import CKLaneA3X.StepH_HcG_10
import CKLaneA3X.StepH_HcG_9
import CKLaneA3X.StepH_HcG_8
import CKLaneA3X.StepH_HcG_7
import CKLaneA3X.StepH_HcG_6
import CKLaneA3X.StepH_HcG_5
import CKLaneA3X.StepH_HcG_4
import CKLaneA3X.StepH_HcG_3
import CKLaneA3X.StepH_HcG_2
import CKLaneA3X.StepH_HcG_1
import CKLaneA3X.StepH_HcG
import CKLaneA3X.StepH_HlcG_13
import CKLaneA3X.StepH_HlcG_12
import CKLaneA3X.StepH_HlcG_11
import CKLaneA3X.StepH_HlcG_10
import CKLaneA3X.StepH_HlcG_9
import CKLaneA3X.StepH_HlcG_8
import CKLaneA3X.StepH_HlcG_7
import CKLaneA3X.StepH_HlcG_6
import CKLaneA3X.StepH_HlcG_5
import CKLaneA3X.StepH_HlcG_4
import CKLaneA3X.StepH_HlcG_3
import CKLaneA3X.StepH_HlcG_2
import CKLaneA3X.StepH_HlcG_1
import CKLaneA3X.StepH_HlcG
import CKLaneA3X.StepH_Hc_13
import CKLaneA3X.StepH_Hc_12
import CKLaneA3X.StepH_Hc_11
import CKLaneA3X.StepH_Hc_10
import CKLaneA3X.StepH_Hc_9
import CKLaneA3X.StepH_Hc_8
import CKLaneA3X.StepH_Hc_7
import CKLaneA3X.StepH_Hc_6
import CKLaneA3X.StepH_Hc_5
import CKLaneA3X.StepH_Hc_4
import CKLaneA3X.StepH_Hc_3
import CKLaneA3X.StepH_Hc_2
import CKLaneA3X.StepH_Hc_1
import CKLaneA3X.StepH_Hc
import CKLaneA3X.StepH_Hlc_13
import CKLaneA3X.StepH_Hlc_12
import CKLaneA3X.StepH_Hlc_11
import CKLaneA3X.StepH_Hlc_10
import CKLaneA3X.StepH_Hlc_9
import CKLaneA3X.StepH_Hlc_8
import CKLaneA3X.StepH_Hlc_7
import CKLaneA3X.StepH_Hlc_6
import CKLaneA3X.StepH_Hlc_5
import CKLaneA3X.StepH_Hlc_4
import CKLaneA3X.StepH_Hlc_3
import CKLaneA3X.StepH_Hlc_2
import CKLaneA3X.StepH_Hlc_1
import CKLaneA3X.StepH_Hlc
import CKLaneA3X.Step000
import CKLaneA3X.Step001
import CKLaneA3X.Step002
import CKLaneA3X.Step004
import CKLaneA3X.Step006
import CKLaneA3X.Step007
import CKLaneA3X.Step009
import CKLaneA3X.Step011
import CKLaneA3X.Step012
import CKLaneA3X.Step013
import CKLaneA3X.Step014
import CKLaneA3X.Step015
import CKLaneA3X.Step016
import CKLaneA3X.Step017
import CKLaneA3X.Step018
import CKLaneA3X.Step019
import CKLaneA3X.Step020
import CKLaneA3X.Step021
import CKLaneA3X.Step022
import CKLaneA3X.Step023
import CKLaneA3X.Step024
import CKLaneA3X.Step025
import CKLaneA3X.Step026
import CKLaneA3X.Step027
import CKLaneA3X.Step028
import CKLaneA3X.Step029

/-! Generated by num/gen_par.py (Lane A3): chain composition. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false

namespace CKLaneA3X

theorem G_t : Good F_t D_t := S_t
theorem G_x : Good F_x D_x := S_x
theorem G_y : Good F_y D_y := S_y
theorem G_d : Good F_d D_d := S_d
theorem G_q : Good F_q D_q := S_q
theorem G_h : Good F_h D_h := S_h
theorem G_L : Good F_L D_L := S_L
theorem G_one : Good F_one D_one := S_one
theorem G_mone : Good F_mone D_mone := S_mone
theorem G_xx : Good F_xx D_xx := S_xx G_x
theorem G_Hx : Good F_Hx D_Hx := S_Hx G_xx
theorem G_Yx : Good F_Yx D_Yx := S_Yx G_x G_Hx
theorem G_Ax : Good F_Ax D_Ax := S_Ax G_x G_Yx
theorem G_Hlx : Good F_Hlx D_Hlx := S_Hlx G_xx
theorem G_Ylx : Good F_Ylx D_Ylx := S_Ylx G_xx G_Hlx
theorem G_lx : Good F_lx D_lx := S_lx G_xx G_Ylx
theorem G_hlx : Good F_hlx D_hlx := S_hlx G_lx
theorem G_Bx : Good F_Bx D_Bx := S_Bx G_L G_hlx
theorem G_vAx : Good F_vAx D_vAx := S_vAx G_x G_Ax
theorem G_mvAx : Good F_mvAx D_mvAx := S_mvAx G_vAx
theorem G_Ex0 : Good F_Ex0 D_Ex0 := S_Ex0 G_Bx G_mvAx
theorem G_yy : Good F_yy D_yy := S_yy G_y
theorem G_Hy : Good F_Hy D_Hy := S_Hy G_yy
theorem G_Yy : Good F_Yy D_Yy := S_Yy G_y G_Hy
theorem G_Ay : Good F_Ay D_Ay := S_Ay G_y G_Yy
theorem G_Hly : Good F_Hly D_Hly := S_Hly G_yy
theorem G_Yly : Good F_Yly D_Yly := S_Yly G_yy G_Hly
theorem G_ly : Good F_ly D_ly := S_ly G_yy G_Yly
theorem G_hly : Good F_hly D_hly := S_hly G_ly
theorem G_By : Good F_By D_By := S_By G_L G_hly
theorem G_vAy : Good F_vAy D_vAy := S_vAy G_y G_Ay
theorem G_mvAy : Good F_mvAy D_mvAy := S_mvAy G_vAy
theorem G_Ey0 : Good F_Ey0 D_Ey0 := S_Ey0 G_By G_mvAy
theorem G_J0 : Good F_J0 D_J0 := S_J0 G_Ax
theorem G_J : Good F_J D_J := S_J G_J0
theorem G_Jw0 : Good F_Jw0 D_Jw0 := S_Jw0 G_Ay
theorem G_Jw : Good F_Jw D_Jw := S_Jw G_Jw0
theorem G_Ex : Good F_Ex D_Ex := S_Ex G_Ex0
theorem G_Ey : Good F_Ey D_Ey := S_Ey G_Ey0
theorem G_S0 : Good F_S0 D_S0 := S_S0 G_Ex G_Ey
theorem G_S : Good F_S D_S := S_S G_S0
theorem G_Si : Good F_Si D_Si := S_Si G_S
theorem G_dd : Good F_dd D_dd := S_dd
theorem G_j0 : Good F_j0 D_j0 := S_j0 G_dd
theorem G_j : Good F_j D_j := S_j G_j0
theorem G_Gex : Good F_Gex D_Gex := S_Gex
theorem G_cG : Good F_cG D_cG := S_cG G_d G_Gex
theorem G_cGcG : Good F_cGcG D_cGcG := S_cGcG G_cG
theorem G_HcG_13 : Good F_HcG_13 D_HcG_13 := S_HcG_13 G_cGcG
theorem G_HcG_12 : Good F_HcG_12 D_HcG_12 := S_HcG_12 G_cGcG G_HcG_13
theorem G_HcG_11 : Good F_HcG_11 D_HcG_11 := S_HcG_11 G_cGcG G_HcG_12
theorem G_HcG_10 : Good F_HcG_10 D_HcG_10 := S_HcG_10 G_cGcG G_HcG_11
theorem G_HcG_9 : Good F_HcG_9 D_HcG_9 := S_HcG_9 G_cGcG G_HcG_10
theorem G_HcG_8 : Good F_HcG_8 D_HcG_8 := S_HcG_8 G_cGcG G_HcG_9
theorem G_HcG_7 : Good F_HcG_7 D_HcG_7 := S_HcG_7 G_cGcG G_HcG_8
theorem G_HcG_6 : Good F_HcG_6 D_HcG_6 := S_HcG_6 G_cGcG G_HcG_7
theorem G_HcG_5 : Good F_HcG_5 D_HcG_5 := S_HcG_5 G_cGcG G_HcG_6
theorem G_HcG_4 : Good F_HcG_4 D_HcG_4 := S_HcG_4 G_cGcG G_HcG_5
theorem G_HcG_3 : Good F_HcG_3 D_HcG_3 := S_HcG_3 G_cGcG G_HcG_4
theorem G_HcG_2 : Good F_HcG_2 D_HcG_2 := S_HcG_2 G_cGcG G_HcG_3
theorem G_HcG_1 : Good F_HcG_1 D_HcG_1 := S_HcG_1 G_cGcG G_HcG_2
theorem G_HcG : Good F_HcG D_HcG := S_HcG G_cGcG G_HcG_1
theorem G_YcG : Good F_YcG D_YcG := S_YcG G_cG G_HcG
theorem G_AcG : Good F_AcG D_AcG := S_AcG G_cG G_YcG
theorem G_HlcG_13 : Good F_HlcG_13 D_HlcG_13 := S_HlcG_13 G_cGcG
theorem G_HlcG_12 : Good F_HlcG_12 D_HlcG_12 := S_HlcG_12 G_cGcG G_HlcG_13
theorem G_HlcG_11 : Good F_HlcG_11 D_HlcG_11 := S_HlcG_11 G_cGcG G_HlcG_12
theorem G_HlcG_10 : Good F_HlcG_10 D_HlcG_10 := S_HlcG_10 G_cGcG G_HlcG_11
theorem G_HlcG_9 : Good F_HlcG_9 D_HlcG_9 := S_HlcG_9 G_cGcG G_HlcG_10
theorem G_HlcG_8 : Good F_HlcG_8 D_HlcG_8 := S_HlcG_8 G_cGcG G_HlcG_9
theorem G_HlcG_7 : Good F_HlcG_7 D_HlcG_7 := S_HlcG_7 G_cGcG G_HlcG_8
theorem G_HlcG_6 : Good F_HlcG_6 D_HlcG_6 := S_HlcG_6 G_cGcG G_HlcG_7
theorem G_HlcG_5 : Good F_HlcG_5 D_HlcG_5 := S_HlcG_5 G_cGcG G_HlcG_6
theorem G_HlcG_4 : Good F_HlcG_4 D_HlcG_4 := S_HlcG_4 G_cGcG G_HlcG_5
theorem G_HlcG_3 : Good F_HlcG_3 D_HlcG_3 := S_HlcG_3 G_cGcG G_HlcG_4
theorem G_HlcG_2 : Good F_HlcG_2 D_HlcG_2 := S_HlcG_2 G_cGcG G_HlcG_3
theorem G_HlcG_1 : Good F_HlcG_1 D_HlcG_1 := S_HlcG_1 G_cGcG G_HlcG_2
theorem G_HlcG : Good F_HlcG D_HlcG := S_HlcG G_cGcG G_HlcG_1
theorem G_YlcG : Good F_YlcG D_YlcG := S_YlcG G_cGcG G_HlcG
theorem G_lcG : Good F_lcG D_lcG := S_lcG G_cGcG G_YlcG
theorem G_hlcG : Good F_hlcG D_hlcG := S_hlcG G_lcG
theorem G_BcG : Good F_BcG D_BcG := S_BcG G_L G_hlcG
theorem G_cGAcG : Good F_cGAcG D_cGAcG := S_cGAcG G_cG G_AcG
theorem G_mcGAcG : Good F_mcGAcG D_mcGAcG := S_mcGAcG G_cGAcG
theorem G_EcG0 : Good F_EcG0 D_EcG0 := S_EcG0 G_BcG G_mcGAcG
theorem G_EcG : Good F_EcG D_EcG := S_EcG G_EcG0 G_cG
theorem G_GS : Good F_GS D_GS := S_GS G_Gex G_S
theorem G_m2EcG : Good F_m2EcG D_m2EcG := S_m2EcG G_EcG
theorem G_Phi : Good F_Phi D_Phi := S_Phi G_GS G_m2EcG
theorem G_gam : Good F_gam D_gam := S_gam G_S G_Phi
theorem G_c0 : Good F_c0 D_c0 := S_c0 G_d G_gam
theorem G_c : Good F_c D_c := S_c G_c0
theorem G_cc : Good F_cc D_cc := S_cc G_c
theorem G_Hc_13 : Good F_Hc_13 D_Hc_13 := S_Hc_13 G_cc
theorem G_Hc_12 : Good F_Hc_12 D_Hc_12 := S_Hc_12 G_cc G_Hc_13
theorem G_Hc_11 : Good F_Hc_11 D_Hc_11 := S_Hc_11 G_cc G_Hc_12
theorem G_Hc_10 : Good F_Hc_10 D_Hc_10 := S_Hc_10 G_cc G_Hc_11
theorem G_Hc_9 : Good F_Hc_9 D_Hc_9 := S_Hc_9 G_cc G_Hc_10
theorem G_Hc_8 : Good F_Hc_8 D_Hc_8 := S_Hc_8 G_cc G_Hc_9
theorem G_Hc_7 : Good F_Hc_7 D_Hc_7 := S_Hc_7 G_cc G_Hc_8
theorem G_Hc_6 : Good F_Hc_6 D_Hc_6 := S_Hc_6 G_cc G_Hc_7
theorem G_Hc_5 : Good F_Hc_5 D_Hc_5 := S_Hc_5 G_cc G_Hc_6
theorem G_Hc_4 : Good F_Hc_4 D_Hc_4 := S_Hc_4 G_cc G_Hc_5
theorem G_Hc_3 : Good F_Hc_3 D_Hc_3 := S_Hc_3 G_cc G_Hc_4
theorem G_Hc_2 : Good F_Hc_2 D_Hc_2 := S_Hc_2 G_cc G_Hc_3
theorem G_Hc_1 : Good F_Hc_1 D_Hc_1 := S_Hc_1 G_cc G_Hc_2
theorem G_Hc : Good F_Hc D_Hc := S_Hc G_cc G_Hc_1
theorem G_Acc : Good F_Acc D_Acc := S_Acc G_c G_Hc
theorem G_Hlc_13 : Good F_Hlc_13 D_Hlc_13 := S_Hlc_13 G_cc
theorem G_Hlc_12 : Good F_Hlc_12 D_Hlc_12 := S_Hlc_12 G_cc G_Hlc_13
theorem G_Hlc_11 : Good F_Hlc_11 D_Hlc_11 := S_Hlc_11 G_cc G_Hlc_12
theorem G_Hlc_10 : Good F_Hlc_10 D_Hlc_10 := S_Hlc_10 G_cc G_Hlc_11
theorem G_Hlc_9 : Good F_Hlc_9 D_Hlc_9 := S_Hlc_9 G_cc G_Hlc_10
theorem G_Hlc_8 : Good F_Hlc_8 D_Hlc_8 := S_Hlc_8 G_cc G_Hlc_9
theorem G_Hlc_7 : Good F_Hlc_7 D_Hlc_7 := S_Hlc_7 G_cc G_Hlc_8
theorem G_Hlc_6 : Good F_Hlc_6 D_Hlc_6 := S_Hlc_6 G_cc G_Hlc_7
theorem G_Hlc_5 : Good F_Hlc_5 D_Hlc_5 := S_Hlc_5 G_cc G_Hlc_6
theorem G_Hlc_4 : Good F_Hlc_4 D_Hlc_4 := S_Hlc_4 G_cc G_Hlc_5
theorem G_Hlc_3 : Good F_Hlc_3 D_Hlc_3 := S_Hlc_3 G_cc G_Hlc_4
theorem G_Hlc_2 : Good F_Hlc_2 D_Hlc_2 := S_Hlc_2 G_cc G_Hlc_3
theorem G_Hlc_1 : Good F_Hlc_1 D_Hlc_1 := S_Hlc_1 G_cc G_Hlc_2
theorem G_Hlc : Good F_Hlc D_Hlc := S_Hlc G_cc G_Hlc_1
theorem G_Ylc : Good F_Ylc D_Ylc := S_Ylc G_cc G_Hlc
theorem G_lc : Good F_lc D_lc := S_lc G_cc G_Ylc
theorem G_hlc : Good F_hlc D_hlc := S_hlc G_lc
theorem G_Bc0 : Good F_Bc0 D_Bc0 := S_Bc0 G_L G_hlc
theorem G_Bc : Good F_Bc D_Bc := S_Bc G_Bc0
theorem G_cAc : Good F_cAc D_cAc := S_cAc G_c G_Acc
theorem G_ccAc : Good F_ccAc D_ccAc := S_ccAc G_c G_cAc
theorem G_mccAc : Good F_mccAc D_mccAc := S_mccAc G_ccAc
theorem G_Ec0 : Good F_Ec0 D_Ec0 := S_Ec0 G_Bc G_mccAc
theorem G_Ec : Good F_Ec D_Ec := S_Ec G_Ec0
theorem G_mcc : Good F_mcc D_mcc := S_mcc G_cc
theorem G_omcc : Good F_omcc D_omcc := S_omcc G_one G_mcc
theorem G_omcci : Good F_omcci D_omcci := S_omcci G_omcc
theorem G_Bci : Good F_Bci D_Bci := S_Bci G_Bc
theorem G_t1 : Good F_t1 D_t1 := S_t1 G_Ec G_omcci
theorem G_t2 : Good F_t2 D_t2 := S_t2 G_t1 G_Bci
theorem G_tAcc : Good F_tAcc D_tAcc := S_tAcc G_Acc
theorem G_t2x2 : Good F_t2x2 D_t2x2 := S_t2x2 G_t2
theorem G_Fsc : Good F_Fsc D_Fsc := S_Fsc G_tAcc G_t2x2
theorem G_R0 : Good F_R0 D_R0 := S_R0 G_gam G_Fsc
theorem G_R : Good F_R D_R := S_R G_R0
theorem G_E2 : Good F_E2 D_E2 := S_E2 G_Ec
theorem G_E3 : Good F_E3 D_E3 := S_E3 G_E2 G_Ec
theorem G_twoB : Good F_twoB D_twoB := S_twoB G_Bc
theorem G_twoBmcc : Good F_twoBmcc D_twoBmcc := S_twoBmcc G_twoB G_mcc
theorem G_w1 : Good F_w1 D_w1 := S_w1 G_E3 G_twoBmcc
theorem G_w2 : Good F_w2 D_w2 := S_w2 G_w1 G_Si
theorem G_om2 : Good F_om2 D_om2 := S_om2 G_omcci
theorem G_w3 : Good F_w3 D_w3 := S_w3 G_w2 G_om2
theorem G_B2 : Good F_B2 D_B2 := S_B2 G_Bci
theorem G_B3 : Good F_B3 D_B3 := S_B3 G_B2 G_Bci
theorem G_w4 : Good F_w4 D_w4 := S_w4 G_w3 G_B3
theorem G_W0 : Good F_W0 D_W0 := S_W0 G_w4
theorem G_W : Good F_W D_W := S_W G_W0
theorem G_hd_ : Good F_hd_ D_hd_ := S_hd_ G_h G_d
theorem G_dd2 : Good F_dd2 D_dd2 := S_dd2 G_d
theorem G_mdd2 : Good F_mdd2 D_mdd2 := S_mdd2 G_dd2
theorem G_qhd : Good F_qhd D_qhd := S_qhd G_q G_hd_
theorem G_qp2 : Good F_qp2 D_qp2 := S_qp2 G_qhd G_mdd2
theorem G_tR : Good F_tR D_tR := S_tR G_R
theorem G_A1 : Good F_A1 D_A1 := S_A1 G_j G_tR
theorem G_qA1 : Good F_qA1 D_qA1 := S_qA1 G_q G_A1
theorem G_num0 : Good F_num0 D_num0 := S_num0 G_qA1 G_mone
theorem G_num0t : Good F_num0t D_num0t := S_num0t G_num0
theorem G_Jt : Good F_Jt D_Jt := S_Jt G_J
theorem G_Jti : Good F_Jti D_Jti := S_Jti G_Jt
theorem G_U0 : Good F_U0 D_U0 := S_U0 G_num0t G_Jti
theorem G_U : Good F_U D_U := S_U G_U0 G_d
theorem G_num0j : Good F_num0j D_num0j := S_num0j G_num0 G_j
theorem G_md : Good F_md D_md := S_md G_d
theorem G_hmd : Good F_hmd D_hmd := S_hmd G_h G_md
theorem G_hmdA1 : Good F_hmdA1 D_hmdA1 := S_hmdA1 G_hmd G_A1
theorem G_hmdA1J : Good F_hmdA1J D_hmdA1J := S_hmdA1J G_hmdA1 G_J
theorem G_mhmdA1J : Good F_mhmdA1J D_mhmdA1J := S_mhmdA1J G_hmdA1J
theorem G_NV : Good F_NV D_NV := S_NV G_num0j G_mhmdA1J
theorem G_NVt : Good F_NVt D_NVt := S_NVt G_NV
theorem G_NVJ : Good F_NVJ D_NVJ := S_NVJ G_NVt G_Jti
theorem G_qJ : Good F_qJ D_qJ := S_qJ G_q G_J
theorem G_qpJw : Good F_qpJw D_qpJw := S_qpJw G_qp2 G_Jw
theorem G_sumZ : Good F_sumZ D_sumZ := S_sumZ G_qJ G_qpJw
theorem G_sumZSi : Good F_sumZSi D_sumZSi := S_sumZSi G_sumZ G_Si
theorem G_msumZSi : Good F_msumZSi D_msumZSi := S_msumZSi G_sumZSi
theorem G_Z : Good F_Z D_Z := S_Z G_hmd G_msumZSi
theorem G_dJ : Good F_dJ D_dJ := S_dJ G_d G_J
theorem G_dJSi : Good F_dJSi D_dJSi := S_dJSi G_dJ G_Si
theorem G_onep : Good F_onep D_onep := S_onep G_one G_dJSi
theorem G_qonep : Good F_qonep D_qonep := S_qonep G_q G_onep
theorem G_z : Good F_z D_z := S_z G_qonep
theorem G_dU : Good F_dU D_dU := S_dU G_d G_U
theorem G_zz : Good F_zz D_zz := S_zz G_z
theorem G_Wzz : Good F_Wzz D_Wzz := S_Wzz G_W G_zz
theorem G_mWzz : Good F_mWzz D_mWzz := S_mWzz G_Wzz
theorem G_qq : Good F_qq D_qq := S_qq G_q G_qp2
theorem G_qqdU : Good F_qqdU D_qqdU := S_qqdU G_qq G_dU
theorem G_m : Good F_m D_m := S_m G_qqdU G_mWzz
theorem G_Wz : Good F_Wz D_Wz := S_Wz G_W G_z
theorem G_WzZ : Good F_WzZ D_WzZ := S_WzZ G_Wz G_Z
theorem G_mWzZ : Good F_mWzZ D_mWzZ := S_mWzZ G_WzZ
theorem G_Us : Good F_Us D_Us := S_Us G_U G_mWzZ
theorem G_ZZ : Good F_ZZ D_ZZ := S_ZZ G_Z
theorem G_JwW : Good F_JwW D_JwW := S_JwW G_Jw G_W
theorem G_JwWZZ : Good F_JwWZZ D_JwWZZ := S_JwWZZ G_JwW G_ZZ
theorem G_mJwWZZ : Good F_mJwWZZ D_mJwWZZ := S_mJwWZZ G_JwWZZ
theorem G_tJw : Good F_tJw D_tJw := S_tJw G_Jw
theorem G_tJwNVJ : Good F_tJwNVJ D_tJwNVJ := S_tJwNVJ G_tJw G_NVJ
theorem G_inner : Good F_inner D_inner := S_inner G_tJwNVJ G_mJwWZZ
theorem G_mInner : Good F_mInner D_mInner := S_mInner G_m G_inner
theorem G_UsUs : Good F_UsUs D_UsUs := S_UsUs G_Us
theorem G_JwUsUs : Good F_JwUsUs D_JwUsUs := S_JwUsUs G_Jw G_UsUs
theorem G_mJwUsUs : Good F_mJwUsUs D_mJwUsUs := S_mJwUsUs G_JwUsUs
theorem G_coef : Good F_coef D_coef := S_coef G_mInner G_mJwUsUs
theorem G_dR : Good F_dR D_dR := S_dR G_d G_R
theorem G_JJw : Good F_JJw D_JJw := S_JJw G_J G_Jw
theorem G_tdR : Good F_tdR D_tdR := S_tdR G_dR
theorem G_JJw2dR : Good F_JJw2dR D_JJw2dR := S_JJw2dR G_JJw G_tdR
theorem G_qT : Good F_qT D_qT := S_qT G_q G_JJw2dR
theorem G_Jh : Good F_Jh D_Jh := S_Jh G_J G_h
theorem G_Jhm1 : Good F_Jhm1 D_Jhm1 := S_Jhm1 G_Jh G_mone
theorem G_dJh : Good F_dJh D_dJh := S_dJh G_d G_Jhm1
theorem G_auN : Good F_auN D_auN := S_auN G_qT G_dJh
theorem G_auNt : Good F_auNt D_auNt := S_auNt G_auN
theorem G_au : Good F_au D_au := S_au G_auNt G_Jti
theorem G_dq : Good F_dq D_dq := S_dq G_d G_q
theorem G_dqJ : Good F_dqJ D_dqJ := S_dqJ G_dq G_J
theorem G_dqJSi : Good F_dqJSi D_dqJSi := S_dqJSi G_dqJ G_Si
theorem G_qdq : Good F_qdq D_qdq := S_qdq G_q G_dqJSi
theorem G_zu : Good F_zu D_zu := S_zu G_qdq
theorem G_zuzu : Good F_zuzu D_zuzu := S_zuzu G_zu
theorem G_Wzuzu : Good F_Wzuzu D_Wzuzu := S_Wzuzu G_W G_zuzu
theorem G_mWzuzu : Good F_mWzuzu D_mWzuzu := S_mWzuzu G_Wzuzu
theorem G_m11 : Good F_m11 D_m11 := S_m11 G_au G_mWzuzu

end CKLaneA3X
