import CKLaneA3X.Data05

/-! Generated by num/gen_par.py (Lane A3): chain steps as lemmas over their inputs. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedTactic false

namespace CKLaneA3X

theorem S_UsUs (G_Us : Good F_Us D_Us) : Good F_UsUs D_UsUs :=
  (TMd.mul_good G_Us G_Us 1 1 24 (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)).of_eq (by decide +kernel) rfl (by decide +kernel)

end CKLaneA3X
