import CKLaneA3X.DataH_HcG

/-! Generated by num/gen_hsplit.py (Lane A3): one Horner iteration. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000
set_option linter.unusedVariables false

namespace CKLaneA3X

theorem S_HcG_11 (G_cGcG : Good F_cGcG D_cGcG) (G_HcG_12 : Good F_HcG_12 D_HcG_12) : Good F_HcG_11 D_HcG_11 :=
  (hornerSplit_good G_cGcG 2 24 (by decide +kernel) (by decide +kernel) (by decide +kernel) ((1 : ℚ) / 23) (List.drop 11 (atanhCoeffs 14)) (List.drop 12 (atanhCoeffs 14)) (by decide +kernel) G_HcG_12 (by decide +kernel)).of_eq (by decide +kernel) (by decide +kernel) (by decide +kernel)

end CKLaneA3X
