import CKLaneA2.Diag6.M00
import CKLaneA2.Diag6.M01
import CKLaneA2.Diag6.M02
import CKLaneA2.Diag6.M03
import CKLaneA2.Diag6.M04
import CKLaneA2.Diag6.M05
import CKLaneA2.Diag6.M06
import CKLaneA2.Diag6.M07
import CKLaneA2.Diag6.M08
import CKLaneA2.Diag6.M09
import CKLaneA2.Diag6.M10
import CKLaneA2.Diag6.M11
import CKLaneA2.Diag6.M12
import CKLaneA2.Diag6.M13
import CKLaneA2.Diag6.M14
import CKLaneA2.Diag6.M15
import CKLaneA2.Diag6.M16
import CKLaneA2.Diag6.M17
import CKLaneA2.Diag6.M18
import CKLaneA2.Diag6.M19
import CKLaneA2.Diag6.M20
import CKLaneA2.Diag6.M21
import CKLaneA2.Diag6.M22
import CKLaneA2.Diag6.M23
import CKLaneA2.Diag6.M24
import CKLaneA2.Diag6.M25
import CKLaneA2.Diag6.M26
import CKLaneA2.Diag6.M27
import CKLaneA2.Diag6.M28
import CKLaneA2.Diag6.M29
import GeneralCK.CorrectionComplementCharts

/-!
GENERATED by A2/gen/emit_a2.py (C=24): ChartOwners slot `diagonal6`, u ∈ [37/100, 19/50],
rho ∈ [0, 3/10]; 449 checker cells (Lane A cover), 30 cell modules.
Checker: Lane A `CKLaneA.Cell.treeOK` / `actual_of_tree` (reused verbatim). The degenerate edge
rho = 0 (kdet -> 0) is excluded through the `0 < rho` binder of `SignsOnBox`.
-/

namespace CKLaneA2.Diag6
open CKLaneA.Cell CKLaneA2

def n6 : Tree := .sr (3 / 80 : ℚ) n7 n38
theorem n6_ok : treeOK (37 / 100 : ℚ) (297 / 800 : ℚ) (0 : ℚ) (3 / 40 : ℚ) n6 = true :=
  treeOK_sr (by decide +kernel) n7_ok n38_ok
def n5 : Tree := .sr (3 / 40 : ℚ) n6 n61
theorem n5_ok : treeOK (37 / 100 : ℚ) (297 / 800 : ℚ) (0 : ℚ) (3 / 20 : ℚ) n5 = true :=
  treeOK_sr (by decide +kernel) n6_ok n61_ok
def n4 : Tree := .sr (3 / 20 : ℚ) n5 n82
theorem n4_ok : treeOK (37 / 100 : ℚ) (297 / 800 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n4 = true :=
  treeOK_sr (by decide +kernel) n5_ok n82_ok
def n107 : Tree := .sr (3 / 80 : ℚ) n108 n139
theorem n107_ok : treeOK (297 / 800 : ℚ) (149 / 400 : ℚ) (0 : ℚ) (3 / 40 : ℚ) n107 = true :=
  treeOK_sr (by decide +kernel) n108_ok n139_ok
def n106 : Tree := .sr (3 / 40 : ℚ) n107 n162
theorem n106_ok : treeOK (297 / 800 : ℚ) (149 / 400 : ℚ) (0 : ℚ) (3 / 20 : ℚ) n106 = true :=
  treeOK_sr (by decide +kernel) n107_ok n162_ok
def n105 : Tree := .sr (3 / 20 : ℚ) n106 n183
theorem n105_ok : treeOK (297 / 800 : ℚ) (149 / 400 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n105 = true :=
  treeOK_sr (by decide +kernel) n106_ok n183_ok
def n3 : Tree := .su (297 / 800 : ℚ) n4 n105
theorem n3_ok : treeOK (37 / 100 : ℚ) (149 / 400 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n3 = true :=
  treeOK_su (by decide +kernel) n4_ok n105_ok
def n209 : Tree := .sr (3 / 80 : ℚ) n210 n241
theorem n209_ok : treeOK (149 / 400 : ℚ) (299 / 800 : ℚ) (0 : ℚ) (3 / 40 : ℚ) n209 = true :=
  treeOK_sr (by decide +kernel) n210_ok n241_ok
def n208 : Tree := .sr (3 / 40 : ℚ) n209 n266
theorem n208_ok : treeOK (149 / 400 : ℚ) (299 / 800 : ℚ) (0 : ℚ) (3 / 20 : ℚ) n208 = true :=
  treeOK_sr (by decide +kernel) n209_ok n266_ok
def n207 : Tree := .sr (3 / 20 : ℚ) n208 n289
theorem n207_ok : treeOK (149 / 400 : ℚ) (299 / 800 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n207 = true :=
  treeOK_sr (by decide +kernel) n208_ok n289_ok
def n316 : Tree := .sr (3 / 80 : ℚ) n317 n348
theorem n316_ok : treeOK (299 / 800 : ℚ) (3 / 8 : ℚ) (0 : ℚ) (3 / 40 : ℚ) n316 = true :=
  treeOK_sr (by decide +kernel) n317_ok n348_ok
def n315 : Tree := .sr (3 / 40 : ℚ) n316 n375
theorem n315_ok : treeOK (299 / 800 : ℚ) (3 / 8 : ℚ) (0 : ℚ) (3 / 20 : ℚ) n315 = true :=
  treeOK_sr (by decide +kernel) n316_ok n375_ok
def n314 : Tree := .sr (3 / 20 : ℚ) n315 n398
theorem n314_ok : treeOK (299 / 800 : ℚ) (3 / 8 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n314 = true :=
  treeOK_sr (by decide +kernel) n315_ok n398_ok
def n206 : Tree := .su (299 / 800 : ℚ) n207 n314
theorem n206_ok : treeOK (149 / 400 : ℚ) (3 / 8 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n206 = true :=
  treeOK_su (by decide +kernel) n207_ok n314_ok
def n2 : Tree := .su (149 / 400 : ℚ) n3 n206
theorem n2_ok : treeOK (37 / 100 : ℚ) (3 / 8 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n2 = true :=
  treeOK_su (by decide +kernel) n3_ok n206_ok
def n427 : Tree := .sr (3 / 80 : ℚ) n428 n459
theorem n427_ok : treeOK (3 / 8 : ℚ) (301 / 800 : ℚ) (0 : ℚ) (3 / 40 : ℚ) n427 = true :=
  treeOK_sr (by decide +kernel) n428_ok n459_ok
def n426 : Tree := .sr (3 / 40 : ℚ) n427 n488
theorem n426_ok : treeOK (3 / 8 : ℚ) (301 / 800 : ℚ) (0 : ℚ) (3 / 20 : ℚ) n426 = true :=
  treeOK_sr (by decide +kernel) n427_ok n488_ok
def n425 : Tree := .sr (3 / 20 : ℚ) n426 n511
theorem n425_ok : treeOK (3 / 8 : ℚ) (301 / 800 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n425 = true :=
  treeOK_sr (by decide +kernel) n426_ok n511_ok
def n540 : Tree := .sr (3 / 80 : ℚ) n541 n572
theorem n540_ok : treeOK (301 / 800 : ℚ) (151 / 400 : ℚ) (0 : ℚ) (3 / 40 : ℚ) n540 = true :=
  treeOK_sr (by decide +kernel) n541_ok n572_ok
def n539 : Tree := .sr (3 / 40 : ℚ) n540 n601
theorem n539_ok : treeOK (301 / 800 : ℚ) (151 / 400 : ℚ) (0 : ℚ) (3 / 20 : ℚ) n539 = true :=
  treeOK_sr (by decide +kernel) n540_ok n601_ok
def n538 : Tree := .sr (3 / 20 : ℚ) n539 n626
theorem n538_ok : treeOK (301 / 800 : ℚ) (151 / 400 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n538 = true :=
  treeOK_sr (by decide +kernel) n539_ok n626_ok
def n424 : Tree := .su (301 / 800 : ℚ) n425 n538
theorem n424_ok : treeOK (3 / 8 : ℚ) (151 / 400 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n424 = true :=
  treeOK_su (by decide +kernel) n425_ok n538_ok
def n656 : Tree := .sr (3 / 80 : ℚ) n657 n688
theorem n656_ok : treeOK (151 / 400 : ℚ) (303 / 800 : ℚ) (0 : ℚ) (3 / 40 : ℚ) n656 = true :=
  treeOK_sr (by decide +kernel) n657_ok n688_ok
def n655 : Tree := .sr (3 / 40 : ℚ) n656 n719
theorem n655_ok : treeOK (151 / 400 : ℚ) (303 / 800 : ℚ) (0 : ℚ) (3 / 20 : ℚ) n655 = true :=
  treeOK_sr (by decide +kernel) n656_ok n719_ok
def n654 : Tree := .sr (3 / 20 : ℚ) n655 n744
theorem n654_ok : treeOK (151 / 400 : ℚ) (303 / 800 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n654 = true :=
  treeOK_sr (by decide +kernel) n655_ok n744_ok
def n775 : Tree := .sr (3 / 80 : ℚ) n776 n807
theorem n775_ok : treeOK (303 / 800 : ℚ) (19 / 50 : ℚ) (0 : ℚ) (3 / 40 : ℚ) n775 = true :=
  treeOK_sr (by decide +kernel) n776_ok n807_ok
def n774 : Tree := .sr (3 / 40 : ℚ) n775 n838
theorem n774_ok : treeOK (303 / 800 : ℚ) (19 / 50 : ℚ) (0 : ℚ) (3 / 20 : ℚ) n774 = true :=
  treeOK_sr (by decide +kernel) n775_ok n838_ok
def n773 : Tree := .sr (3 / 20 : ℚ) n774 n867
theorem n773_ok : treeOK (303 / 800 : ℚ) (19 / 50 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n773 = true :=
  treeOK_sr (by decide +kernel) n774_ok n867_ok
def n653 : Tree := .su (303 / 800 : ℚ) n654 n773
theorem n653_ok : treeOK (151 / 400 : ℚ) (19 / 50 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n653 = true :=
  treeOK_su (by decide +kernel) n654_ok n773_ok
def n423 : Tree := .su (151 / 400 : ℚ) n424 n653
theorem n423_ok : treeOK (3 / 8 : ℚ) (19 / 50 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n423 = true :=
  treeOK_su (by decide +kernel) n424_ok n653_ok
def n1 : Tree := .su (3 / 8 : ℚ) n2 n423
theorem n1_ok : treeOK (37 / 100 : ℚ) (19 / 50 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n1 = true :=
  treeOK_su (by decide +kernel) n2_ok n423_ok

theorem slotTree_ok : treeOK (37 / 100 : ℚ) (19 / 50 : ℚ) (0 : ℚ) (3 / 10 : ℚ) n1 = true := n1_ok

end CKLaneA2.Diag6

namespace CKLaneA2.Slots
open GeneralCK GeneralCK.Correction GeneralCK.Correction.Complement CKLaneA.Cell

/-- strict owner on `[37/100, 19/50] × (0, 3/10]` -/
theorem diagonal6_actual : ∀ ⦃u rho : ℝ⦄, u ∈ Set.Icc (37 / 100 : ℝ) (19 / 50) →
    rho ∈ Set.Ioc (0 : ℝ) (3 / 10) → ActualRatioMinorsPositive u rho := by
  intro u rho hu hr
  exact actual_of_tree Diag6.slotTree_ok (by push_cast; linarith [hu.1])
    (by push_cast; linarith [hu.2]) (by push_cast; linarith [hr.1]) (by push_cast; linarith [hr.2])
    (by linarith [hu.1]) (by linarith [hu.2]) hr.1 (by linarith [hr.2])

/-- `ChartOwners.diagonal6` field type -/
theorem diagonal6_signs : SignsOnBox (37 / 100) (19 / 50) 0 (3 / 10) := by
  intro u rho _ _ hr _ hub hrb
  exact ratioSigns_of_positive (diagonal6_actual hub ⟨hr, hrb.2⟩)

end CKLaneA2.Slots
