import CKLaneG3.SChunkBind
import CKLaneG3.SCover
import CKLaneG3.S.ChunkG.G_5030010530431531
import CKLaneM1.MLPopulationDfs

/-! Lane G3b: (S) owner label 1, chunk block 14 (2 chunks, 3818 label leaves; generated by G3/pipeline/g3chunk.py). -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace CKLaneG3.S.C1.B14

open CKLaneD CKLaneG3

/-- chunk `50300105314304`: 1475 label-1 leaves. -/
theorem c_50300105314304 : ∀ q ∈ CKLaneG3.S.Chunk.C_50300105314304.t.leavesR [4, 0, 3, 4, 1, 3, 5, 0, 1, 0, 0, 3, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_range (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50300105314304.t 1 [4, 0, 3, 4, 1, 3, 5, 0, 1, 0, 0, 3, 0, 5] CKLaneM1.ML.Population.dfsList CKLaneM1.ML.Population.dfsList_sLeafOK 39198 1475 (by decide +kernel)

/-- chunk `50300105314305`: 2343 label-1 leaves. -/
theorem c_50300105314305 : ∀ q ∈ CKLaneG3.S.Chunk.C_50300105314305.t.leavesR [5, 0, 3, 4, 1, 3, 5, 0, 1, 0, 0, 3, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_range (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50300105314305.t 1 [5, 0, 3, 4, 1, 3, 5, 0, 1, 0, 0, 3, 0, 5] CKLaneM1.ML.Population.dfsList CKLaneM1.ML.Population.dfsList_sLeafOK 40673 2343 (by decide +kernel)

end CKLaneG3.S.C1.B14
