import CKLaneG3.SChunkBind
import CKLaneG3.SCover
import CKLaneG3.S.Chunk.C_502020300431512
import CKLaneG3.S.Chunk.C_502020300431513
import CKLaneG3.S.Chunk.C_50202030052
import CKLaneG3.S.Chunk.C_50202030053
import CKLaneG3.S.Chunk.C_50202030142
import CKLaneM03.G3Bridge
import CKLaneM03.Family.F01
import CKLaneM03.Family.F02

/-! Lane G3b: (S) owner label 2, chunk block 2 (5 chunks, 1726 label leaves; generated by G3/pipeline/g3chunk.py). -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace CKLaneG3.S.C2.B2

open CKLaneD CKLaneG3

noncomputable def SH : List (List (List ℕ)) := [
  CKLaneM03.EP.P0046.leaves,
  CKLaneM03.EP.P0047.leaves,
  CKLaneM03.EP.P0048.leaves,
  CKLaneM03.EP.P0049.leaves,
  CKLaneM03.EP.P0050.leaves,
  CKLaneM03.EP.P0051.leaves,
  CKLaneM03.EP.P0052.leaves,
  CKLaneM03.EP.P0053.leaves,
  CKLaneM03.EP.P0054.leaves,
  CKLaneM03.EP.P0055.leaves,
  CKLaneM03.EP.P0056.leaves,
  CKLaneM03.EP.P0057.leaves,
  CKLaneM03.EP.P0058.leaves,
  CKLaneM03.EP.P0059.leaves,
  CKLaneM03.EP.P0060.leaves,
  CKLaneM03.EP.P0061.leaves,
  CKLaneM03.EP.P0062.leaves
]

theorem SH_ok : ∀ S ∈ SH, ∀ x ∈ S, SLeafOK (sBox (id x)) :=
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0046.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0047.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0048.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0049.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0050.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0051.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0052.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0053.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0054.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0055.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0056.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0057.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0058.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0059.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0060.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0061.leaves_sem x hx))
  (shards_cons (fun x hx => CKLaneM03.sLeafOK_of_sem (CKLaneM03.EP.P0062.leaves_sem x hx))
   shards_nil)))))))))))))))))

def r_502020300431512_0 : List (ℕ × ℕ × ℕ) := [(0, 43, 70), (1, 0, 119), (2, 0, 40), (3, 0, 120), (4, 0, 66)]
/-- chunk `502020300431512`: 415 label-2 leaves. -/
theorem c_502020300431512 : ∀ q ∈ CKLaneG3.S.Chunk.C_502020300431512.t.leavesR [2, 1, 5, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 2 → SLeafOK (sBox q.1) :=
  sub_family_of_slices (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_502020300431512.t 2 [2, 1, 5, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] SH id SH_ok
    (r_502020300431512_0) (by decide +kernel)

def r_502020300431513_0 : List (ℕ × ℕ × ℕ) := [(5, 0, 120), (6, 0, 120), (7, 0, 118), (8, 0, 119), (9, 0, 58)]
/-- chunk `502020300431513`: 535 label-2 leaves. -/
theorem c_502020300431513 : ∀ q ∈ CKLaneG3.S.Chunk.C_502020300431513.t.leavesR [3, 1, 5, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 2 → SLeafOK (sBox q.1) :=
  sub_family_of_slices (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_502020300431513.t 2 [3, 1, 5, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] SH id SH_ok
    (r_502020300431513_0) (by decide +kernel)

/-- chunk `50202030052`: 0 label-2 leaves. -/
theorem c_50202030052 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202030052.t.leavesR [2, 5, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 2 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202030052.t 2 [2, 5, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `50202030053`: 0 label-2 leaves. -/
theorem c_50202030053 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202030053.t.leavesR [3, 5, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 2 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202030053.t 2 [3, 5, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

def r_50202030142_0 : List (ℕ × ℕ × ℕ) := [(10, 0, 120), (11, 0, 116), (12, 0, 118), (13, 0, 119), (14, 0, 120), (15, 0, 115), (16, 0, 68)]
/-- chunk `50202030142`: 776 label-2 leaves. -/
theorem c_50202030142 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202030142.t.leavesR [2, 4, 1, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 2 → SLeafOK (sBox q.1) :=
  sub_family_of_slices (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202030142.t 2 [2, 4, 1, 0, 3, 0, 2, 0, 2, 0, 5] SH id SH_ok
    (r_50202030142_0) (by decide +kernel)

end CKLaneG3.S.C2.B2
