import GeneralCK.Certificates.E8TAxisProd0558GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0558GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0558GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0558GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0558GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0558GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0558GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0558GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0558Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0558CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0558GraphCenterA.qJetBox,
   E8TAxisProd0558GraphCenterB.qJetBox,
   E8TAxisProd0558GraphCenterC.qJetBox,
   E8TAxisProd0558GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0558GraphWholeA.qJetBox,
   E8TAxisProd0558GraphWholeB.qJetBox,
   E8TAxisProd0558GraphWholeC.qJetBox,
   E8TAxisProd0558GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨5383722588522726074783903694195822281966381852, 5383722588522726074783903694195862885279756232⟩
  | 0, 2 => ⟨18395355722664998423582332687207887807206392915, 18395355722664998423582332687208020865701319374⟩
  | 1, 1 => ⟨18562125916885453251980965755565724544940718716, 18562125916885453251980965755565952110590077731⟩
  | 0, 3 => ⟨42744745009668784463636603303292269462762125031, 42744745009668784463636603303292680027529200606⟩
  | 1, 2 => ⟨58674243289787941492459714743014270705271753016, 58674243289787941492459714743014973620378256814⟩
  | 2, 1 => ⟨59141085897324170741095978430683283097592338774, 59141085897324170741095978430684523326029087119⟩
  | 0, 4 => ⟨82424699370971318461978464319551063250055071503, 82424699370971318461978464319552395751845772202⟩
  | 1, 3 => ⟨126673323513429971650159109849343925285735082686, 126673323513429971650159109849346260078720389285⟩
  | 2, 2 => ⟨171199059818796481858724685383320107519841996797, 171199059818796481858724685383324304127550720678⟩
  | 3, 1 => ⟨172373800738807413708902759042413950056974799169, 172373800738807413708902759042421580095234637707⟩
  | 0, 5 => ⟨-176955959407328063687720063812898103909937640126025, 178299323238577809916297336514213324247828047294350⟩
  | 1, 4 => ⟨-341923183671084078615887209305387885206379492121275, 343897846472270457344129108588714316465407402851156⟩
  | 2, 3 => ⟨-661934168683482824236866400166568590132349679272747, 664735672621535876966820562597143495405971640285213⟩
  | 3, 2 => ⟨-1282782136355194584113251856136837216155515915223560, 1286431718846628770011638058584306355206013707703458⟩
  | 4, 1 => ⟨-2487528295183280052910772859822877391258892155619156, 2491268646071618990639903043476192423634880583396979⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0558Geometry.ds, E8TAxisProd0558Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 5016667997614215857712529079455830599610556051 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0558CertifiedArithmetic
