import GeneralCK.Certificates.E8TAxisProd0679GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0679GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0679GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0679GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0679GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0679GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0679GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0679GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0679Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0679CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0679GraphCenterA.qJetBox,
   E8TAxisProd0679GraphCenterB.qJetBox,
   E8TAxisProd0679GraphCenterC.qJetBox,
   E8TAxisProd0679GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0679GraphWholeA.qJetBox,
   E8TAxisProd0679GraphWholeB.qJetBox,
   E8TAxisProd0679GraphWholeC.qJetBox,
   E8TAxisProd0679GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨3596158201347853994917146868974846227392762852, 3596158201347853994917146868974877349028838988⟩
  | 0, 2 => ⟨12746652703155367575263321007364703310876311036, 12746652703155367575263321007364800592054202838⟩
  | 1, 1 => ⟨12782368999759620906304593307746349647032239488, 12782368999759620906304593307746513185785244012⟩
  | 0, 3 => ⟨30428995828800087188726536007799049723593679966, 30428995828800087188726536007799344342159806703⟩
  | 1, 2 => ⟨41909783472686937597203330768149401553835748108, 41909783472686937597203330768149898664893479386⟩
  | 2, 1 => ⟨42012922724275885822271898152479549067146859086, 42012922724275885822271898152480418524542451697⟩
  | 0, 4 => ⟨60319931790667798035692373026473596139726692375, 60319931790667798035692373026474537547141092927⟩
  | 1, 3 => ⟨93394889195086714504960324250253362341244412266, 93394889195086714504960324250254991934905953599⟩
  | 2, 2 => ⟨126534267417380426257682095300359112829862922647, 126534267417380426257682095300362019830391257104⟩
  | 3, 1 => ⟨126803872843125687460780293707683076698549681270, 126803872843125687460780293707688329823646137385⟩
  | 0, 5 => ⟨-105249076877674779464561171773112257158795058758951, 106169190833687399879498316163054340058574776913432⟩
  | 1, 4 => ⟨-202417605078222568634197331767056423664337417641892, 203755295788596457786336465095748798396263682483767⟩
  | 2, 3 => ⟨-390234539374379109859466819224361465944593638018296, 392118742930286632345628083256181659105079630494589⟩
  | 3, 2 => ⟨-753280340953990782551838550802668399006928554108739, 755725351828585854836449295417508230354995741984856⟩
  | 4, 1 => ⟨-1455148492302014638240060879406410504603557467199541, 1457654548379726426117702806249518878087417769169606⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0679Geometry.ds, E8TAxisProd0679Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 3344312699596977733100455409121580653724241618 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0679CertifiedArithmetic
