import GeneralCK.Certificates.E8TAxisProd0514GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0514GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0514GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0514GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0514GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0514GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0514GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0514GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0514Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0514CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0514GraphCenterA.qJetBox,
   E8TAxisProd0514GraphCenterB.qJetBox,
   E8TAxisProd0514GraphCenterC.qJetBox,
   E8TAxisProd0514GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0514GraphWholeA.qJetBox,
   E8TAxisProd0514GraphWholeB.qJetBox,
   E8TAxisProd0514GraphWholeC.qJetBox,
   E8TAxisProd0514GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨7056439345861323451465957894949073877105073650, 7056439345861323451465957894949122802668067653⟩
  | 0, 2 => ⟨23482162423554543398260302562666850887561429641, 23482162423554543398260302562667016027054633128⟩
  | 1, 1 => ⟨23832936557018881745444227554937166255354777590, 23832936557018881745444227554937451623559627582⟩
  | 0, 3 => ⟨53519058176697444843517078916983068538087067554, 53519058176697444843517078916983583323600075818⟩
  | 1, 2 => ⟨73352848312073618761628162484163361749152315370, 73352848312073618761628162484164250679639282612⟩
  | 2, 1 => ⟨74313859453172933847644809969861137556323737764, 74313859453172933847644809969862714361969629447⟩
  | 0, 4 => ⟨101199319554798339291519649832826169605568123725, 101199319554798339291519649832827853924299374677⟩
  | 1, 3 => ⟨154848862056362414689854219106430246147163156071, 154848862056362414689854219106433217851910126149⟩
  | 2, 2 => ⟨209050013638928184062620083193702981439658645211, 209050013638928184062620083193708346479910746988⟩
  | 3, 1 => ⟨211408011554018215843813349170751976809033799941, 211408011554018215843813349170761766953014037428⟩
  | 0, 5 => ⟨-248535454782700081163103985469374627271058510047203, 250277739683106535585184374364240203766730949287262⟩
  | 1, 4 => ⟨-481519586875350089728308845657535692699388110657239, 484093339617367123442618663013619938849868772328706⟩
  | 2, 3 => ⟨-934446449594083936988569812813979527657233890839372, 938108360714644603920551392832821388967134961405641⟩
  | 3, 2 => ⟨-1815093616250272850358466219491533887264035779973755, 1819869658767353307922792841635555591148381290365118⟩
  | 4, 1 => ⟨-3527783415173514946830590226270193592428095754347449, 3532672721004224439664934478038478820755908173886289⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0514Geometry.ds, E8TAxisProd0514Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 6583982892977758178732567231611662757973934706 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0514CertifiedArithmetic
