import GeneralCK.Certificates.E8TAxisProd0012GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0012GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0012GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0012GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0012GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0012GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0012GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0012GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0012Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0012CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0012GraphCenterA.qJetBox,
   E8TAxisProd0012GraphCenterB.qJetBox,
   E8TAxisProd0012GraphCenterC.qJetBox,
   E8TAxisProd0012GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0012GraphWholeA.qJetBox,
   E8TAxisProd0012GraphWholeB.qJetBox,
   E8TAxisProd0012GraphWholeC.qJetBox,
   E8TAxisProd0012GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨14437175051920455869962789433053995442782, 14437175051920455869962789434083240342328⟩
  | 0, 2 => ⟨301626362018556519761480478277974781549455, 301626362018556519761480478281228062789039⟩
  | 1, 1 => ⟨317485955153869652035075373831334416429300, 317485955153869652035075373835289533444430⟩
  | 0, 3 => ⟨3177643024589874950259721460720830561537955, 3177643024589874950259721460725794829181840⟩
  | 1, 2 => ⟨5398409630070571325017393788722451669252698, 5398409630070571325017393788727903257798947⟩
  | 2, 1 => ⟨5612994703189318325486884108127711248735906, 5612994703189318325486884108134527985108094⟩
  | 0, 4 => ⟨15079393078100928912069535120798186734383632, 15079393078100928912069535120812912363352064⟩
  | 1, 3 => ⟨43726470546803252012501885165395972356051731, 43726470546803252012501885165412137184445548⟩
  | 2, 2 => ⟨73325013477048032345630182773904677151166156, 73325013477048032345630182773925420366614438⟩
  | 3, 1 => ⟨75309499115605201366159995554810588726572237, 75309499115605201366159995554841587305918414⟩
  | 0, 5 => ⟨-148806115050039486149294733413490711834238537305, 148408243550329373397698195753164666220956288161⟩
  | 1, 4 => ⟨-225217929637481490247605394205435305795314456649, 222797820470014388233839663669797512608430862386⟩
  | 2, 3 => ⟨-360328325790593186462478095937747902545174415489, 355498143104405842729171184485565871813242481039⟩
  | 3, 2 => ⟨-585427659955855585163536474592236657625883095341, 578312525888081900119931317643119100071088257780⟩
  | 4, 1 => ⟨-941858373924746162689039818331631543053508807522, 935265310519564201084018062189189599004973597514⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0012Geometry.ds, E8TAxisProd0012Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 9744473713936238276254828210720165747595 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0012CertifiedArithmetic
