import GeneralCK.Certificates.E8TAxisProd0281GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0281GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0281GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0281GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0281GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0281GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0281GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0281GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0281Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0281CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0281GraphCenterA.qJetBox,
   E8TAxisProd0281GraphCenterB.qJetBox,
   E8TAxisProd0281GraphCenterC.qJetBox,
   E8TAxisProd0281GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0281GraphWholeA.qJetBox,
   E8TAxisProd0281GraphWholeB.qJetBox,
   E8TAxisProd0281GraphWholeC.qJetBox,
   E8TAxisProd0281GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨38507697674252286148964491026483437038098739672, 38507697674252286148964491026483637253315043128⟩
  | 0, 2 => ⟨112155289845676170238473634275891902082073189263, 112155289845676170238473634275892695507356981900⟩
  | 1, 1 => ⟨113441213310093745499334899033244567695463760675, 113441213310093745499334899033246013027335550730⟩
  | 0, 3 => ⟨225468141569379301024491365266286857693249210479, 225468141569379301024491365266289475850437855610⟩
  | 1, 2 => ⟨303198692093047014522556944314618902648404288824, 303198692093047014522556944314623628631705397620⟩
  | 2, 1 => ⟨306252053623733233493298765104224135448288742103, 306252053623733233493298765104232780248640348634⟩
  | 0, 4 => ⟨376427036415956579735714669270349226704704338842, 376427036415956579735714669270358273212686173255⟩
  | 1, 3 => ⟨559187991600315553853053447343499643324843378567, 559187991600315553853053447343516171414623322621⟩
  | 2, 2 => ⟨743412672232392193529615155858757348923232945407, 743412672232392193529615155858787926345169162568⟩
  | 3, 1 => ⟨749977114017829454693192890137592318013152244564, 749977114017829454693192890137649323034486819477⟩
  | 0, 5 => ⟨-1862918733037181249922156769837508892951500110488484, 1872932476498095333072701928537588088258174494348968⟩
  | 1, 4 => ⟨-3651908674398149110359662266482562505920654527773957, 3667027979785777346916464890458864098744944355896745⟩
  | 2, 3 => ⟨-7165762902488285924400302663972368410928762937109573, 7187592050323425581009376030542582577951488956205536⟩
  | 3, 2 => ⟨-14069799711884025470874147921414568964906462738219158, 14098517530798166485886717302834578198389162103827507⟩
  | 4, 1 => ⟨-27639898718222142579750560491414214271165926754483019, 27669407010064898038881527889977168229340271832395367⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0281Geometry.ds, E8TAxisProd0281Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 36216574469630016954669497113698145187209359168 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0281CertifiedArithmetic
