import GeneralCK.Certificates.E8TAxisProd0327GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0327GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0327GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0327GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0327GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0327GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0327GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0327GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0327Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0327CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0327GraphCenterA.qJetBox,
   E8TAxisProd0327GraphCenterB.qJetBox,
   E8TAxisProd0327GraphCenterC.qJetBox,
   E8TAxisProd0327GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0327GraphWholeA.qJetBox,
   E8TAxisProd0327GraphWholeB.qJetBox,
   E8TAxisProd0327GraphWholeC.qJetBox,
   E8TAxisProd0327GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨19820558161352353665936983166848822578991437779, 19820558161352353665936983166848933672415863563⟩
  | 0, 2 => ⟨61099550735264640189316155630414466285051163689, 61099550735264640189316155630414883161150359093⟩
  | 1, 1 => ⟨61688201723984179240809156286662931272286141267, 61688201723984179240809156286663677682793108122⟩
  | 0, 3 => ⟨129270355606059225338686300840708451345687294386, 129270355606059225338686300840709798032576248517⟩
  | 1, 2 => ⟨174857438197678512328342956685532507867581554787, 174857438197678512328342956685534902683278325443⟩
  | 2, 1 => ⟨176331730387064387529303292616778823210184194926, 176331730387064387529303292616783155165625783685⟩
  | 0, 4 => ⟨226155288948368295085976508797537335562711607328, 226155288948368295085976508797541877083077769365⟩
  | 1, 3 => ⟨339386194238708199778218239288408722403653060656, 339386194238708199778218239288416922644710447993⟩
  | 2, 2 => ⟨453365800630864028086107767686857266491283251032, 453365800630864028086107767686872303792951874325⟩
  | 3, 1 => ⟨456669044193284279682027127665484744022589240346, 456669044193284279682027127665512554423862107621⟩
  | 0, 5 => ⟨-888457938381466916165420170518417670127318607805076, 893612583909657806736630904846602033972387266906179⟩
  | 1, 4 => ⟨-1735309353836647052486057017912878292832679732028933, 1743049224222572405042775516673099317941685859776680⟩
  | 2, 3 => ⟨-3393063512422052533090506429369377461615322528872524, 3404194343769280512226215835563888530720154993960300⟩
  | 3, 2 => ⟨-6639114230283506753795747804056639085434966493881975, 6653713827374158928535378817744040562112068181467743⟩
  | 4, 1 => ⟨-12997291387580440784582185857556470322501453138791247, 13012228216217403850041696686499027856510512324479716⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0327Geometry.ds, E8TAxisProd0327Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 18582315929646713860570835124385978578852741405 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0327CertifiedArithmetic
