import GeneralCK.Certificates.E8TAxisProd0621GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0621GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0621GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0621GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0621GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0621GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0621GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0621GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0621Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0621CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0621GraphCenterA.qJetBox,
   E8TAxisProd0621GraphCenterB.qJetBox,
   E8TAxisProd0621GraphCenterC.qJetBox,
   E8TAxisProd0621GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0621GraphWholeA.qJetBox,
   E8TAxisProd0621GraphWholeB.qJetBox,
   E8TAxisProd0621GraphWholeC.qJetBox,
   E8TAxisProd0621GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨9662018121126666288968791446024319225167384906, 9662018121126666288968791446024381850718138333⟩
  | 0, 2 => ⟨31735931919369444266966681738999799966714512001, 31735931919369444266966681739000019235195581805⟩
  | 1, 1 => ⟨31847132015065938563191106769732790139593525482, 31847132015065938563191106769733173963403187145⟩
  | 0, 3 => ⟨70908809062269114379869480279627339458931061343, 70908809062269114379869480279628031139699999874⟩
  | 1, 2 => ⟨96473983269135008055333548138261756625877163248, 96473983269135008055333548138262963677894480467⟩
  | 2, 1 => ⟨96769964156702858019659883218213655275146438739, 96769964156702858019659883218215810623844525509⟩
  | 0, 4 => ⟨130949515659354893152620642882456236838312038886, 130949515659354893152620642882458517631977530352⟩
  | 1, 3 => ⟨198791253779493866771924234926396883919903468540, 198791253779493866771924234926400942007972346622⟩
  | 2, 2 => ⟨266795790210818405748102231657922916411896761080, 266795790210818405748102231657930282231932424327⟩
  | 3, 1 => ⟨267499186720421370442837434309501702939979612870, 267499186720421370442837434309515204095547944218⟩
  | 0, 5 => ⟨-380819007609926722995863086951617668367295690728786, 383282815964667907403032920141856560147348685532357⟩
  | 1, 4 => ⟨-740055990727526173798627079171328944626245380983344, 743717726684841727506158817612177056164039784395060⟩
  | 2, 3 => ⟨-1440165717621811782779245230183161359404772041362479, 1445396132453144282876232921649916113795687033059281⟩
  | 3, 2 => ⟨-2804876885450030057752515354948781380079095254022069, 2811711675453930551924539191030762657598008123285771⟩
  | 4, 1 => ⟨-5465792231497925682260413913554152682957028262069532, 5472779368468672943994767211077799086206461860897056⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0621Geometry.ds, E8TAxisProd0621Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 9027406596494168873568357450173000489450530440 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0621CertifiedArithmetic
