import GeneralCK.Certificates.E8TAxisProd0337GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0337GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0337GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0337GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0337GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0337GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0337GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0337GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0337Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0337CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0337GraphCenterA.qJetBox,
   E8TAxisProd0337GraphCenterB.qJetBox,
   E8TAxisProd0337GraphCenterC.qJetBox,
   E8TAxisProd0337GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0337GraphWholeA.qJetBox,
   E8TAxisProd0337GraphWholeB.qJetBox,
   E8TAxisProd0337GraphWholeC.qJetBox,
   E8TAxisProd0337GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨85513867069556815832640373935131589083198637630, 85513867069556815832640373935132031243387894432⟩
  | 0, 2 => ⟨234306365258700495177349103579930183410557821700, 234306365258700495177349103579932036372905518499⟩
  | 1, 1 => ⟨235680995269120774925153784570075505742877669490, 235680995269120774925153784570078940303763609657⟩
  | 0, 3 => ⟨444591723778939229852082490021528968998727634123, 444591723778939229852082490021535271728243101573⟩
  | 1, 2 => ⟨592763373037298479415177814177555910685748752802, 592763373037298479415177814177567473431937759748⟩
  | 2, 1 => ⟨595851062293928111375632508424794555974506199620, 595851062293928111375632508424815985391124427475⟩
  | 0, 4 => ⟨707386698601739914177887452404365920622146584443, 707386698601739914177887452404388605898004707007⟩
  | 1, 3 => ⟨1038539223594556476817000768330205840144681808135, 1038539223594556476817000768330247842522589810160⟩
  | 2, 2 => ⟨1371103149281562307336874522313815247801165741189, 1371103149281562307336874522313893788917079390798⟩
  | 3, 1 => ⟨1377521255743425073785415900001558012599310549825, 1377521255743425073785415900001705889464149667802⟩
  | 0, 5 => ⟨-4278625402832872975440675889606049138610909028116586, 4298164802829854295065362655950833809442227447450650⟩
  | 1, 4 => ⟨-8416609777433419870421752575186291894982949850341189, 8446014100804276636259461208578097096731769512494885⟩
  | 2, 3 => ⟨-16571442436716616513039669683035338393612486424681579, 16613757007681934870828422263273842800738334885858640⟩
  | 3, 2 => ⟨-32648459239263436323812843063381961805165843196835336, 32703928939401213724458879824738737398591770262176050⟩
  | 4, 1 => ⟨-64356940821818022370510987750433046262358380058923709, 64413532490621498247237981044176345802754706952504472⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0337Geometry.ds, E8TAxisProd0337Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 80728034153544240908452064453572891098140442575 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0337CertifiedArithmetic
