import GeneralCK.Certificates.E8TAxisZero0036GraphCenterA
import GeneralCK.Certificates.E8TAxisZero0036GraphCenterB
import GeneralCK.Certificates.E8TAxisZero0036GraphCenterC
import GeneralCK.Certificates.E8TAxisZero0036GraphCenterD
import GeneralCK.Certificates.E8TAxisZero0036GraphWholeA
import GeneralCK.Certificates.E8TAxisZero0036GraphWholeB
import GeneralCK.Certificates.E8TAxisZero0036GraphWholeC
import GeneralCK.Certificates.E8TAxisZero0036GraphWholeD
import GeneralCK.Certificates.E8TAxisRegularInverseBoxes
import GeneralCK.Certificates.E8TAxisZero0036Geometry
import GeneralCK.Certificates.E8TAxisRegularCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisZero0036CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisRegularCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisZero0036GraphCenterA.qJetBox,
   E8TAxisZero0036GraphCenterB.qJetBox,
   E8TAxisZero0036GraphCenterC.qJetBox,
   E8TAxisZero0036GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisZero0036GraphWholeA.qJetBox,
   E8TAxisZero0036GraphWholeB.qJetBox,
   E8TAxisZero0036GraphWholeC.qJetBox,
   E8TAxisZero0036GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨1828811560661898641528227423674087226492449399, 1828811560661898641528227423674104980094124749⟩
  | 0, 2 => ⟨6833823808167856875010183645664242754867826252, 6833823808167856875010183645664297525376148297⟩
  | 1, 1 => ⟨6842097665566567260320792371704530735014609743, 6842097665566567260320792371704624163363076421⟩
  | 0, 3 => ⟨16976186613133925697926654142162543415832707543, 16976186613133925697926654142162706375871331027⟩
  | 1, 2 => ⟨23607813764591779665854518870569679645931415006, 23607813764591779665854518870569956781853702768⟩
  | 2, 1 => ⟨23632895912218162676770848531762975384349056606, 23632895912218162676770848531763456113442452886⟩
  | 0, 4 => ⟨35037492286413783923302043446298295094879312359, 35037492286413783923302043446302127625734599464⟩
  | 1, 3 => ⟨55121018917360596153815139505013926794125624795, 55121018917360596153815139505014810573205140417⟩
  | 2, 2 => ⟨75221591089860703412268531185662493006411731454, 75221591089860703412268531185664055204695113683⟩
  | 3, 1 => ⟨75291296548244541856293868081597229183098347395, 75291296548244541856293868081600022476190183763⟩
  | 0, 5 => ⟨-510000394158222282333385745987975215892301175689233, 511555771131475429124088647675237791495319700360867⟩
  | 1, 4 => ⟨-991434701877169668824423960608400418882082721925104, 993577358219781817309602868639311661782974043663113⟩
  | 2, 3 => ⟨-1929300456456881121638374192169947660517883982521350, 1932207684634114504220638532069576559538001441362001⟩
  | 3, 2 => ⟨-3756324759451196317634615914150830917777979747054562, 3760045585550452237550297996940890309202512308562869⟩
  | 4, 1 => ⟨-7315593578379141308106824245159741836453212108536470, 7319534164465836303502276980549754446401649125429368⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisZero0036Geometry.ds, E8TAxisZero0036Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 1278043446085374403982333801631627214291511111 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsRegularAt s t) :
    data.CenterEnclosed (mixed E8TAxisRegularGermJet.regularQJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_regular_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_regular_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_regular_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_regular_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_regular_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_regular_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_regular_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_regular_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_regular_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_regular_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsRegularAt s t) :
    data.RemainderEnclosed (mixed E8TAxisRegularGermJet.regularQJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_regular_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_regular_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_regular_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_regular_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_regular_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisZero0036CertifiedArithmetic
