import GeneralCK.Certificates.E8TAxisProd0096GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0096GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0096GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0096GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0096GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0096GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0096GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0096GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0096Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0096CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0096GraphCenterA.qJetBox,
   E8TAxisProd0096GraphCenterB.qJetBox,
   E8TAxisProd0096GraphCenterC.qJetBox,
   E8TAxisProd0096GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0096GraphWholeA.qJetBox,
   E8TAxisProd0096GraphWholeB.qJetBox,
   E8TAxisProd0096GraphWholeC.qJetBox,
   E8TAxisProd0096GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨2457170162974894966214484463279463774918984460, 2457170162974894966214484463279487994613252273⟩
  | 0, 2 => ⟨8835266257919945378210070005389698066751619794, 8835266257919945378210070005389769950179130408⟩
  | 1, 1 => ⟨8988996105873461332555538682686567590609349027, 8988996105873461332555538682686685956967802236⟩
  | 0, 3 => ⟨21508467211945002380085767057186529600519762621, 21508467211945002380085767057186742062596374575⟩
  | 1, 2 => ⟨29936247335335675852931159185674851348269156009, 29936247335335675852931159185675203418897464930⟩
  | 2, 1 => ⟨30393837208221432212113069356595681158827190759, 30393837208221432212113069356596290640335593095⟩
  | 0, 4 => ⟨43650708394708143405095553626485488147418041885, 43650708394708143405095553626486153332886774096⟩
  | 1, 3 => ⟨68376147102689693949516969910013840646660681355, 68376147102689693949516969910014974001478836898⟩
  | 2, 2 => ⟨93402663107430290031225670290389691851936983477, 93402663107430290031225670290391694841003872460⟩
  | 3, 1 => ⟨94645345564679402048111138990606212591082797820, 94645345564679402048111138990609806124195610190⟩
  | 0, 5 => ⟨-782046936580877593198082386064846668365529194598564, 783634301074866667998270999465728726437547552327210⟩
  | 1, 4 => ⟨-1524575388902774906788339626277992265707305461830837, 1526713993556576944821560625237901651958690610519638⟩
  | 2, 3 => ⟨-2974635801580571956855750738187977340314677421414387, 2977478678851771404965927567709872621251143416409621⟩
  | 3, 2 => ⟨-5806487545467811524147420355076331908902322755706846, 5810067389311561496130188883800258244180217987361734⟩
  | 4, 1 => ⟨-11337194377680956361653440115224738684508406118955346, 11340924678919898862531193121377835826335079981581847⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0096Geometry.ds, E8TAxisProd0096Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 1659914239926501600290228037028697633819380834 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0096CertifiedArithmetic
