import GeneralCK.Certificates.E8TAxisFirstCellInverseCoverage
import GeneralCK.Certificates.E8TAxisProd0531Geometry
import GeneralCK.Certificates.E8TAxisProd0531PaddedInputs

/-!
# Endpoint certificates for all eight padded first-cell inverse brackets

Generated by `scripts/e8_taxis_emit_endpoint_witnesses.py`.
All primitive checks, scalar graph identities, and target comparisons
are checked separately. Coverage follows from the intermediate value theorem.
The exact lower cell boundaries are those in `E8TAxisProd0531Geometry`.
-/

namespace GeneralCK.Certificates.E8TAxisProd0531EndpointWitnesses

open Set DyadicInterval E8TAxisStableInterval E8TAxisStableScalar
open E8TAxisFirstCellInverseCoverage E8TAxisProd0531Geometry

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

def precision : ℕ := 160
def endpointLogTwo : DyadicInterval precision := ⟨1013035739299659071135698605846798551586536899314, 1013035739299659071135698605846798551586536899589⟩
def fastLogWitness : FastLogBoxWitness := ⟨0, 128, 0, 128⟩

theorem endpointLogTwo_checked :
    logBoxCheck (ofInt precision 2) endpointLogTwo fastLogWitness = true := by decide +kernel

def centerALowerAlpha : DyadicInterval precision := ⟨4590335763975281399345081579386246932603809519, 4590335763975281399345081579386246932603809519⟩
def centerALowerExp : DyadicInterval precision := ⟨1452349740496526708002027977982130831006559458830, 1452349740496526708002027977982130831006559460879⟩
def centerALowerLog : DyadicInterval precision := ⟨1008452612267868520487407126245153690937839073828, 1008452612267868520487407126245153690937839075123⟩
def centerALowerYBox : DyadicInterval precision := ⟨26489717176622615392441787592982629731263397613, 26489717176622615392441787592982629731263400680⟩
def centerALowerInput : Inputs precision :=
  ⟨centerALowerAlpha, centerALowerExp, centerALowerLog, endpointLogTwo⟩
def centerALowerExpWitness : ExpWitness precision :=
  ⟨1452349740496526708002027977982130831006559458830, scale precision, 1452349740496526708002027977982130831006559460879, scale precision,
    0, 128, 0, 128, ⟨-9180671527950562798690163158772493865207620321, -9180671527950562798690163158772493865207620058⟩, ⟨-9180671527950562798690163158772493865207618259, -9180671527950562798690163158772493865207617996⟩⟩

theorem centerALower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerALowerAlpha) centerALowerExp centerALowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerALowerExp) centerALowerLog fastLogWitness = true := by decide +kernel

theorem centerALower_denominators : DenominatorsPositive centerALowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerALower_yBox_eq : (yBox centerALowerInput).d0 = centerALowerYBox := by decide +kernel

theorem centerALower_contains :
    centerALowerYBox.Contains (Y (lower E8TAxisProd0531PaddedInputs.centerAInput.alpha)) := by
  rw [← centerALower_yBox_eq]
  apply checked_yBox_d0_contains centerALower_primitive_checks.1
    centerALower_primitive_checks.2 endpointLogTwo_checked centerALower_denominators
  exact point_contains precision 4590335763975281399345081579386246932603809519

def centerAUpperAlpha : DyadicInterval precision := ⟨4590335763975281399345081579386246932603940592, 4590335763975281399345081579386246932603940592⟩
def centerAUpperExp : DyadicInterval precision := ⟨1452349740496526708002027977982130831006559198326, 1452349740496526708002027977982130831006559200375⟩
def centerAUpperLog : DyadicInterval precision := ⟨1008452612267868520487407126245153690937838943172, 1008452612267868520487407126245153690937838944461⟩
def centerAUpperYBox : DyadicInterval precision := ⟨26489717176622615392441787592982629731264153998, 26489717176622615392441787592982629731264157062⟩
def centerAUpperInput : Inputs precision :=
  ⟨centerAUpperAlpha, centerAUpperExp, centerAUpperLog, endpointLogTwo⟩
def centerAUpperExpWitness : ExpWitness precision :=
  ⟨1452349740496526708002027977982130831006559198326, scale precision, 1452349740496526708002027977982130831006559200375, scale precision,
    0, 128, 0, 128, ⟨-9180671527950562798690163158772493865207882467, -9180671527950562798690163158772493865207882204⟩, ⟨-9180671527950562798690163158772493865207880405, -9180671527950562798690163158772493865207880142⟩⟩

theorem centerAUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerAUpperAlpha) centerAUpperExp centerAUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerAUpperExp) centerAUpperLog fastLogWitness = true := by decide +kernel

theorem centerAUpper_denominators : DenominatorsPositive centerAUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerAUpper_yBox_eq : (yBox centerAUpperInput).d0 = centerAUpperYBox := by decide +kernel

theorem centerAUpper_contains :
    centerAUpperYBox.Contains (Y (upper E8TAxisProd0531PaddedInputs.centerAInput.alpha)) := by
  rw [← centerAUpper_yBox_eq]
  apply checked_yBox_d0_contains centerAUpper_primitive_checks.1
    centerAUpper_primitive_checks.2 endpointLogTwo_checked centerAUpper_denominators
  exact point_contains precision 4590335763975281399345081579386246932603940592

def centerBLowerAlpha : DyadicInterval precision := ⟨1296507372404864056126547685199520070053088430406, 1296507372404864056126547685199520070053088430406⟩
def centerBLowerExp : DyadicInterval precision := ⟨247895433806592693986732232053616620652358069637, 247895433806592693986732232053616620652358071686⟩
def centerBLowerLog : DyadicInterval precision := ⟨228982657997730178281846609719434850793965729008, 228982657997730178281846609719434850793965731029⟩
def centerBLowerYBox : DyadicInterval precision := ⟨6135109841958130906321905736836821813449419068703, 6135109841958130906321905736836821813449419128100⟩
def centerBLowerInput : Inputs precision :=
  ⟨centerBLowerAlpha, centerBLowerExp, centerBLowerLog, endpointLogTwo⟩
def centerBLowerExpWitness : ExpWitness precision :=
  ⟨247895433806592693986732232053616620652358069637, scale precision, 247895433806592693986732232053616620652358071686, scale precision,
    2, 128, 2, 128,
    ⟨-2593014744809728112253095370399040140106176867525, -2593014744809728112253095370399040140106176866710⟩, ⟨-2593014744809728112253095370399040140106176855445, -2593014744809728112253095370399040140106176854628⟩⟩

theorem centerBLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerBLowerAlpha) centerBLowerExp centerBLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerBLowerExp) centerBLowerLog fastLogWitness = true := by decide +kernel

theorem centerBLower_denominators : DenominatorsPositive centerBLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerBLower_yBox_eq : (yBox centerBLowerInput).d0 = centerBLowerYBox := by decide +kernel

theorem centerBLower_contains :
    centerBLowerYBox.Contains (Y (lower E8TAxisProd0531PaddedInputs.centerBInput.alpha)) := by
  rw [← centerBLower_yBox_eq]
  apply checked_yBox_d0_contains centerBLower_primitive_checks.1
    centerBLower_primitive_checks.2 endpointLogTwo_checked centerBLower_denominators
  exact point_contains precision 1296507372404864056126547685199520070053088430406

def centerBUpperAlpha : DyadicInterval precision := ⟨1296507372404864056126547685199520070053088561479, 1296507372404864056126547685199520070053088561479⟩
def centerBUpperExp : DyadicInterval precision := ⟨247895433806592693986732232053616620652358025172, 247895433806592693986732232053616620652358027221⟩
def centerBUpperLog : DyadicInterval precision := ⟨228982657997730178281846609719434850793965690990, 228982657997730178281846609719434850793965693011⟩
def centerBUpperYBox : DyadicInterval precision := ⟨6135109841958130906321905736836821813449419527535, 6135109841958130906321905736836821813449419586923⟩
def centerBUpperInput : Inputs precision :=
  ⟨centerBUpperAlpha, centerBUpperExp, centerBUpperLog, endpointLogTwo⟩
def centerBUpperExpWitness : ExpWitness precision :=
  ⟨247895433806592693986732232053616620652358025172, scale precision, 247895433806592693986732232053616620652358027221, scale precision,
    2, 128, 2, 128,
    ⟨-2593014744809728112253095370399040140106177129673, -2593014744809728112253095370399040140106177128856⟩, ⟨-2593014744809728112253095370399040140106177117593, -2593014744809728112253095370399040140106177116778⟩⟩

theorem centerBUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerBUpperAlpha) centerBUpperExp centerBUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerBUpperExp) centerBUpperLog fastLogWitness = true := by decide +kernel

theorem centerBUpper_denominators : DenominatorsPositive centerBUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerBUpper_yBox_eq : (yBox centerBUpperInput).d0 = centerBUpperYBox := by decide +kernel

theorem centerBUpper_contains :
    centerBUpperYBox.Contains (Y (upper E8TAxisProd0531PaddedInputs.centerBInput.alpha)) := by
  rw [← centerBUpper_yBox_eq]
  apply checked_yBox_d0_contains centerBUpper_primitive_checks.1
    centerBUpper_primitive_checks.2 endpointLogTwo_checked centerBUpper_denominators
  exact point_contains precision 1296507372404864056126547685199520070053088561479

def centerCLowerAlpha : DyadicInterval precision := ⟨562408817328067198567559886289325588347679447633, 562408817328067198567559886289325588347679447633⟩
def centerCLowerExp : DyadicInterval precision := ⟨676943794321723647138909445402963869340618181515, 676943794321723647138909445402963869340618183564⟩
def centerCLowerLog : DyadicInterval precision := ⟨556269015088472894434144883242305722426517479030, 556269015088472894434144883242305722426517480695⟩
def centerCLowerYBox : DyadicInterval precision := ⟨3080799779567376760857173762214902221590341217211, 3080799779567376760857173762214902221590341237580⟩
def centerCLowerInput : Inputs precision :=
  ⟨centerCLowerAlpha, centerCLowerExp, centerCLowerLog, endpointLogTwo⟩
def centerCLowerExpWitness : ExpWitness precision :=
  ⟨676943794321723647138909445402963869340618181515, scale precision, 676943794321723647138909445402963869340618183564, scale precision,
    1, 128, 1, 128,
    ⟨-1124817634656134397135119772578651176695358897948, -1124817634656134397135119772578651176695358897406⟩, ⟨-1124817634656134397135119772578651176695358893526, -1124817634656134397135119772578651176695358892984⟩⟩

theorem centerCLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerCLowerAlpha) centerCLowerExp centerCLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerCLowerExp) centerCLowerLog fastLogWitness = true := by decide +kernel

theorem centerCLower_denominators : DenominatorsPositive centerCLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerCLower_yBox_eq : (yBox centerCLowerInput).d0 = centerCLowerYBox := by decide +kernel

theorem centerCLower_contains :
    centerCLowerYBox.Contains (Y (lower E8TAxisProd0531PaddedInputs.centerCInput.alpha)) := by
  rw [← centerCLower_yBox_eq]
  apply checked_yBox_d0_contains centerCLower_primitive_checks.1
    centerCLower_primitive_checks.2 endpointLogTwo_checked centerCLower_denominators
  exact point_contains precision 562408817328067198567559886289325588347679447633

def centerCUpperAlpha : DyadicInterval precision := ⟨562408817328067198567559886289325588347679578706, 562408817328067198567559886289325588347679578706⟩
def centerCUpperExp : DyadicInterval precision := ⟨676943794321723647138909445402963869340618060094, 676943794321723647138909445402963869340618062143⟩
def centerCUpperLog : DyadicInterval precision := ⟨556269015088472894434144883242305722426517396044, 556269015088472894434144883242305722426517397709⟩
def centerCUpperYBox : DyadicInterval precision := ⟨3080799779567376760857173762214902221590341867358, 3080799779567376760857173762214902221590341887731⟩
def centerCUpperInput : Inputs precision :=
  ⟨centerCUpperAlpha, centerCUpperExp, centerCUpperLog, endpointLogTwo⟩
def centerCUpperExpWitness : ExpWitness precision :=
  ⟨676943794321723647138909445402963869340618060094, scale precision, 676943794321723647138909445402963869340618062143, scale precision,
    1, 128, 1, 128,
    ⟨-1124817634656134397135119772578651176695359160092, -1124817634656134397135119772578651176695359159552⟩, ⟨-1124817634656134397135119772578651176695359155668, -1124817634656134397135119772578651176695359155128⟩⟩

theorem centerCUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerCUpperAlpha) centerCUpperExp centerCUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerCUpperExp) centerCUpperLog fastLogWitness = true := by decide +kernel

theorem centerCUpper_denominators : DenominatorsPositive centerCUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerCUpper_yBox_eq : (yBox centerCUpperInput).d0 = centerCUpperYBox := by decide +kernel

theorem centerCUpper_contains :
    centerCUpperYBox.Contains (Y (upper E8TAxisProd0531PaddedInputs.centerCInput.alpha)) := by
  rw [← centerCUpper_yBox_eq]
  apply checked_yBox_d0_contains centerCUpper_primitive_checks.1
    centerCUpper_primitive_checks.2 endpointLogTwo_checked centerCUpper_denominators
  exact point_contains precision 562408817328067198567559886289325588347679578706

def centerDLowerAlpha : DyadicInterval precision := ⟨557075069631301290362165038182134082283955492789, 557075069631301290362165038182134082283955492789⟩
def centerDLowerExp : DyadicInterval precision := ⟨681902880895464588128477464036409277405850863658, 681902880895464588128477464036409277405850865707⟩
def centerDLowerLog : DyadicInterval precision := ⟨559654335205987407427227649575573487608400002078, 559654335205987407427227649575573487608400003741⟩
def centerDLowerYBox : DyadicInterval precision := ⟨3054310062390754145464731974621919591859077439164, 3054310062390754145464731974621919591859077459318⟩
def centerDLowerInput : Inputs precision :=
  ⟨centerDLowerAlpha, centerDLowerExp, centerDLowerLog, endpointLogTwo⟩
def centerDLowerExpWitness : ExpWitness precision :=
  ⟨681902880895464588128477464036409277405850863658, scale precision, 681902880895464588128477464036409277405850865707, scale precision,
    1, 128, 1, 128,
    ⟨-1114150139262602580724330076364268164567910988240, -1114150139262602580724330076364268164567910987706⟩, ⟨-1114150139262602580724330076364268164567910983850, -1114150139262602580724330076364268164567910983312⟩⟩

theorem centerDLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerDLowerAlpha) centerDLowerExp centerDLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerDLowerExp) centerDLowerLog fastLogWitness = true := by decide +kernel

theorem centerDLower_denominators : DenominatorsPositive centerDLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerDLower_yBox_eq : (yBox centerDLowerInput).d0 = centerDLowerYBox := by decide +kernel

theorem centerDLower_contains :
    centerDLowerYBox.Contains (Y (lower E8TAxisProd0531PaddedInputs.centerDInput.alpha)) := by
  rw [← centerDLower_yBox_eq]
  apply checked_yBox_d0_contains centerDLower_primitive_checks.1
    centerDLower_primitive_checks.2 endpointLogTwo_checked centerDLower_denominators
  exact point_contains precision 557075069631301290362165038182134082283955492789

def centerDUpperAlpha : DyadicInterval precision := ⟨557075069631301290362165038182134082283955623862, 557075069631301290362165038182134082283955623862⟩
def centerDUpperExp : DyadicInterval precision := ⟨681902880895464588128477464036409277405850741347, 681902880895464588128477464036409277405850743396⟩
def centerDUpperLog : DyadicInterval precision := ⟨559654335205987407427227649575573487608399918676, 559654335205987407427227649575573487608399920343⟩
def centerDUpperYBox : DyadicInterval precision := ⟨3054310062390754145464731974621919591859078090939, 3054310062390754145464731974621919591859078111114⟩
def centerDUpperInput : Inputs precision :=
  ⟨centerDUpperAlpha, centerDUpperExp, centerDUpperLog, endpointLogTwo⟩
def centerDUpperExpWitness : ExpWitness precision :=
  ⟨681902880895464588128477464036409277405850741347, scale precision, 681902880895464588128477464036409277405850743396, scale precision,
    1, 128, 1, 128,
    ⟨-1114150139262602580724330076364268164567911250386, -1114150139262602580724330076364268164567911249850⟩, ⟨-1114150139262602580724330076364268164567911245994, -1114150139262602580724330076364268164567911245458⟩⟩

theorem centerDUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerDUpperAlpha) centerDUpperExp centerDUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerDUpperExp) centerDUpperLog fastLogWitness = true := by decide +kernel

theorem centerDUpper_denominators : DenominatorsPositive centerDUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerDUpper_yBox_eq : (yBox centerDUpperInput).d0 = centerDUpperYBox := by decide +kernel

theorem centerDUpper_contains :
    centerDUpperYBox.Contains (Y (upper E8TAxisProd0531PaddedInputs.centerDInput.alpha)) := by
  rw [← centerDUpper_yBox_eq]
  apply checked_yBox_d0_contains centerDUpper_primitive_checks.1
    centerDUpper_primitive_checks.2 endpointLogTwo_checked centerDUpper_denominators
  exact point_contains precision 557075069631301290362165038182134082283955623862

def wholeALowerAlpha : DyadicInterval precision := ⟨4432047174048269527644776165804031130864610368, 4432047174048269527644776165804031130864610368⟩
def wholeALowerExp : DyadicInterval precision := ⟨1452664369350591901250217311774540049762303959345, 1452664369350591901250217311774540049762303961394⟩
def wholeALowerLog : DyadicInterval precision := ⟨1008610412272733567070593870872814920969193762208, 1008610412272733567070593870872814920969193763499⟩
def wholeALowerYBox : DyadicInterval precision := ⟨25576278653290801068564484572534952843978439780, 25576278653290801068564484572534952843978442841⟩
def wholeALowerInput : Inputs precision :=
  ⟨wholeALowerAlpha, wholeALowerExp, wholeALowerLog, endpointLogTwo⟩
def wholeALowerExpWitness : ExpWitness precision :=
  ⟨1452664369350591901250217311774540049762303959345, scale precision, 1452664369350591901250217311774540049762303961394, scale precision,
    0, 128, 0, 128, ⟨-8864094348096539055289552331608062261729222019, -8864094348096539055289552331608062261729221758⟩, ⟨-8864094348096539055289552331608062261729219957, -8864094348096539055289552331608062261729219696⟩⟩

theorem wholeALower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeALowerAlpha) wholeALowerExp wholeALowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeALowerExp) wholeALowerLog fastLogWitness = true := by decide +kernel

theorem wholeALower_denominators : DenominatorsPositive wholeALowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeALower_yBox_eq : (yBox wholeALowerInput).d0 = wholeALowerYBox := by decide +kernel

theorem wholeALower_contains :
    wholeALowerYBox.Contains (Y (lower E8TAxisProd0531PaddedInputs.wholeAInput.alpha)) := by
  rw [← wholeALower_yBox_eq]
  apply checked_yBox_d0_contains wholeALower_primitive_checks.1
    wholeALower_primitive_checks.2 endpointLogTwo_checked wholeALower_denominators
  exact point_contains precision 4432047174048269527644776165804031130864610368

def wholeAUpperAlpha : DyadicInterval precision := ⟨4748624479255801076876082777124010865681716875, 4748624479255801076876082777124010865681716875⟩
def wholeAUpperExp : DyadicInterval precision := ⟨1452035179538035812075122148102075717554934481868, 1452035179538035812075122148102075717554934483917⟩
def wholeAUpperLog : DyadicInterval precision := ⟨1008294829281404787796718047455216464285448679886, 1008294829281404787796718047455216464285448681177⟩
def wholeAUpperYBox : DyadicInterval precision := ⟨27403155699954429716319090613430306618549111840, 27403155699954429716319090613430306618549114907⟩
def wholeAUpperInput : Inputs precision :=
  ⟨wholeAUpperAlpha, wholeAUpperExp, wholeAUpperLog, endpointLogTwo⟩
def wholeAUpperExpWitness : ExpWitness precision :=
  ⟨1452035179538035812075122148102075717554934481868, scale precision, 1452035179538035812075122148102075717554934483917, scale precision,
    0, 128, 0, 128, ⟨-9497248958511602153752165554248021731363435031, -9497248958511602153752165554248021731363434768⟩, ⟨-9497248958511602153752165554248021731363432969, -9497248958511602153752165554248021731363432706⟩⟩

theorem wholeAUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeAUpperAlpha) wholeAUpperExp wholeAUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeAUpperExp) wholeAUpperLog fastLogWitness = true := by decide +kernel

theorem wholeAUpper_denominators : DenominatorsPositive wholeAUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeAUpper_yBox_eq : (yBox wholeAUpperInput).d0 = wholeAUpperYBox := by decide +kernel

theorem wholeAUpper_contains :
    wholeAUpperYBox.Contains (Y (upper E8TAxisProd0531PaddedInputs.wholeAInput.alpha)) := by
  rw [← wholeAUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeAUpper_primitive_checks.1
    wholeAUpper_primitive_checks.2 endpointLogTwo_checked wholeAUpper_denominators
  exact point_contains precision 4748624479255801076876082777124010865681716875

def wholeBLowerAlpha : DyadicInterval precision := ⟨1281286317673260541933134320761264852245544685145, 1281286317673260541933134320761264852245544685145⟩
def wholeBLowerExp : DyadicInterval precision := ⟨253113082663736822276297681991513347913377554485, 253113082663736822276297681991513347913377556534⟩
def wholeBLowerLog : DyadicInterval precision := ⟨233436853085456590992630848080526443523710362168, 233436853085456590992630848080526443523710364179⟩
def wholeBLowerYBox : DyadicInterval precision := ⟨6081673688343219768375083510140632715543249034309, 6081673688343219768375083510140632715543249092600⟩
def wholeBLowerInput : Inputs precision :=
  ⟨wholeBLowerAlpha, wholeBLowerExp, wholeBLowerLog, endpointLogTwo⟩
def wholeBLowerExpWitness : ExpWitness precision :=
  ⟨253113082663736822276297681991513347913377554485, scale precision, 253113082663736822276297681991513347913377556534, scale precision,
    2, 128, 2, 128,
    ⟨-2562572635346521083866268641522529704491089376877, -2562572635346521083866268641522529704491089376064⟩, ⟨-2562572635346521083866268641522529704491089365045, -2562572635346521083866268641522529704491089364232⟩⟩

theorem wholeBLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeBLowerAlpha) wholeBLowerExp wholeBLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeBLowerExp) wholeBLowerLog fastLogWitness = true := by decide +kernel

theorem wholeBLower_denominators : DenominatorsPositive wholeBLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeBLower_yBox_eq : (yBox wholeBLowerInput).d0 = wholeBLowerYBox := by decide +kernel

theorem wholeBLower_contains :
    wholeBLowerYBox.Contains (Y (lower E8TAxisProd0531PaddedInputs.wholeBInput.alpha)) := by
  rw [← wholeBLower_yBox_eq]
  apply checked_yBox_d0_contains wholeBLower_primitive_checks.1
    wholeBLower_primitive_checks.2 endpointLogTwo_checked wholeBLower_denominators
  exact point_contains precision 1281286317673260541933134320761264852245544685145

def wholeBUpperAlpha : DyadicInterval precision := ⟨1311816315929484659436961567433321599157553028746, 1311816315929484659436961567433321599157553028746⟩
def wholeBUpperExp : DyadicInterval precision := ⟨242756142563984799299377264386521145577843169561, 242756142563984799299377264386521145577843171610⟩
def wholeBUpperLog : DyadicInterval precision := ⟨224582044245990533872398728589104101553664097452, 224582044245990533872398728589104101553664099473⟩
def wholeBUpperYBox : DyadicInterval precision := ⟨6188545995573042044268727963533010911355589559286, 6188545995573042044268727963533010911355589619747⟩
def wholeBUpperInput : Inputs precision :=
  ⟨wholeBUpperAlpha, wholeBUpperExp, wholeBUpperLog, endpointLogTwo⟩
def wholeBUpperExpWitness : ExpWitness precision :=
  ⟨242756142563984799299377264386521145577843169561, scale precision, 242756142563984799299377264386521145577843171610, scale precision,
    2, 128, 2, 128,
    ⟨-2623632631858969318873923134866643198315106064333, -2623632631858969318873923134866643198315106063518⟩, ⟨-2623632631858969318873923134866643198315106051999, -2623632631858969318873923134866643198315106051180⟩⟩

theorem wholeBUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeBUpperAlpha) wholeBUpperExp wholeBUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeBUpperExp) wholeBUpperLog fastLogWitness = true := by decide +kernel

theorem wholeBUpper_denominators : DenominatorsPositive wholeBUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeBUpper_yBox_eq : (yBox wholeBUpperInput).d0 = wholeBUpperYBox := by decide +kernel

theorem wholeBUpper_contains :
    wholeBUpperYBox.Contains (Y (upper E8TAxisProd0531PaddedInputs.wholeBInput.alpha)) := by
  rw [← wholeBUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeBUpper_primitive_checks.1
    wholeBUpper_primitive_checks.2 endpointLogTwo_checked wholeBUpper_denominators
  exact point_contains precision 1311816315929484659436961567433321599157553028746

def wholeCLowerAlpha : DyadicInterval precision := ⟨556937304727438396274038219807161263222909371541, 556937304727438396274038219807161263222909371541⟩
def wholeCLowerExp : DyadicInterval precision := ⟨682031448853554463306711643490469223624807434685, 682031448853554463306711643490469223624807436734⟩
def wholeCLowerLog : DyadicInterval precision := ⟨559741997914732991466360178093726645195902846388, 559741997914732991466360178093726645195902848053⟩
def wholeCLowerYBox : DyadicInterval precision := ⟨3053624983498255284721823997356583834193613720761, 3053624983498255284721823997356583834193613740918⟩
def wholeCLowerInput : Inputs precision :=
  ⟨wholeCLowerAlpha, wholeCLowerExp, wholeCLowerLog, endpointLogTwo⟩
def wholeCLowerExpWitness : ExpWitness precision :=
  ⟨682031448853554463306711643490469223624807434685, scale precision, 682031448853554463306711643490469223624807436734, scale precision,
    1, 128, 1, 128,
    ⟨-1113874609454876792548076439614322526445818745746, -1113874609454876792548076439614322526445818745208⟩, ⟨-1113874609454876792548076439614322526445818741354, -1113874609454876792548076439614322526445818740818⟩⟩

theorem wholeCLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeCLowerAlpha) wholeCLowerExp wholeCLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeCLowerExp) wholeCLowerLog fastLogWitness = true := by decide +kernel

theorem wholeCLower_denominators : DenominatorsPositive wholeCLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeCLower_yBox_eq : (yBox wholeCLowerInput).d0 = wholeCLowerYBox := by decide +kernel

theorem wholeCLower_contains :
    wholeCLowerYBox.Contains (Y (lower E8TAxisProd0531PaddedInputs.wholeCInput.alpha)) := by
  rw [← wholeCLower_yBox_eq]
  apply checked_yBox_d0_contains wholeCLower_primitive_checks.1
    wholeCLower_primitive_checks.2 endpointLogTwo_checked wholeCLower_denominators
  exact point_contains precision 556937304727438396274038219807161263222909371541

def wholeCUpperAlpha : DyadicInterval precision := ⟨567894451010262947723637521760626815702547225497, 567894451010262947723637521760626815702547225497⟩
def wholeCUpperExp : DyadicInterval precision := ⟨671881107849787291930214422714323229366563892288, 671881107849787291930214422714323229366563894337⟩
def wholeCUpperLog : DyadicInterval precision := ⟨552804864506629412855800948393297087847060383560, 552804864506629412855800948393297087847060385231⟩
def wholeCUpperYBox : DyadicInterval precision := ⟨3107974575636498236992523527073220608987069362129, 3107974575636498236992523527073220608987069382725⟩
def wholeCUpperInput : Inputs precision :=
  ⟨wholeCUpperAlpha, wholeCUpperExp, wholeCUpperLog, endpointLogTwo⟩
def wholeCUpperExpWitness : ExpWitness precision :=
  ⟨671881107849787291930214422714323229366563892288, scale precision, 671881107849787291930214422714323229366563894337, scale precision,
    1, 128, 1, 128,
    ⟨-1135788902020525895447275043521253631405094453690, -1135788902020525895447275043521253631405094453146⟩, ⟨-1135788902020525895447275043521253631405094449232, -1135788902020525895447275043521253631405094448690⟩⟩

theorem wholeCUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeCUpperAlpha) wholeCUpperExp wholeCUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeCUpperExp) wholeCUpperLog fastLogWitness = true := by decide +kernel

theorem wholeCUpper_denominators : DenominatorsPositive wholeCUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeCUpper_yBox_eq : (yBox wholeCUpperInput).d0 = wholeCUpperYBox := by decide +kernel

theorem wholeCUpper_contains :
    wholeCUpperYBox.Contains (Y (upper E8TAxisProd0531PaddedInputs.wholeCInput.alpha)) := by
  rw [← wholeCUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeCUpper_primitive_checks.1
    wholeCUpper_primitive_checks.2 endpointLogTwo_checked wholeCUpper_denominators
  exact point_contains precision 567894451010262947723637521760626815702547225497

def wholeDLowerAlpha : DyadicInterval precision := ⟨551800421242914454820810459967297938576086227354, 551800421242914454820810459967297938576086227354⟩
def wholeDLowerExp : DyadicInterval precision := ⟨686842745746340006938348233447115252167520689576, 686842745746340006938348233447115252167520691625⟩
def wholeDLowerLog : DyadicInterval precision := ⟨563018755595924057929845042473976396860205665492, 563018755595924057929845042473976396860205667155⟩
def wholeDLowerYBox : DyadicInterval precision := ⟨3028048704844964483653259512784048881349634900576, 3028048704844964483653259512784048881349634920536⟩
def wholeDLowerInput : Inputs precision :=
  ⟨wholeDLowerAlpha, wholeDLowerExp, wholeDLowerLog, endpointLogTwo⟩
def wholeDLowerExpWitness : ExpWitness precision :=
  ⟨686842745746340006938348233447115252167520689576, scale precision, 686842745746340006938348233447115252167520691625, scale precision,
    1, 128, 1, 128,
    ⟨-1103600842485828909641620919934595877152172457356, -1103600842485828909641620919934595877152172456816⟩, ⟨-1103600842485828909641620919934595877152172452996, -1103600842485828909641620919934595877152172452456⟩⟩

theorem wholeDLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeDLowerAlpha) wholeDLowerExp wholeDLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeDLowerExp) wholeDLowerLog fastLogWitness = true := by decide +kernel

theorem wholeDLower_denominators : DenominatorsPositive wholeDLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeDLower_yBox_eq : (yBox wholeDLowerInput).d0 = wholeDLowerYBox := by decide +kernel

theorem wholeDLower_contains :
    wholeDLowerYBox.Contains (Y (lower E8TAxisProd0531PaddedInputs.wholeDInput.alpha)) := by
  rw [← wholeDLower_yBox_eq]
  apply checked_yBox_d0_contains wholeDLower_primitive_checks.1
    wholeDLower_primitive_checks.2 endpointLogTwo_checked wholeDLower_denominators
  exact point_contains precision 551800421242914454820810459967297938576086227354

def wholeDUpperAlpha : DyadicInterval precision := ⟨562362779591003425345044647758252905789383303694, 562362779591003425345044647758252905789383303694⟩
def wholeDUpperExp : DyadicInterval precision := ⟨676986443527636285719880989929562987720180644468, 676986443527636285719880989929562987720180646517⟩
def wholeDUpperLog : DyadicInterval precision := ⟨556298163020790248856133545839930269777570312566, 556298163020790248856133545839930269777570314237⟩
def wholeDUpperYBox : DyadicInterval precision := ⟨3080571419936543807276204436459790302368520627897, 3080571419936543807276204436459790302368520648283⟩
def wholeDUpperInput : Inputs precision :=
  ⟨wholeDUpperAlpha, wholeDUpperExp, wholeDUpperLog, endpointLogTwo⟩
def wholeDUpperExpWitness : ExpWitness precision :=
  ⟨676986443527636285719880989929562987720180644468, scale precision, 676986443527636285719880989929562987720180646517, scale precision,
    1, 128, 1, 128,
    ⟨-1124725559182006850690089295516505811578766610066, -1124725559182006850690089295516505811578766609528⟩, ⟨-1124725559182006850690089295516505811578766605640, -1124725559182006850690089295516505811578766605104⟩⟩

theorem wholeDUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeDUpperAlpha) wholeDUpperExp wholeDUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeDUpperExp) wholeDUpperLog fastLogWitness = true := by decide +kernel

theorem wholeDUpper_denominators : DenominatorsPositive wholeDUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeDUpper_yBox_eq : (yBox wholeDUpperInput).d0 = wholeDUpperYBox := by decide +kernel

theorem wholeDUpper_contains :
    wholeDUpperYBox.Contains (Y (upper E8TAxisProd0531PaddedInputs.wholeDInput.alpha)) := by
  rw [← wholeDUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeDUpper_primitive_checks.1
    wholeDUpper_primitive_checks.2 endpointLogTwo_checked wholeDUpper_denominators
  exact point_contains precision 562362779591003425345044647758252905789383303694

theorem centerA_covers_slope {s : ℝ} (hs : s ∈ Icc (centerT) (centerT)) :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.centerAInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerALower_contains centerAUpper_contains _ _ hs
  · norm_num [centerALowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerAUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerA_covers :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.centerAInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerT) :=
  centerA_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerB_covers_slope {s : ℝ} (hs : s ∈ Icc (2 * centerS + centerT) (2 * centerS + centerT)) :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.centerBInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerBLower_contains centerBUpper_contains _ _ hs
  · norm_num [centerBLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerBUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerB_covers :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.centerBInput.alpha.Contains a ∧
      0 < a ∧ Y a = (2 * centerS + centerT) :=
  centerB_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerC_covers_slope {s : ℝ} (hs : s ∈ Icc (centerS + centerT) (centerS + centerT)) :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.centerCInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerCLower_contains centerCUpper_contains _ _ hs
  · norm_num [centerCLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerCUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerC_covers :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.centerCInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerS + centerT) :=
  centerC_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerD_covers_slope {s : ℝ} (hs : s ∈ Icc (centerS) (centerS)) :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.centerDInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerDLower_contains centerDUpper_contains _ _ hs
  · norm_num [centerDLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerDUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerD_covers :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.centerDInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerS) :=
  centerD_covers_slope ⟨le_rfl, le_rfl⟩

theorem wholeA_covers_slope {s : ℝ} (hs : s ∈ Icc (tLower) (tUpper)) :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.wholeAInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeALower_contains wholeAUpper_contains _ _ hs
  · norm_num [wholeALowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeAUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeB_covers_slope {s : ℝ} (hs : s ∈ Icc (2 * sLower + tLower) (2 * sUpper + tUpper)) :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.wholeBInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeBLower_contains wholeBUpper_contains _ _ hs
  · norm_num [wholeBLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeBUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeC_covers_slope {s : ℝ} (hs : s ∈ Icc (sLower + tLower) (sUpper + tUpper)) :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.wholeCInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeCLower_contains wholeCUpper_contains _ _ hs
  · norm_num [wholeCLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeCUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeD_covers_slope {s : ℝ} (hs : s ∈ Icc (sLower) (sUpper)) :
    ∃ a : ℝ, E8TAxisProd0531PaddedInputs.wholeDInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeDLower_contains wholeDUpper_contains _ _ hs
  · norm_num [wholeDLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeDUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

#print axioms centerA_covers
#print axioms wholeA_covers_slope
#print axioms wholeB_covers_slope

end GeneralCK.Certificates.E8TAxisProd0531EndpointWitnesses
