import GeneralCK.Certificates.E8TAxisProd0052GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0052GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0052GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0052GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0052GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0052GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0052GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0052GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0052Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0052CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0052GraphCenterA.qJetBox,
   E8TAxisProd0052GraphCenterB.qJetBox,
   E8TAxisProd0052GraphCenterC.qJetBox,
   E8TAxisProd0052GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0052GraphWholeA.qJetBox,
   E8TAxisProd0052GraphWholeB.qJetBox,
   E8TAxisProd0052GraphWholeC.qJetBox,
   E8TAxisProd0052GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨38021963598043239395996665464654001266115, 38021963598043239395996665465811587310914⟩
  | 0, 2 => ⟨646062001194787687361645581990209807518954, 646062001194787687361645581993640917940686⟩
  | 1, 1 => ⟨692847033167325853314755459651296530637465, 692847033167325853314755459655458640093485⟩
  | 0, 3 => ⟨5638292362312161230747753534240966320644069, 5638292362312161230747753534246422388997916⟩
  | 1, 2 => ⟨9642020801053559621386589272217967097607388, 9642020801053559621386589272223999319400315⟩
  | 2, 1 => ⟨10171492301081664982586820504472821671699106, 10171492301081664982586820504480508575787577⟩
  | 0, 4 => ⟨22888350490103975852192724707266276708537842, 22888350490103975852192724707282116304181769⟩
  | 1, 3 => ⟨65352434395417016015219184665332351822506715, 65352434395417016015219184665349908519362200⟩
  | 2, 2 => ⟨109765668038337929261054665710515905653267305, 109765668038337929261054665710538797603512190⟩
  | 3, 1 => ⟨113904694215046775597502532557660393195039027, 113904694215046775597502532557694830052947216⟩
  | 0, 5 => ⟨-344706119380189290927757317629822067104616131302, 344870318995934354884025350291156853981117499169⟩
  | 1, 4 => ⟨-549614184055951750889619177488719420399222587309, 545304376878094803091346745302829621611322966771⟩
  | 2, 3 => ⟨-906434484763206700293347379144544563451364037620, 896579340157275044925651192752678896840516799880⟩
  | 3, 2 => ⟨-1504887438293839198133238562943551037866312480429, 1489827115422751321808581203760072211260707450355⟩
  | 4, 1 => ⟨-2474804025093230700709165283449159584106690803355, 2461083522718709533721411784942907386180397486789⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0052Geometry.ds, E8TAxisProd0052Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 14929109302878665054545007819391438509939 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0052CertifiedArithmetic
