import GeneralCK.Certificates.E8TAxisFirstCellInverseCoverage
import GeneralCK.Certificates.E8TAxisProd0594Geometry
import GeneralCK.Certificates.E8TAxisProd0594PaddedInputs

/-!
# Endpoint certificates for all eight padded first-cell inverse brackets

Generated by `scripts/e8_taxis_emit_endpoint_witnesses.py`.
All primitive checks, scalar graph identities, and target comparisons
are checked separately. Coverage follows from the intermediate value theorem.
The exact lower cell boundaries are those in `E8TAxisProd0594Geometry`.
-/

namespace GeneralCK.Certificates.E8TAxisProd0594EndpointWitnesses

open Set DyadicInterval E8TAxisStableInterval E8TAxisStableScalar
open E8TAxisFirstCellInverseCoverage E8TAxisProd0594Geometry

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

def precision : ℕ := 160
def endpointLogTwo : DyadicInterval precision := ⟨1013035739299659071135698605846798551586536899314, 1013035739299659071135698605846798551586536899589⟩
def fastLogWitness : FastLogBoxWitness := ⟨0, 128, 0, 128⟩

theorem endpointLogTwo_checked :
    logBoxCheck (ofInt precision 2) endpointLogTwo fastLogWitness = true := by decide +kernel

def centerALowerAlpha : DyadicInterval precision := ⟨2057730428207317882804005838293844500353801724, 2057730428207317882804005838293844500353801724⟩
def centerALowerExp : DyadicInterval precision := ⟨1457391965428497307986584889920415114397435640039, 1457391965428497307986584889920415114397435642088⟩
def centerALowerLog : DyadicInterval precision := ⟨1010979457468226488278372104764954115437730941988, 1010979457468226488278372104764954115437730943283⟩
def centerALowerYBox : DyadicInterval precision := ⟨11874700803313586210404939265819799534704072209, 11874700803313586210404939265819799534704075220⟩
def centerALowerInput : Inputs precision :=
  ⟨centerALowerAlpha, centerALowerExp, centerALowerLog, endpointLogTwo⟩
def centerALowerExpWitness : ExpWitness precision :=
  ⟨1457391965428497307986584889920415114397435640039, scale precision, 1457391965428497307986584889920415114397435642088, scale precision,
    0, 128, 0, 128, ⟨-4115460856414635765608011676587689000707604731, -4115460856414635765608011676587689000707604468⟩, ⟨-4115460856414635765608011676587689000707602675, -4115460856414635765608011676587689000707602412⟩⟩

theorem centerALower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerALowerAlpha) centerALowerExp centerALowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerALowerExp) centerALowerLog fastLogWitness = true := by decide +kernel

theorem centerALower_denominators : DenominatorsPositive centerALowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerALower_yBox_eq : (yBox centerALowerInput).d0 = centerALowerYBox := by decide +kernel

theorem centerALower_contains :
    centerALowerYBox.Contains (Y (lower E8TAxisProd0594PaddedInputs.centerAInput.alpha)) := by
  rw [← centerALower_yBox_eq]
  apply checked_yBox_d0_contains centerALower_primitive_checks.1
    centerALower_primitive_checks.2 endpointLogTwo_checked centerALower_denominators
  exact point_contains precision 2057730428207317882804005838293844500353801724

def centerAUpperAlpha : DyadicInterval precision := ⟨2057730428207317882804005838293844500353932797, 2057730428207317882804005838293844500353932797⟩
def centerAUpperExp : DyadicInterval precision := ⟨1457391965428497307986584889920415114397435378631, 1457391965428497307986584889920415114397435380680⟩
def centerAUpperLog : DyadicInterval precision := ⟨1010979457468226488278372104764954115437730811098, 1010979457468226488278372104764954115437730812393⟩
def centerAUpperYBox : DyadicInterval precision := ⟨11874700803313586210404939265819799534704828600, 11874700803313586210404939265819799534704831611⟩
def centerAUpperInput : Inputs precision :=
  ⟨centerAUpperAlpha, centerAUpperExp, centerAUpperLog, endpointLogTwo⟩
def centerAUpperExpWitness : ExpWitness precision :=
  ⟨1457391965428497307986584889920415114397435378631, scale precision, 1457391965428497307986584889920415114397435380680, scale precision,
    0, 128, 0, 128, ⟨-4115460856414635765608011676587689000707866875, -4115460856414635765608011676587689000707866612⟩, ⟨-4115460856414635765608011676587689000707864821, -4115460856414635765608011676587689000707864558⟩⟩

theorem centerAUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerAUpperAlpha) centerAUpperExp centerAUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerAUpperExp) centerAUpperLog fastLogWitness = true := by decide +kernel

theorem centerAUpper_denominators : DenominatorsPositive centerAUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerAUpper_yBox_eq : (yBox centerAUpperInput).d0 = centerAUpperYBox := by decide +kernel

theorem centerAUpper_contains :
    centerAUpperYBox.Contains (Y (upper E8TAxisProd0594PaddedInputs.centerAInput.alpha)) := by
  rw [← centerAUpper_yBox_eq]
  apply checked_yBox_d0_contains centerAUpper_primitive_checks.1
    centerAUpper_primitive_checks.2 endpointLogTwo_checked centerAUpper_denominators
  exact point_contains precision 2057730428207317882804005838293844500353932797

def centerBLowerAlpha : DyadicInterval precision := ⟨1575146361186211366160844951567876050727133310435, 1575146361186211366160844951567876050727133310435⟩
def centerBLowerExp : DyadicInterval precision := ⟨169305022312753157303339815619428744354628928936, 169305022312753157303339815619428744354628930985⟩
def centerBLowerLog : DyadicInterval precision := ⟨160195705619659895901484474568121441987086013510, 160195705619659895901484474568121441987086015613⟩
def centerBLowerYBox : DyadicInterval precision := ⟨7065903697233249702352877514673004561592791115053, 7065903697233249702352877514673004561592791197554⟩
def centerBLowerInput : Inputs precision :=
  ⟨centerBLowerAlpha, centerBLowerExp, centerBLowerLog, endpointLogTwo⟩
def centerBLowerExpWitness : ExpWitness precision :=
  ⟨169305022312753157303339815619428744354628928936, scale precision, 169305022312753157303339815619428744354628930985, scale precision,
    3, 128, 3, 128,
    ⟨-3150292722372422732321689903135752101454266630624, -3150292722372422732321689903135752101454266629528⟩, ⟨-3150292722372422732321689903135752101454266612936, -3150292722372422732321689903135752101454266611842⟩⟩

theorem centerBLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerBLowerAlpha) centerBLowerExp centerBLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerBLowerExp) centerBLowerLog fastLogWitness = true := by decide +kernel

theorem centerBLower_denominators : DenominatorsPositive centerBLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerBLower_yBox_eq : (yBox centerBLowerInput).d0 = centerBLowerYBox := by decide +kernel

theorem centerBLower_contains :
    centerBLowerYBox.Contains (Y (lower E8TAxisProd0594PaddedInputs.centerBInput.alpha)) := by
  rw [← centerBLower_yBox_eq]
  apply checked_yBox_d0_contains centerBLower_primitive_checks.1
    centerBLower_primitive_checks.2 endpointLogTwo_checked centerBLower_denominators
  exact point_contains precision 1575146361186211366160844951567876050727133310435

def centerBUpperAlpha : DyadicInterval precision := ⟨1575146361186211366160844951567876050727133441508, 1575146361186211366160844951567876050727133441508⟩
def centerBUpperExp : DyadicInterval precision := ⟨169305022312753157303339815619428744354628898568, 169305022312753157303339815619428744354628900617⟩
def centerBUpperLog : DyadicInterval precision := ⟨160195705619659895901484474568121441987085986294, 160195705619659895901484474568121441987085988397⟩
def centerBUpperYBox : DyadicInterval precision := ⟨7065903697233249702352877514673004561592791534848, 7065903697233249702352877514673004561592791617353⟩
def centerBUpperInput : Inputs precision :=
  ⟨centerBUpperAlpha, centerBUpperExp, centerBUpperLog, endpointLogTwo⟩
def centerBUpperExpWitness : ExpWitness precision :=
  ⟨169305022312753157303339815619428744354628898568, scale precision, 169305022312753157303339815619428744354628900617, scale precision,
    3, 128, 3, 128,
    ⟨-3150292722372422732321689903135752101454266892770, -3150292722372422732321689903135752101454266891678⟩, ⟨-3150292722372422732321689903135752101454266875082, -3150292722372422732321689903135752101454266873990⟩⟩

theorem centerBUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerBUpperAlpha) centerBUpperExp centerBUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerBUpperExp) centerBUpperLog fastLogWitness = true := by decide +kernel

theorem centerBUpper_denominators : DenominatorsPositive centerBUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerBUpper_yBox_eq : (yBox centerBUpperInput).d0 = centerBUpperYBox := by decide +kernel

theorem centerBUpper_contains :
    centerBUpperYBox.Contains (Y (upper E8TAxisProd0594PaddedInputs.centerBInput.alpha)) := by
  rw [← centerBUpper_yBox_eq]
  apply checked_yBox_d0_contains centerBUpper_primitive_checks.1
    centerBUpper_primitive_checks.2 endpointLogTwo_checked centerBUpper_denominators
  exact point_contains precision 1575146361186211366160844951567876050727133441508

def centerCLowerAlpha : DyadicInterval precision := ⟨656878516469306261116746328428018274820981856803, 656878516469306261116746328428018274820981856803⟩
def centerCLowerExp : DyadicInterval precision := ⟨594850828333114487958442239933833417535470935706, 594850828333114487958442239933833417535470937755⟩
def centerCLowerLog : DyadicInterval precision := ⟨499057999126726522710694398619088641070760203594, 499057999126726522710694398619088641070760205319⟩
def centerCLowerYBox : DyadicInterval precision := ⟨3538889199018281644281641226969412180563747586281, 3538889199018281644281641226969412180563747610554⟩
def centerCLowerInput : Inputs precision :=
  ⟨centerCLowerAlpha, centerCLowerExp, centerCLowerLog, endpointLogTwo⟩
def centerCLowerExpWitness : ExpWitness precision :=
  ⟨594850828333114487958442239933833417535470935706, scale precision, 594850828333114487958442239933833417535470937755, scale precision,
    1, 128, 1, 128,
    ⟨-1313757032938612522233492656856036549641963716580, -1313757032938612522233492656856036549641963716038⟩, ⟨-1313757032938612522233492656856036549641963711546, -1313757032938612522233492656856036549641963711002⟩⟩

theorem centerCLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerCLowerAlpha) centerCLowerExp centerCLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerCLowerExp) centerCLowerLog fastLogWitness = true := by decide +kernel

theorem centerCLower_denominators : DenominatorsPositive centerCLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerCLower_yBox_eq : (yBox centerCLowerInput).d0 = centerCLowerYBox := by decide +kernel

theorem centerCLower_contains :
    centerCLowerYBox.Contains (Y (lower E8TAxisProd0594PaddedInputs.centerCInput.alpha)) := by
  rw [← centerCLower_yBox_eq]
  apply checked_yBox_d0_contains centerCLower_primitive_checks.1
    centerCLower_primitive_checks.2 endpointLogTwo_checked centerCLower_denominators
  exact point_contains precision 656878516469306261116746328428018274820981856803

def centerCUpperAlpha : DyadicInterval precision := ⟨656878516469306261116746328428018274820981987876, 656878516469306261116746328428018274820981987876⟩
def centerCUpperExp : DyadicInterval precision := ⟨594850828333114487958442239933833417535470829009, 594850828333114487958442239933833417535470831058⟩
def centerCUpperLog : DyadicInterval precision := ⟨499057999126726522710694398619088641070760127760, 499057999126726522710694398619088641070760129483⟩
def centerCUpperYBox : DyadicInterval precision := ⟨3538889199018281644281641226969412180563748207219, 3538889199018281644281641226969412180563748231490⟩
def centerCUpperInput : Inputs precision :=
  ⟨centerCUpperAlpha, centerCUpperExp, centerCUpperLog, endpointLogTwo⟩
def centerCUpperExpWitness : ExpWitness precision :=
  ⟨594850828333114487958442239933833417535470829009, scale precision, 594850828333114487958442239933833417535470831058, scale precision,
    1, 128, 1, 128,
    ⟨-1313757032938612522233492656856036549641963978726, -1313757032938612522233492656856036549641963978182⟩, ⟨-1313757032938612522233492656856036549641963973692, -1313757032938612522233492656856036549641963973150⟩⟩

theorem centerCUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerCUpperAlpha) centerCUpperExp centerCUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerCUpperExp) centerCUpperLog fastLogWitness = true := by decide +kernel

theorem centerCUpper_denominators : DenominatorsPositive centerCUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerCUpper_yBox_eq : (yBox centerCUpperInput).d0 = centerCUpperYBox := by decide +kernel

theorem centerCUpper_contains :
    centerCUpperYBox.Contains (Y (upper E8TAxisProd0594PaddedInputs.centerCInput.alpha)) := by
  rw [← centerCUpper_yBox_eq]
  apply checked_yBox_d0_contains centerCUpper_primitive_checks.1
    centerCUpper_primitive_checks.2 endpointLogTwo_checked centerCUpper_denominators
  exact point_contains precision 656878516469306261116746328428018274820981987876

def centerDLowerAlpha : DyadicInterval precision := ⟨654373479606638252589496685135113086385905379786, 654373479606638252589496685135113086385905379786⟩
def centerDLowerExp : DyadicInterval precision := ⟨596893494903452163994038347155718253471565274756, 596893494903452163994038347155718253471565276805⟩
def centerDLowerLog : DyadicInterval precision := ⟨500509053273440340443871498920685506325175058192, 500509053273440340443871498920685506325175059915⟩
def centerDLowerYBox : DyadicInterval precision := ⟨3527014498214968058071236287703592381029043134033, 3527014498214968058071236287703592381029043158200⟩
def centerDLowerInput : Inputs precision :=
  ⟨centerDLowerAlpha, centerDLowerExp, centerDLowerLog, endpointLogTwo⟩
def centerDLowerExpWitness : ExpWitness precision :=
  ⟨596893494903452163994038347155718253471565274756, scale precision, 596893494903452163994038347155718253471565276805, scale precision,
    1, 128, 1, 128,
    ⟨-1308746959213276505178993370270226172771810762540, -1308746959213276505178993370270226172771810762002⟩, ⟨-1308746959213276505178993370270226172771810757524, -1308746959213276505178993370270226172771810756986⟩⟩

theorem centerDLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerDLowerAlpha) centerDLowerExp centerDLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerDLowerExp) centerDLowerLog fastLogWitness = true := by decide +kernel

theorem centerDLower_denominators : DenominatorsPositive centerDLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerDLower_yBox_eq : (yBox centerDLowerInput).d0 = centerDLowerYBox := by decide +kernel

theorem centerDLower_contains :
    centerDLowerYBox.Contains (Y (lower E8TAxisProd0594PaddedInputs.centerDInput.alpha)) := by
  rw [← centerDLower_yBox_eq]
  apply checked_yBox_d0_contains centerDLower_primitive_checks.1
    centerDLower_primitive_checks.2 endpointLogTwo_checked centerDLower_denominators
  exact point_contains precision 654373479606638252589496685135113086385905379786

def centerDUpperAlpha : DyadicInterval precision := ⟨654373479606638252589496685135113086385905510859, 654373479606638252589496685135113086385905510859⟩
def centerDUpperExp : DyadicInterval precision := ⟨596893494903452163994038347155718253471565167693, 596893494903452163994038347155718253471565169742⟩
def centerDUpperLog : DyadicInterval precision := ⟨500509053273440340443871498920685506325174982174, 500509053273440340443871498920685506325174983901⟩
def centerDUpperYBox : DyadicInterval precision := ⟨3527014498214968058071236287703592381029043755745, 3527014498214968058071236287703592381029043779921⟩
def centerDUpperInput : Inputs precision :=
  ⟨centerDUpperAlpha, centerDUpperExp, centerDUpperLog, endpointLogTwo⟩
def centerDUpperExpWitness : ExpWitness precision :=
  ⟨596893494903452163994038347155718253471565167693, scale precision, 596893494903452163994038347155718253471565169742, scale precision,
    1, 128, 1, 128,
    ⟨-1308746959213276505178993370270226172771811024686, -1308746959213276505178993370270226172771811024146⟩, ⟨-1308746959213276505178993370270226172771811019668, -1308746959213276505178993370270226172771811019130⟩⟩

theorem centerDUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerDUpperAlpha) centerDUpperExp centerDUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerDUpperExp) centerDUpperLog fastLogWitness = true := by decide +kernel

theorem centerDUpper_denominators : DenominatorsPositive centerDUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerDUpper_yBox_eq : (yBox centerDUpperInput).d0 = centerDUpperYBox := by decide +kernel

theorem centerDUpper_contains :
    centerDUpperYBox.Contains (Y (upper E8TAxisProd0594PaddedInputs.centerDInput.alpha)) := by
  rw [← centerDUpper_yBox_eq]
  apply checked_yBox_d0_contains centerDUpper_primitive_checks.1
    centerDUpper_primitive_checks.2 endpointLogTwo_checked centerDUpper_denominators
  exact point_contains precision 654373479606638252589496685135113086385905510859

def wholeALowerAlpha : DyadicInterval precision := ⟨1899443256066344012630337314537754309230211955, 1899443256066344012630337314537754309230211955⟩
def wholeALowerExp : DyadicInterval precision := ⟨1457707683773513925477741956702213445579665376973, 1457707683773513925477741956702213445579665379022⟩
def wholeALowerLog : DyadicInterval precision := ⟨1011137530350683182654731711817158198659058131914, 1011137530350683182654731711817158198659058133213⟩
def wholeALowerYBox : DyadicInterval precision := ⟨10961262279981771886527636245372122647419114373, 10961262279981771886527636245372122647419117378⟩
def wholeALowerInput : Inputs precision :=
  ⟨wholeALowerAlpha, wholeALowerExp, wholeALowerLog, endpointLogTwo⟩
def wholeALowerExpWitness : ExpWitness precision :=
  ⟨1457707683773513925477741956702213445579665376973, scale precision, 1457707683773513925477741956702213445579665379022, scale precision,
    0, 128, 0, 128, ⟨-3798886512132688025260674629075508618460425191, -3798886512132688025260674629075508618460424928⟩, ⟨-3798886512132688025260674629075508618460423137, -3798886512132688025260674629075508618460422874⟩⟩

theorem wholeALower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeALowerAlpha) wholeALowerExp wholeALowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeALowerExp) wholeALowerLog fastLogWitness = true := by decide +kernel

theorem wholeALower_denominators : DenominatorsPositive wholeALowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeALower_yBox_eq : (yBox wholeALowerInput).d0 = wholeALowerYBox := by decide +kernel

theorem wholeALower_contains :
    wholeALowerYBox.Contains (Y (lower E8TAxisProd0594PaddedInputs.wholeAInput.alpha)) := by
  rw [← wholeALower_yBox_eq]
  apply checked_yBox_d0_contains wholeALower_primitive_checks.1
    wholeALower_primitive_checks.2 endpointLogTwo_checked wholeALower_denominators
  exact point_contains precision 1899443256066344012630337314537754309230211955

def wholeAUpperAlpha : DyadicInterval precision := ⟨2216017656540843594568486214625237657013019781, 2216017656540843594568486214625237657013019781⟩
def wholeAUpperExp : DyadicInterval precision := ⟨1457076315351450948047082186788007226070285309563, 1457076315351450948047082186788007226070285311612⟩
def wholeAUpperLog : DyadicInterval precision := ⟨1010821401672838003372446069258059722889029530022, 1010821401672838003372446069258059722889029531325⟩
def wholeAUpperYBox : DyadicInterval precision := ⟨12788139326645400534282242286267476421989786439, 12788139326645400534282242286267476421989789456⟩
def wholeAUpperInput : Inputs precision :=
  ⟨wholeAUpperAlpha, wholeAUpperExp, wholeAUpperLog, endpointLogTwo⟩
def wholeAUpperExpWitness : ExpWitness precision :=
  ⟨1457076315351450948047082186788007226070285309563, scale precision, 1457076315351450948047082186788007226070285311612, scale precision,
    0, 128, 0, 128, ⟨-4432035313081687189136972429250475314026040839, -4432035313081687189136972429250475314026040580⟩, ⟨-4432035313081687189136972429250475314026038785, -4432035313081687189136972429250475314026038526⟩⟩

theorem wholeAUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeAUpperAlpha) wholeAUpperExp wholeAUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeAUpperExp) wholeAUpperLog fastLogWitness = true := by decide +kernel

theorem wholeAUpper_denominators : DenominatorsPositive wholeAUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeAUpper_yBox_eq : (yBox wholeAUpperInput).d0 = wholeAUpperYBox := by decide +kernel

theorem wholeAUpper_contains :
    wholeAUpperYBox.Contains (Y (upper E8TAxisProd0594PaddedInputs.wholeAInput.alpha)) := by
  rw [← wholeAUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeAUpper_primitive_checks.1
    wholeAUpper_primitive_checks.2 endpointLogTwo_checked wholeAUpper_denominators
  exact point_contains precision 2216017656540843594568486214625237657013019781

def wholeBLowerAlpha : DyadicInterval precision := ⟨1558498752655911414479039696555119969280556304024, 1558498752655911414479039696555119969280556304024⟩
def wholeBLowerExp : DyadicInterval precision := ⟨173206316670390555870059482055290595367699335644, 173206316670390555870059482055290595367699337693⟩
def wholeBLowerLog : DyadicInterval precision := ⟨163687805015123821012257875634955130756255773674, 163687805015123821012257875634955130756255775771⟩
def wholeBLowerYBox : DyadicInterval precision := ⟨7012467543618338564406055287976815463686621081296, 7012467543618338564406055287976815463686621162205⟩
def wholeBLowerInput : Inputs precision :=
  ⟨wholeBLowerAlpha, wholeBLowerExp, wholeBLowerLog, endpointLogTwo⟩
def wholeBLowerExpWitness : ExpWitness precision :=
  ⟨173206316670390555870059482055290595367699335644, scale precision, 173206316670390555870059482055290595367699337693, scale precision,
    3, 128, 3, 128,
    ⟨-3116997505311822828958079393110239938561112617612, -3116997505311822828958079393110239938561112616522⟩, ⟨-3116997505311822828958079393110239938561112600322, -3116997505311822828958079393110239938561112599230⟩⟩

theorem wholeBLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeBLowerAlpha) wholeBLowerExp wholeBLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeBLowerExp) wholeBLowerLog fastLogWitness = true := by decide +kernel

theorem wholeBLower_denominators : DenominatorsPositive wholeBLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeBLower_yBox_eq : (yBox wholeBLowerInput).d0 = wholeBLowerYBox := by decide +kernel

theorem wholeBLower_contains :
    wholeBLowerYBox.Contains (Y (lower E8TAxisProd0594PaddedInputs.wholeBInput.alpha)) := by
  rw [← wholeBLower_yBox_eq]
  apply checked_yBox_d0_contains wholeBLower_primitive_checks.1
    wholeBLower_primitive_checks.2 endpointLogTwo_checked wholeBLower_denominators
  exact point_contains precision 1558498752655911414479039696555119969280556304024

def wholeBUpperAlpha : DyadicInterval precision := ⟨1591867000330174148021782611381705423145895837922, 1591867000330174148021782611381705423145895837922⟩
def wholeBUpperExp : DyadicInterval precision := ⟨165475062339919478462078684400071847525619711356, 165475062339919478462078684400071847525619713405⟩
def wholeBUpperLog : DyadicInterval precision := ⟨156759322820295063833163021737420000888249316864, 156759322820295063833163021737420000888249318973⟩
def wholeBUpperYBox : DyadicInterval precision := ⟨7119339850848160840299699741369193659498961566709, 7119339850848160840299699741369193659498961650853⟩
def wholeBUpperInput : Inputs precision :=
  ⟨wholeBUpperAlpha, wholeBUpperExp, wholeBUpperLog, endpointLogTwo⟩
def wholeBUpperExpWitness : ExpWitness precision :=
  ⟨165475062339919478462078684400071847525619711356, scale precision, 165475062339919478462078684400071847525619713405, scale precision,
    3, 128, 3, 128,
    ⟨-3183734000660348296043565222763410846291791685800, -3183734000660348296043565222763410846291791684712⟩, ⟨-3183734000660348296043565222763410846291791667702, -3183734000660348296043565222763410846291791666616⟩⟩

theorem wholeBUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeBUpperAlpha) wholeBUpperExp wholeBUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeBUpperExp) wholeBUpperLog fastLogWitness = true := by decide +kernel

theorem wholeBUpper_denominators : DenominatorsPositive wholeBUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeBUpper_yBox_eq : (yBox wholeBUpperInput).d0 = wholeBUpperYBox := by decide +kernel

theorem wholeBUpper_contains :
    wholeBUpperYBox.Contains (Y (upper E8TAxisProd0594PaddedInputs.wholeBInput.alpha)) := by
  rw [← wholeBUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeBUpper_primitive_checks.1
    wholeBUpper_primitive_checks.2 endpointLogTwo_checked wholeBUpper_denominators
  exact point_contains precision 1591867000330174148021782611381705423145895837922

def wholeCLowerAlpha : DyadicInterval precision := ⟨651150448708457975201240894662653348543109814458, 651150448708457975201240894662653348543109814458⟩
def wholeCLowerExp : DyadicInterval precision := ⟨599531952387429235098446449878248959606622076882, 599531952387429235098446449878248959606622078931⟩
def wholeCLowerLog : DyadicInterval precision := ⟨502381211147956781273011703584038216417249154210, 502381211147956781273011703584038216417249155935⟩
def wholeCLowerYBox : DyadicInterval precision := ⟨3511714402949160168146291462111093793167020089787, 3511714402949160168146291462111093793167020113832⟩
def wholeCLowerInput : Inputs precision :=
  ⟨wholeCLowerAlpha, wholeCLowerExp, wholeCLowerLog, endpointLogTwo⟩
def wholeCLowerExpWitness : ExpWitness precision :=
  ⟨599531952387429235098446449878248959606622076882, scale precision, 599531952387429235098446449878248959606622078931, scale precision,
    1, 128, 1, 128,
    ⟨-1302300897416915950402481789325306697086219631870, -1302300897416915950402481789325306697086219631332⟩, ⟨-1302300897416915950402481789325306697086219626876, -1302300897416915950402481789325306697086219626336⟩⟩

theorem wholeCLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeCLowerAlpha) wholeCLowerExp wholeCLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeCLowerExp) wholeCLowerLog fastLogWitness = true := by decide +kernel

theorem wholeCLower_denominators : DenominatorsPositive wholeCLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeCLower_yBox_eq : (yBox wholeCLowerInput).d0 = wholeCLowerYBox := by decide +kernel

theorem wholeCLower_contains :
    wholeCLowerYBox.Contains (Y (lower E8TAxisProd0594PaddedInputs.wholeCInput.alpha)) := by
  rw [← wholeCLower_yBox_eq]
  apply checked_yBox_d0_contains wholeCLower_primitive_checks.1
    wholeCLower_primitive_checks.2 endpointLogTwo_checked wholeCLower_denominators
  exact point_contains precision 651150448708457975201240894662653348543109814458

def wholeCUpperAlpha : DyadicInterval precision := ⟨662623035398286831751652389035954589091240261865, 662623035398286831751652389035954589091240261865⟩
def wholeCUpperExp : DyadicInterval precision := ⟨590192967346016485656449927180617539725162351467, 590192967346016485656449927180617539725162353516⟩
def wholeCUpperLog : DyadicInterval precision := ⟨495743784727647238417256752005641846583279252194, 495743784727647238417256752005641846583279253917⟩
def wholeCUpperYBox : DyadicInterval precision := ⟨3566063995087403120416990991827730567960475701935, 3566063995087403120416990991827730567960475726444⟩
def wholeCUpperInput : Inputs precision :=
  ⟨wholeCUpperAlpha, wholeCUpperExp, wholeCUpperLog, endpointLogTwo⟩
def wholeCUpperExpWitness : ExpWitness precision :=
  ⟨590192967346016485656449927180617539725162351467, scale precision, 590192967346016485656449927180617539725162353516, scale precision,
    1, 128, 1, 128,
    ⟨-1325246070796573663503304778071909178182480526732, -1325246070796573663503304778071909178182480526188⟩, ⟨-1325246070796573663503304778071909178182480521660, -1325246070796573663503304778071909178182480521116⟩⟩

theorem wholeCUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeCUpperAlpha) wholeCUpperExp wholeCUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeCUpperExp) wholeCUpperLog fastLogWitness = true := by decide +kernel

theorem wholeCUpper_denominators : DenominatorsPositive wholeCUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeCUpper_yBox_eq : (yBox wholeCUpperInput).d0 = wholeCUpperYBox := by decide +kernel

theorem wholeCUpper_contains :
    wholeCUpperYBox.Contains (Y (upper E8TAxisProd0594PaddedInputs.wholeCInput.alpha)) := by
  rw [← wholeCUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeCUpper_primitive_checks.1
    wholeCUpper_primitive_checks.2 endpointLogTwo_checked wholeCUpper_denominators
  exact point_contains precision 662623035398286831751652389035954589091240261865

def wholeDLowerAlpha : DyadicInterval precision := ⟨648844592727412176647428020776866274458569841672, 648844592727412176647428020776866274458569841672⟩
def wholeDLowerExp : DyadicInterval precision := ⟨601426740197304508434017275821189106629636489102, 601426740197304508434017275821189106629636491151⟩
def wholeDLowerLog : DyadicInterval precision := ⟨503724208829984298099852655433700220931323128704, 503724208829984298099852655433700220931323130423⟩
def wholeDLowerYBox : DyadicInterval precision := ⟨3500753140669178396259763825865721670519600595411, 3500753140669178396259763825865721670519600619345⟩
def wholeDLowerInput : Inputs precision :=
  ⟨wholeDLowerAlpha, wholeDLowerExp, wholeDLowerLog, endpointLogTwo⟩
def wholeDLowerExpWitness : ExpWitness precision :=
  ⟨601426740197304508434017275821189106629636489102, scale precision, 601426740197304508434017275821189106629636491151, scale precision,
    1, 128, 1, 128,
    ⟨-1297689185454824353294856041553732548917139686294, -1297689185454824353294856041553732548917139685756⟩, ⟨-1297689185454824353294856041553732548917139681316, -1297689185454824353294856041553732548917139680776⟩⟩

theorem wholeDLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeDLowerAlpha) wholeDLowerExp wholeDLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeDLowerExp) wholeDLowerLog fastLogWitness = true := by decide +kernel

theorem wholeDLower_denominators : DenominatorsPositive wholeDLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeDLower_yBox_eq : (yBox wholeDLowerInput).d0 = wholeDLowerYBox := by decide +kernel

theorem wholeDLower_contains :
    wholeDLowerYBox.Contains (Y (lower E8TAxisProd0594PaddedInputs.wholeDInput.alpha)) := by
  rw [← wholeDLower_yBox_eq]
  apply checked_yBox_d0_contains wholeDLower_primitive_checks.1
    wholeDLower_primitive_checks.2 endpointLogTwo_checked wholeDLower_denominators
  exact point_contains precision 648844592727412176647428020776866274458569841672

def wholeDUpperAlpha : DyadicInterval precision := ⟨659917674403335303398947154306570012946022093104, 659917674403335303398947154306570012946022093104⟩
def wholeDUpperExp : DyadicInterval precision := ⟨592382009410612930615839145836493982194246398537, 592382009410612930615839145836493982194246400586⟩
def wholeDUpperLog : DyadicInterval precision := ⟨497302293015079090720897450218278678648265818886, 497302293015079090720897450218278678648265820611⟩
def wholeDUpperYBox : DyadicInterval precision := ⟨3553275855760757719882708749541463091538486292654, 3553275855760757719882708749541463091538486317055⟩
def wholeDUpperInput : Inputs precision :=
  ⟨wholeDUpperAlpha, wholeDUpperExp, wholeDUpperLog, endpointLogTwo⟩
def wholeDUpperExpWitness : ExpWitness precision :=
  ⟨592382009410612930615839145836493982194246398537, scale precision, 592382009410612930615839145836493982194246400586, scale precision,
    1, 128, 1, 128,
    ⟨-1319835348806670606797894308613140025892044189202, -1319835348806670606797894308613140025892044188660⟩, ⟨-1319835348806670606797894308613140025892044184144, -1319835348806670606797894308613140025892044183606⟩⟩

theorem wholeDUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeDUpperAlpha) wholeDUpperExp wholeDUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeDUpperExp) wholeDUpperLog fastLogWitness = true := by decide +kernel

theorem wholeDUpper_denominators : DenominatorsPositive wholeDUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeDUpper_yBox_eq : (yBox wholeDUpperInput).d0 = wholeDUpperYBox := by decide +kernel

theorem wholeDUpper_contains :
    wholeDUpperYBox.Contains (Y (upper E8TAxisProd0594PaddedInputs.wholeDInput.alpha)) := by
  rw [← wholeDUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeDUpper_primitive_checks.1
    wholeDUpper_primitive_checks.2 endpointLogTwo_checked wholeDUpper_denominators
  exact point_contains precision 659917674403335303398947154306570012946022093104

theorem centerA_covers_slope {s : ℝ} (hs : s ∈ Icc (centerT) (centerT)) :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.centerAInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerALower_contains centerAUpper_contains _ _ hs
  · norm_num [centerALowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerAUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerA_covers :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.centerAInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerT) :=
  centerA_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerB_covers_slope {s : ℝ} (hs : s ∈ Icc (2 * centerS + centerT) (2 * centerS + centerT)) :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.centerBInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerBLower_contains centerBUpper_contains _ _ hs
  · norm_num [centerBLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerBUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerB_covers :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.centerBInput.alpha.Contains a ∧
      0 < a ∧ Y a = (2 * centerS + centerT) :=
  centerB_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerC_covers_slope {s : ℝ} (hs : s ∈ Icc (centerS + centerT) (centerS + centerT)) :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.centerCInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerCLower_contains centerCUpper_contains _ _ hs
  · norm_num [centerCLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerCUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerC_covers :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.centerCInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerS + centerT) :=
  centerC_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerD_covers_slope {s : ℝ} (hs : s ∈ Icc (centerS) (centerS)) :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.centerDInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerDLower_contains centerDUpper_contains _ _ hs
  · norm_num [centerDLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerDUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerD_covers :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.centerDInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerS) :=
  centerD_covers_slope ⟨le_rfl, le_rfl⟩

theorem wholeA_covers_slope {s : ℝ} (hs : s ∈ Icc (tLower) (tUpper)) :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.wholeAInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeALower_contains wholeAUpper_contains _ _ hs
  · norm_num [wholeALowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeAUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeB_covers_slope {s : ℝ} (hs : s ∈ Icc (2 * sLower + tLower) (2 * sUpper + tUpper)) :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.wholeBInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeBLower_contains wholeBUpper_contains _ _ hs
  · norm_num [wholeBLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeBUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeC_covers_slope {s : ℝ} (hs : s ∈ Icc (sLower + tLower) (sUpper + tUpper)) :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.wholeCInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeCLower_contains wholeCUpper_contains _ _ hs
  · norm_num [wholeCLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeCUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeD_covers_slope {s : ℝ} (hs : s ∈ Icc (sLower) (sUpper)) :
    ∃ a : ℝ, E8TAxisProd0594PaddedInputs.wholeDInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeDLower_contains wholeDUpper_contains _ _ hs
  · norm_num [wholeDLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeDUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

#print axioms centerA_covers
#print axioms wholeA_covers_slope
#print axioms wholeB_covers_slope

end GeneralCK.Certificates.E8TAxisProd0594EndpointWitnesses
