import GeneralCK.Certificates.E8TAxisZero0056GraphCenterA
import GeneralCK.Certificates.E8TAxisZero0056GraphCenterB
import GeneralCK.Certificates.E8TAxisZero0056GraphCenterC
import GeneralCK.Certificates.E8TAxisZero0056GraphCenterD
import GeneralCK.Certificates.E8TAxisZero0056GraphWholeA
import GeneralCK.Certificates.E8TAxisZero0056GraphWholeB
import GeneralCK.Certificates.E8TAxisZero0056GraphWholeC
import GeneralCK.Certificates.E8TAxisZero0056GraphWholeD
import GeneralCK.Certificates.E8TAxisRegularInverseBoxes
import GeneralCK.Certificates.E8TAxisZero0056Geometry
import GeneralCK.Certificates.E8TAxisRegularCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisZero0056CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisRegularCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisZero0056GraphCenterA.qJetBox,
   E8TAxisZero0056GraphCenterB.qJetBox,
   E8TAxisZero0056GraphCenterC.qJetBox,
   E8TAxisZero0056GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisZero0056GraphWholeA.qJetBox,
   E8TAxisZero0056GraphWholeB.qJetBox,
   E8TAxisZero0056GraphWholeC.qJetBox,
   E8TAxisZero0056GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨55753775917154727762522297773301751087340661164, 55753775917154727762522297773302033839042494203⟩
  | 0, 2 => ⟨159166204655631512674760297761453535169146756621, 159166204655631512674760297761454708044902718061⟩
  | 1, 1 => ⟨159231620643579506138041970834768071286241740442, 159231620643579506138041970834770242403280688574⟩
  | 0, 3 => ⟨311812876083434107205996841765844642150829425693, 311812876083434107205996841765848588218053891904⟩
  | 1, 2 => ⟨416553934531401369716510213545160325695700001082, 416553934531401369716510213545167544380228400064⟩
  | 2, 1 => ⟨416704886180044857731837542484061459205644023821, 416704886180044857731837542484074768417139241022⟩
  | 0, 4 => ⟨508516170349019946342640223529550644793377795585, 508516170349019946342640223529564588492637790216⟩
  | 1, 3 => ⟨750127622702225419019617311082990252716998710818, 750127622702225419019617311083015993989343057331⟩
  | 2, 2 => ⟨991809579238144510956739425031719938649082185763, 991809579238144510956739425031767863305687600776⟩
  | 3, 1 => ⟨992128207603707118328341750007500428371334117358, 992128207603707118328341750007590246287336817680⟩
  | 0, 5 => ⟨-2816726760048646268510671464212267481267599785747842, 2830661340088995407958001986967780590076034980588366⟩
  | 1, 4 => ⟨-5532075186878927236998878360620227146243487237772585, 5553054098124752792012737161990516259732840102262263⟩
  | 2, 3 => ⟨-10874834876228785204233039451140877992514203344092905, 10905022014916801754732687721624832862669141360969422⟩
  | 3, 2 => ⟨-21391073777971561077356892314378858724585729023872535, 21430591441657235945666564717415557100379265606943309⟩
  | 4, 1 => ⟨-42098438668376946940499723350930301929696278431178290, 42138539242065596331844103976331073003927362149864695⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisZero0056Geometry.ds, E8TAxisZero0056Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 52523694141161441458133961593037863478522326089 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsRegularAt s t) :
    data.CenterEnclosed (mixed E8TAxisRegularGermJet.regularQJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_regular_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_regular_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_regular_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_regular_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_regular_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_regular_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_regular_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_regular_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_regular_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_regular_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsRegularAt s t) :
    data.RemainderEnclosed (mixed E8TAxisRegularGermJet.regularQJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_regular_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_regular_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_regular_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_regular_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_regular_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisZero0056CertifiedArithmetic
