import GeneralCK.Certificates.E8TAxisProd0606GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0606GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0606GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0606GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0606GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0606GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0606GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0606GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0606Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0606CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0606GraphCenterA.qJetBox,
   E8TAxisProd0606GraphCenterB.qJetBox,
   E8TAxisProd0606GraphCenterC.qJetBox,
   E8TAxisProd0606GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0606GraphWholeA.qJetBox,
   E8TAxisProd0606GraphWholeB.qJetBox,
   E8TAxisProd0606GraphWholeC.qJetBox,
   E8TAxisProd0606GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨8613572365213716967136709598402141099867660175, 8613572365213716967136709598402198426121453844⟩
  | 0, 2 => ⟨28516384640795689603376222629163925884430455315, 28516384640795689603376222629164124138833745427⟩
  | 1, 1 => ⟨28646468489208329157153689615488471140122131830, 28646468489208329157153689615488816710477130037⟩
  | 0, 3 => ⟨64226009850893047823521348405879903837955118674, 64226009850893047823521348405880526928890037309⟩
  | 1, 2 => ⟨87526932767506266815428767530247131107750079377, 87526932767506266815428767530248214717892439311⟩
  | 2, 1 => ⟨87876687825421897101053613605713024601453642662, 87876687825421897101053613605714955241030863855⟩
  | 0, 4 => ⟨119642121950736087532572235666753583748085249118, 119642121950736087532572235666755633549303620291⟩
  | 1, 3 => ⟨182045846144039697286338550201825098696185125498, 182045846144039697286338550201828735963027310019⟩
  | 2, 2 => ⟨244644769373233149360986485350714472997258641908, 244644769373233149360986485350721063377879207576⟩
  | 3, 1 => ⟨245485068525996882991090083627166331044542494283, 245485068525996882991090083627178392955245525110⟩
  | 0, 5 => ⟨-328615684890881050440371238059918320310254513269982, 330798998035792557053668805899928693464237555118058⟩
  | 1, 4 => ⟨-637966504678439478694643257264573513018202017012002, 641205199585009235324966633423964174573676842665974⟩
  | 2, 3 => ⟨-1240345964586675852454807285363124053539861016286353, 1244966493001969170477257400835049689529087767765759⟩
  | 3, 2 => ⟨-2413546855725335194087694576003856858522854654029047, 2419581146623383571932293429481350823691184119572063⟩
  | 4, 1 => ⟨-4699069921415387287565570840891031335538690298710468, 4705240643912883284798236111300776214522247375039784⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0606Geometry.ds, E8TAxisProd0606Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 8043623395277760616250322894270931033054475699 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0606CertifiedArithmetic
