import GeneralCK.Certificates.E8TAxisProd0376GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0376GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0376GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0376GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0376GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0376GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0376GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0376GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0376Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0376CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0376GraphCenterA.qJetBox,
   E8TAxisProd0376GraphCenterB.qJetBox,
   E8TAxisProd0376GraphCenterC.qJetBox,
   E8TAxisProd0376GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0376GraphWholeA.qJetBox,
   E8TAxisProd0376GraphWholeB.qJetBox,
   E8TAxisProd0376GraphWholeC.qJetBox,
   E8TAxisProd0376GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨92468950434264384863767575653468430908468827455, 92468950434264384863767575653468914629016108096⟩
  | 0, 2 => ⟨252913233231826382677899799979502497462645955423, 252913233231826382677899799979504535128430137403⟩
  | 1, 1 => ⟨253208714997020805936363255881306798805668265300, 253208714997020805936363255881310582347305957220⟩
  | 0, 3 => ⟨477685586017149032705065053806825601832233969451, 477685586017149032705065053806832554031985632192⟩
  | 1, 2 => ⟨635605988330847179939931524436224597088031039424, 635605988330847179939931524436237372773109074475⟩
  | 2, 1 => ⟨636266191547932938290653120930641943118799174923, 636266191547932938290653120930665653830184843217⟩
  | 0, 4 => ⟨756937811305295217778768783765229265445285515561, 756937811305295217778768783765254393652102332506⟩
  | 1, 3 => ⟨1109429847629905312271146360934267633245938151645, 1109429847629905312271146360934314224187991002788⟩
  | 2, 2 => ⟨1462222489050468269595154617706076989120482046144, 1462222489050468269595154617706164211912181160848⟩
  | 3, 1 => ⟨1463590892129765441419565565490348169977214675067, 1463590892129765441419565565490512571333805046016⟩
  | 0, 5 => ⟨-4644285522385501806017218786282490281049758448180419, 4665134696459396846828995678651117402899271665939728⟩
  | 1, 4 => ⟨-9138843161880385780693361891709815959143586118040379, 9170183053199177813952898220375349207057700001689626⟩
  | 2, 3 => ⟨-17999197053763966774023611742559299329980640447005740, 18044236104266905333860796757590441021048388430656155⟩
  | 3, 2 => ⟨-35472772341058732799711203960978405045979639467012344, 35531687443591959027914820221552772991890996982123227⟩
  | 4, 1 => ⟨-69946998540776351312091209575027755849550267197072148, 70006751237545954863343522892411119951097364567887567⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0376Geometry.ds, E8TAxisProd0376Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 87323382344744977208318245817226574791596317704 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0376CertifiedArithmetic
