import GeneralCK.Certificates.E8TAxisFirstCellInverseCoverage
import GeneralCK.Certificates.E8TAxisProd0295Geometry
import GeneralCK.Certificates.E8TAxisProd0295PaddedInputs

/-!
# Endpoint certificates for all eight padded first-cell inverse brackets

Generated by `scripts/e8_taxis_emit_endpoint_witnesses.py`.
All primitive checks, scalar graph identities, and target comparisons
are checked separately. Coverage follows from the intermediate value theorem.
The exact lower cell boundaries are those in `E8TAxisProd0295Geometry`.
-/

namespace GeneralCK.Certificates.E8TAxisProd0295EndpointWitnesses

open Set DyadicInterval E8TAxisStableInterval E8TAxisStableScalar
open E8TAxisFirstCellInverseCoverage E8TAxisProd0295Geometry

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

def precision : ℕ := 160
def endpointLogTwo : DyadicInterval precision := ⟨1013035739299659071135698605846798551586536899314, 1013035739299659071135698605846798551586536899589⟩
def fastLogWitness : FastLogBoxWitness := ⟨0, 128, 0, 128⟩

theorem endpointLogTwo_checked :
    logBoxCheck (ofInt precision 2) endpointLogTwo fastLogWitness = true := by decide +kernel

def centerALowerAlpha : DyadicInterval precision := ⟨4590335763975281399345081579386246932603809519, 4590335763975281399345081579386246932603809519⟩
def centerALowerExp : DyadicInterval precision := ⟨1452349740496526708002027977982130831006559458830, 1452349740496526708002027977982130831006559460879⟩
def centerALowerLog : DyadicInterval precision := ⟨1008452612267868520487407126245153690937839073828, 1008452612267868520487407126245153690937839075123⟩
def centerALowerYBox : DyadicInterval precision := ⟨26489717176622615392441787592982629731263397613, 26489717176622615392441787592982629731263400680⟩
def centerALowerInput : Inputs precision :=
  ⟨centerALowerAlpha, centerALowerExp, centerALowerLog, endpointLogTwo⟩
def centerALowerExpWitness : ExpWitness precision :=
  ⟨1452349740496526708002027977982130831006559458830, scale precision, 1452349740496526708002027977982130831006559460879, scale precision,
    0, 128, 0, 128, ⟨-9180671527950562798690163158772493865207620321, -9180671527950562798690163158772493865207620058⟩, ⟨-9180671527950562798690163158772493865207618259, -9180671527950562798690163158772493865207617996⟩⟩

theorem centerALower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerALowerAlpha) centerALowerExp centerALowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerALowerExp) centerALowerLog fastLogWitness = true := by decide +kernel

theorem centerALower_denominators : DenominatorsPositive centerALowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerALower_yBox_eq : (yBox centerALowerInput).d0 = centerALowerYBox := by decide +kernel

theorem centerALower_contains :
    centerALowerYBox.Contains (Y (lower E8TAxisProd0295PaddedInputs.centerAInput.alpha)) := by
  rw [← centerALower_yBox_eq]
  apply checked_yBox_d0_contains centerALower_primitive_checks.1
    centerALower_primitive_checks.2 endpointLogTwo_checked centerALower_denominators
  exact point_contains precision 4590335763975281399345081579386246932603809519

def centerAUpperAlpha : DyadicInterval precision := ⟨4590335763975281399345081579386246932603940592, 4590335763975281399345081579386246932603940592⟩
def centerAUpperExp : DyadicInterval precision := ⟨1452349740496526708002027977982130831006559198326, 1452349740496526708002027977982130831006559200375⟩
def centerAUpperLog : DyadicInterval precision := ⟨1008452612267868520487407126245153690937838943172, 1008452612267868520487407126245153690937838944461⟩
def centerAUpperYBox : DyadicInterval precision := ⟨26489717176622615392441787592982629731264153998, 26489717176622615392441787592982629731264157062⟩
def centerAUpperInput : Inputs precision :=
  ⟨centerAUpperAlpha, centerAUpperExp, centerAUpperLog, endpointLogTwo⟩
def centerAUpperExpWitness : ExpWitness precision :=
  ⟨1452349740496526708002027977982130831006559198326, scale precision, 1452349740496526708002027977982130831006559200375, scale precision,
    0, 128, 0, 128, ⟨-9180671527950562798690163158772493865207882467, -9180671527950562798690163158772493865207882204⟩, ⟨-9180671527950562798690163158772493865207880405, -9180671527950562798690163158772493865207880142⟩⟩

theorem centerAUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerAUpperAlpha) centerAUpperExp centerAUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerAUpperExp) centerAUpperLog fastLogWitness = true := by decide +kernel

theorem centerAUpper_denominators : DenominatorsPositive centerAUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerAUpper_yBox_eq : (yBox centerAUpperInput).d0 = centerAUpperYBox := by decide +kernel

theorem centerAUpper_contains :
    centerAUpperYBox.Contains (Y (upper E8TAxisProd0295PaddedInputs.centerAInput.alpha)) := by
  rw [← centerAUpper_yBox_eq]
  apply checked_yBox_d0_contains centerAUpper_primitive_checks.1
    centerAUpper_primitive_checks.2 endpointLogTwo_checked centerAUpper_denominators
  exact point_contains precision 4590335763975281399345081579386246932603940592

def centerBLowerAlpha : DyadicInterval precision := ⟨1747218414921219117848495143064616713388768667077, 1747218414921219117848495143064616713388768667077⟩
def centerBLowerExp : DyadicInterval precision := ⟨133784326570533634139807104724014569301766075386, 133784326570533634139807104724014569301766077435⟩
def centerBLowerLog : DyadicInterval precision := ⟨128010856007604251799636349855958167641375575360, 128010856007604251799636349855958167641375577509⟩
def centerBLowerYBox : DyadicInterval precision := ⟨7605745864522351967764363599757581601978201197140, 7605745864522351967764363599757581601978201298009⟩
def centerBLowerInput : Inputs precision :=
  ⟨centerBLowerAlpha, centerBLowerExp, centerBLowerLog, endpointLogTwo⟩
def centerBLowerExpWitness : ExpWitness precision :=
  ⟨133784326570533634139807104724014569301766075386, scale precision, 133784326570533634139807104724014569301766077435, scale precision,
    3, 128, 3, 128,
    ⟨-3494436829842438235696990286129233426777537346244, -3494436829842438235696990286129233426777537345152⟩, ⟨-3494436829842438235696990286129233426777537323860, -3494436829842438235696990286129233426777537322766⟩⟩

theorem centerBLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerBLowerAlpha) centerBLowerExp centerBLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerBLowerExp) centerBLowerLog fastLogWitness = true := by decide +kernel

theorem centerBLower_denominators : DenominatorsPositive centerBLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerBLower_yBox_eq : (yBox centerBLowerInput).d0 = centerBLowerYBox := by decide +kernel

theorem centerBLower_contains :
    centerBLowerYBox.Contains (Y (lower E8TAxisProd0295PaddedInputs.centerBInput.alpha)) := by
  rw [← centerBLower_yBox_eq]
  apply checked_yBox_d0_contains centerBLower_primitive_checks.1
    centerBLower_primitive_checks.2 endpointLogTwo_checked centerBLower_denominators
  exact point_contains precision 1747218414921219117848495143064616713388768667077

def centerBUpperAlpha : DyadicInterval precision := ⟨1747218414921219117848495143064616713388768798150, 1747218414921219117848495143064616713388768798150⟩
def centerBUpperExp : DyadicInterval precision := ⟨133784326570533634139807104724014569301766051389, 133784326570533634139807104724014569301766053438⟩
def centerBUpperLog : DyadicInterval precision := ⟨128010856007604251799636349855958167641375553376, 128010856007604251799636349855958167641375555525⟩
def centerBUpperYBox : DyadicInterval precision := ⟨7605745864522351967764363599757581601978201600612, 7605745864522351967764363599757581601978201701496⟩
def centerBUpperInput : Inputs precision :=
  ⟨centerBUpperAlpha, centerBUpperExp, centerBUpperLog, endpointLogTwo⟩
def centerBUpperExpWitness : ExpWitness precision :=
  ⟨133784326570533634139807104724014569301766051389, scale precision, 133784326570533634139807104724014569301766053438, scale precision,
    3, 128, 3, 128,
    ⟨-3494436829842438235696990286129233426777537608394, -3494436829842438235696990286129233426777537607302⟩, ⟨-3494436829842438235696990286129233426777537586008, -3494436829842438235696990286129233426777537584918⟩⟩

theorem centerBUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerBUpperAlpha) centerBUpperExp centerBUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerBUpperExp) centerBUpperLog fastLogWitness = true := by decide +kernel

theorem centerBUpper_denominators : DenominatorsPositive centerBUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerBUpper_yBox_eq : (yBox centerBUpperInput).d0 = centerBUpperYBox := by decide +kernel

theorem centerBUpper_contains :
    centerBUpperYBox.Contains (Y (upper E8TAxisProd0295PaddedInputs.centerBInput.alpha)) := by
  rw [← centerBUpper_yBox_eq]
  apply checked_yBox_d0_contains centerBUpper_primitive_checks.1
    centerBUpper_primitive_checks.2 endpointLogTwo_checked centerBUpper_denominators
  exact point_contains precision 1747218414921219117848495143064616713388768798150

def centerCLowerAlpha : DyadicInterval precision := ⟨716278251275813859315557252004682783676832932260, 716278251275813859315557252004682783676832932260⟩
def centerCLowerExp : DyadicInterval precision := ⟨548410870531673399042357809545285291477889534151, 548410870531673399042357809545285291477889536200⟩
def centerCLowerLog : DyadicInterval precision := ⟨465673541404822342686973974550477249520875356140, 465673541404822342686973974550477249520875357897⟩
def centerCLowerYBox : DyadicInterval precision := ⟨3816117790849487291578402693675282115854732298411, 3816117790849487291578402693675282115854732325268⟩
def centerCLowerInput : Inputs precision :=
  ⟨centerCLowerAlpha, centerCLowerExp, centerCLowerLog, endpointLogTwo⟩
def centerCLowerExpWitness : ExpWitness precision :=
  ⟨548410870531673399042357809545285291477889534151, scale precision, 548410870531673399042357809545285291477889536200, scale precision,
    1, 128, 1, 128,
    ⟨-1432556502551627718631114504009365567353665867710, -1432556502551627718631114504009365567353665867166⟩, ⟨-1432556502551627718631114504009365567353665862252, -1432556502551627718631114504009365567353665861708⟩⟩

theorem centerCLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerCLowerAlpha) centerCLowerExp centerCLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerCLowerExp) centerCLowerLog fastLogWitness = true := by decide +kernel

theorem centerCLower_denominators : DenominatorsPositive centerCLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerCLower_yBox_eq : (yBox centerCLowerInput).d0 = centerCLowerYBox := by decide +kernel

theorem centerCLower_contains :
    centerCLowerYBox.Contains (Y (lower E8TAxisProd0295PaddedInputs.centerCInput.alpha)) := by
  rw [← centerCLower_yBox_eq]
  apply checked_yBox_d0_contains centerCLower_primitive_checks.1
    centerCLower_primitive_checks.2 endpointLogTwo_checked centerCLower_denominators
  exact point_contains precision 716278251275813859315557252004682783676832932260

def centerCUpperAlpha : DyadicInterval precision := ⟨716278251275813859315557252004682783676833063333, 716278251275813859315557252004682783676833063333⟩
def centerCUpperExp : DyadicInterval precision := ⟨548410870531673399042357809545285291477889435784, 548410870531673399042357809545285291477889437833⟩
def centerCUpperLog : DyadicInterval precision := ⟨465673541404822342686973974550477249520875284612, 465673541404822342686973974550477249520875286369⟩
def centerCUpperYBox : DyadicInterval precision := ⟨3816117790849487291578402693675282115854732900979, 3816117790849487291578402693675282115854732927841⟩
def centerCUpperInput : Inputs precision :=
  ⟨centerCUpperAlpha, centerCUpperExp, centerCUpperLog, endpointLogTwo⟩
def centerCUpperExpWitness : ExpWitness precision :=
  ⟨548410870531673399042357809545285291477889435784, scale precision, 548410870531673399042357809545285291477889437833, scale precision,
    1, 128, 1, 128,
    ⟨-1432556502551627718631114504009365567353666129856, -1432556502551627718631114504009365567353666129316⟩, ⟨-1432556502551627718631114504009365567353666124396, -1432556502551627718631114504009365567353666123854⟩⟩

theorem centerCUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerCUpperAlpha) centerCUpperExp centerCUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerCUpperExp) centerCUpperLog fastLogWitness = true := by decide +kernel

theorem centerCUpper_denominators : DenominatorsPositive centerCUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerCUpper_yBox_eq : (yBox centerCUpperInput).d0 = centerCUpperYBox := by decide +kernel

theorem centerCUpper_contains :
    centerCUpperYBox.Contains (Y (upper E8TAxisProd0295PaddedInputs.centerCInput.alpha)) := by
  rw [← centerCUpper_yBox_eq]
  apply checked_yBox_d0_contains centerCUpper_primitive_checks.1
    centerCUpper_primitive_checks.2 endpointLogTwo_checked centerCUpper_denominators
  exact point_contains precision 716278251275813859315557252004682783676833063333

def centerDLowerAlpha : DyadicInterval precision := ⟨710524563403850356500890582610538039823373949832, 710524563403850356500890582610538039823373949832⟩
def centerDLowerExp : DyadicInterval precision := ⟨552745918518612785766768712299414360459400695730, 552745918518612785766768712299414360459400697779⟩
def centerDLowerLog : DyadicInterval precision := ⟨468822363559667384554973018042110608872909385966, 468822363559667384554973018042110608872909387719⟩
def centerDLowerYBox : DyadicInterval precision := ⟨3789628073672864676185960906082299486123468520309, 3789628073672864676185960906082299486123468546911⟩
def centerDLowerInput : Inputs precision :=
  ⟨centerDLowerAlpha, centerDLowerExp, centerDLowerLog, endpointLogTwo⟩
def centerDLowerExpWitness : ExpWitness precision :=
  ⟨552745918518612785766768712299414360459400695730, scale precision, 552745918518612785766768712299414360459400697779, scale precision,
    1, 128, 1, 128,
    ⟨-1421049126807700713001781165221076079646747902834, -1421049126807700713001781165221076079646747902290⟩, ⟨-1421049126807700713001781165221076079646747897418, -1421049126807700713001781165221076079646747896874⟩⟩

theorem centerDLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerDLowerAlpha) centerDLowerExp centerDLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerDLowerExp) centerDLowerLog fastLogWitness = true := by decide +kernel

theorem centerDLower_denominators : DenominatorsPositive centerDLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerDLower_yBox_eq : (yBox centerDLowerInput).d0 = centerDLowerYBox := by decide +kernel

theorem centerDLower_contains :
    centerDLowerYBox.Contains (Y (lower E8TAxisProd0295PaddedInputs.centerDInput.alpha)) := by
  rw [← centerDLower_yBox_eq]
  apply checked_yBox_d0_contains centerDLower_primitive_checks.1
    centerDLower_primitive_checks.2 endpointLogTwo_checked centerDLower_denominators
  exact point_contains precision 710524563403850356500890582610538039823373949832

def centerDUpperAlpha : DyadicInterval precision := ⟨710524563403850356500890582610538039823374080905, 710524563403850356500890582610538039823374080905⟩
def centerDUpperExp : DyadicInterval precision := ⟨552745918518612785766768712299414360459400596585, 552745918518612785766768712299414360459400598634⟩
def centerDUpperLog : DyadicInterval precision := ⟨468822363559667384554973018042110608872909314030, 468822363559667384554973018042110608872909315783⟩
def centerDUpperYBox : DyadicInterval precision := ⟨3789628073672864676185960906082299486123469124651, 3789628073672864676185960906082299486123469151250⟩
def centerDUpperInput : Inputs precision :=
  ⟨centerDUpperAlpha, centerDUpperExp, centerDUpperLog, endpointLogTwo⟩
def centerDUpperExpWitness : ExpWitness precision :=
  ⟨552745918518612785766768712299414360459400596585, scale precision, 552745918518612785766768712299414360459400598634, scale precision,
    1, 128, 1, 128,
    ⟨-1421049126807700713001781165221076079646748164984, -1421049126807700713001781165221076079646748164438⟩, ⟨-1421049126807700713001781165221076079646748159566, -1421049126807700713001781165221076079646748159020⟩⟩

theorem centerDUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerDUpperAlpha) centerDUpperExp centerDUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerDUpperExp) centerDUpperLog fastLogWitness = true := by decide +kernel

theorem centerDUpper_denominators : DenominatorsPositive centerDUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerDUpper_yBox_eq : (yBox centerDUpperInput).d0 = centerDUpperYBox := by decide +kernel

theorem centerDUpper_contains :
    centerDUpperYBox.Contains (Y (upper E8TAxisProd0295PaddedInputs.centerDInput.alpha)) := by
  rw [← centerDUpper_yBox_eq]
  apply checked_yBox_d0_contains centerDUpper_primitive_checks.1
    centerDUpper_primitive_checks.2 endpointLogTwo_checked centerDUpper_denominators
  exact point_contains precision 710524563403850356500890582610538039823374080905

def wholeALowerAlpha : DyadicInterval precision := ⟨4432047174048269527644776165804031130864610368, 4432047174048269527644776165804031130864610368⟩
def wholeALowerExp : DyadicInterval precision := ⟨1452664369350591901250217311774540049762303959345, 1452664369350591901250217311774540049762303961394⟩
def wholeALowerLog : DyadicInterval precision := ⟨1008610412272733567070593870872814920969193762208, 1008610412272733567070593870872814920969193763499⟩
def wholeALowerYBox : DyadicInterval precision := ⟨25576278653290801068564484572534952843978439780, 25576278653290801068564484572534952843978442841⟩
def wholeALowerInput : Inputs precision :=
  ⟨wholeALowerAlpha, wholeALowerExp, wholeALowerLog, endpointLogTwo⟩
def wholeALowerExpWitness : ExpWitness precision :=
  ⟨1452664369350591901250217311774540049762303959345, scale precision, 1452664369350591901250217311774540049762303961394, scale precision,
    0, 128, 0, 128, ⟨-8864094348096539055289552331608062261729222019, -8864094348096539055289552331608062261729221758⟩, ⟨-8864094348096539055289552331608062261729219957, -8864094348096539055289552331608062261729219696⟩⟩

theorem wholeALower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeALowerAlpha) wholeALowerExp wholeALowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeALowerExp) wholeALowerLog fastLogWitness = true := by decide +kernel

theorem wholeALower_denominators : DenominatorsPositive wholeALowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeALower_yBox_eq : (yBox wholeALowerInput).d0 = wholeALowerYBox := by decide +kernel

theorem wholeALower_contains :
    wholeALowerYBox.Contains (Y (lower E8TAxisProd0295PaddedInputs.wholeAInput.alpha)) := by
  rw [← wholeALower_yBox_eq]
  apply checked_yBox_d0_contains wholeALower_primitive_checks.1
    wholeALower_primitive_checks.2 endpointLogTwo_checked wholeALower_denominators
  exact point_contains precision 4432047174048269527644776165804031130864610368

def wholeAUpperAlpha : DyadicInterval precision := ⟨4748624479255801076876082777124010865681716875, 4748624479255801076876082777124010865681716875⟩
def wholeAUpperExp : DyadicInterval precision := ⟨1452035179538035812075122148102075717554934481868, 1452035179538035812075122148102075717554934483917⟩
def wholeAUpperLog : DyadicInterval precision := ⟨1008294829281404787796718047455216464285448679886, 1008294829281404787796718047455216464285448681177⟩
def wholeAUpperYBox : DyadicInterval precision := ⟨27403155699954429716319090613430306618549111840, 27403155699954429716319090613430306618549114907⟩
def wholeAUpperInput : Inputs precision :=
  ⟨wholeAUpperAlpha, wholeAUpperExp, wholeAUpperLog, endpointLogTwo⟩
def wholeAUpperExpWitness : ExpWitness precision :=
  ⟨1452035179538035812075122148102075717554934481868, scale precision, 1452035179538035812075122148102075717554934483917, scale precision,
    0, 128, 0, 128, ⟨-9497248958511602153752165554248021731363435031, -9497248958511602153752165554248021731363434768⟩, ⟨-9497248958511602153752165554248021731363432969, -9497248958511602153752165554248021731363432706⟩⟩

theorem wholeAUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeAUpperAlpha) wholeAUpperExp wholeAUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeAUpperExp) wholeAUpperLog fastLogWitness = true := by decide +kernel

theorem wholeAUpper_denominators : DenominatorsPositive wholeAUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeAUpper_yBox_eq : (yBox wholeAUpperInput).d0 = wholeAUpperYBox := by decide +kernel

theorem wholeAUpper_contains :
    wholeAUpperYBox.Contains (Y (upper E8TAxisProd0295PaddedInputs.wholeAInput.alpha)) := by
  rw [← wholeAUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeAUpper_primitive_checks.1
    wholeAUpper_primitive_checks.2 endpointLogTwo_checked wholeAUpper_denominators
  exact point_contains precision 4748624479255801076876082777124010865681716875

def wholeBLowerAlpha : DyadicInterval precision := ⟨1729889549436356120419450138046724972925043761798, 1729889549436356120419450138046724972925043761798⟩
def wholeBLowerExp : DyadicInterval precision := ⟨136994774385991933216964520234630133135369435991, 136994774385991933216964520234630133135369438040⟩
def wholeBLowerLog : DyadicInterval precision := ⟨130949112762396578556967171589626096068964690092, 130949112762396578556967171589626096068964692231⟩
def wholeBLowerYBox : DyadicInterval precision := ⟨7552309710907440829817541373061392504072031163851, 7552309710907440829817541373061392504072031262660⟩
def wholeBLowerInput : Inputs precision :=
  ⟨wholeBLowerAlpha, wholeBLowerExp, wholeBLowerLog, endpointLogTwo⟩
def wholeBLowerExpWitness : ExpWitness precision :=
  ⟨136994774385991933216964520234630133135369435991, scale precision, 136994774385991933216964520234630133135369438040, scale precision,
    3, 128, 3, 128,
    ⟨-3459779098872712240838900276093449945850087535424, -3459779098872712240838900276093449945850087534332⟩, ⟨-3459779098872712240838900276093449945850087513564, -3459779098872712240838900276093449945850087512476⟩⟩

theorem wholeBLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeBLowerAlpha) wholeBLowerExp wholeBLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeBLowerExp) wholeBLowerLog fastLogWitness = true := by decide +kernel

theorem wholeBLower_denominators : DenominatorsPositive wholeBLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeBLower_yBox_eq : (yBox wholeBLowerInput).d0 = wholeBLowerYBox := by decide +kernel

theorem wholeBLower_contains :
    wholeBLowerYBox.Contains (Y (lower E8TAxisProd0295PaddedInputs.wholeBInput.alpha)) := by
  rw [← wholeBLower_yBox_eq]
  apply checked_yBox_d0_contains wholeBLower_primitive_checks.1
    wholeBLower_primitive_checks.2 endpointLogTwo_checked wholeBLower_denominators
  exact point_contains precision 1729889549436356120419450138046724972925043761798

def wholeBUpperAlpha : DyadicInterval precision := ⟨1764607600105616150080605020414501265452494309598, 1764607600105616150080605020414501265452494309598⟩
def wholeBUpperExp : DyadicInterval precision := ⟨130638331056824412386060033823056433928056883236, 130638331056824412386060033823056433928056885285⟩
def wholeBUpperLog : DyadicInterval precision := ⟨125125845227722155733946265151055994762781622218, 125125845227722155733946265151055994762781624361⟩
def wholeBUpperYBox : DyadicInterval precision := ⟨7659182018137263105711185826453770699884371632557, 7659182018137263105711185826453770699884371735432⟩
def wholeBUpperInput : Inputs precision :=
  ⟨wholeBUpperAlpha, wholeBUpperExp, wholeBUpperLog, endpointLogTwo⟩
def wholeBUpperExpWitness : ExpWitness precision :=
  ⟨130638331056824412386060033823056433928056883236, scale precision, 130638331056824412386060033823056433928056885285, scale precision,
    3, 128, 3, 128,
    ⟨-3529215200211232300161210040829002530904988631552, -3529215200211232300161210040829002530904988630466⟩, ⟨-3529215200211232300161210040829002530904988608628, -3529215200211232300161210040829002530904988607540⟩⟩

theorem wholeBUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeBUpperAlpha) wholeBUpperExp wholeBUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeBUpperExp) wholeBUpperLog fastLogWitness = true := by decide +kernel

theorem wholeBUpper_denominators : DenominatorsPositive wholeBUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeBUpper_yBox_eq : (yBox wholeBUpperInput).d0 = wholeBUpperYBox := by decide +kernel

theorem wholeBUpper_contains :
    wholeBUpperYBox.Contains (Y (upper E8TAxisProd0295PaddedInputs.wholeBInput.alpha)) := by
  rw [← wholeBUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeBUpper_primitive_checks.1
    wholeBUpper_primitive_checks.2 endpointLogTwo_checked wholeBUpper_denominators
  exact point_contains precision 1764607600105616150080605020414501265452494309598

def wholeCLowerAlpha : DyadicInterval precision := ⟨710375984744079666965525749940701742740995695871, 710375984744079666965525749940701742740995695871⟩
def wholeCLowerExp : DyadicInterval precision := ⟨552858316062788645412766309955396676992277354375, 552858316062788645412766309955396676992277356424⟩
def wholeCLowerLog : DyadicInterval precision := ⟨468903914911845880875209036562913361999830083556, 468903914911845880875209036562913361999830085309⟩
def wholeCLowerYBox : DyadicInterval precision := ⟨3788942994780365815443052928816963728458004801912, 3788942994780365815443052928816963728458004828504⟩
def wholeCLowerInput : Inputs precision :=
  ⟨wholeCLowerAlpha, wholeCLowerExp, wholeCLowerLog, endpointLogTwo⟩
def wholeCLowerExpWitness : ExpWitness precision :=
  ⟨552858316062788645412766309955396676992277354375, scale precision, 552858316062788645412766309955396676992277356424, scale precision,
    1, 128, 1, 128,
    ⟨-1420751969488159333931051499881403485481991394908, -1420751969488159333931051499881403485481991394368⟩, ⟨-1420751969488159333931051499881403485481991389490, -1420751969488159333931051499881403485481991388950⟩⟩

theorem wholeCLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeCLowerAlpha) wholeCLowerExp wholeCLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeCLowerExp) wholeCLowerLog fastLogWitness = true := by decide +kernel

theorem wholeCLower_denominators : DenominatorsPositive wholeCLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeCLower_yBox_eq : (yBox wholeCLowerInput).d0 = wholeCLowerYBox := by decide +kernel

theorem wholeCLower_contains :
    wholeCLowerYBox.Contains (Y (lower E8TAxisProd0295PaddedInputs.wholeCInput.alpha)) := by
  rw [← wholeCLower_yBox_eq]
  apply checked_yBox_d0_contains wholeCLower_primitive_checks.1
    wholeCLower_primitive_checks.2 endpointLogTwo_checked wholeCLower_denominators
  exact point_contains precision 710375984744079666965525749940701742740995695871

def wholeCUpperAlpha : DyadicInterval precision := ⟨722198344994417869219609110170833200809152087811, 722198344994417869219609110170833200809152087811⟩
def wholeCUpperExp : DyadicInterval precision := ⟨543985931203311227643823781124117991704123667608, 543985931203311227643823781124117991704123669657⟩
def wholeCUpperLog : DyadicInterval precision := ⟨462452413463253984708760357722707628191662669508, 462452413463253984708760357722707628191662671271⟩
def wholeCUpperYBox : DyadicInterval precision := ⟨3843292586918608767713752458533600503251460395648, 3843292586918608767713752458533600503251460422780⟩
def wholeCUpperInput : Inputs precision :=
  ⟨wholeCUpperAlpha, wholeCUpperExp, wholeCUpperLog, endpointLogTwo⟩
def wholeCUpperExpWitness : ExpWitness precision :=
  ⟨543985931203311227643823781124117991704123667608, scale precision, 543985931203311227643823781124117991704123669657, scale precision,
    1, 128, 1, 128,
    ⟨-1444396689988835738439218220341666401618304178826, -1444396689988835738439218220341666401618304178290⟩, ⟨-1444396689988835738439218220341666401618304173320, -1444396689988835738439218220341666401618304172782⟩⟩

theorem wholeCUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeCUpperAlpha) wholeCUpperExp wholeCUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeCUpperExp) wholeCUpperLog fastLogWitness = true := by decide +kernel

theorem wholeCUpper_denominators : DenominatorsPositive wholeCUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeCUpper_yBox_eq : (yBox wholeCUpperInput).d0 = wholeCUpperYBox := by decide +kernel

theorem wholeCUpper_contains :
    wholeCUpperYBox.Contains (Y (upper E8TAxisProd0295PaddedInputs.wholeCInput.alpha)) := by
  rw [← wholeCUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeCUpper_primitive_checks.1
    wholeCUpper_primitive_checks.2 endpointLogTwo_checked wholeCUpper_denominators
  exact point_contains precision 722198344994417869219609110170833200809152087811

def wholeDLowerAlpha : DyadicInterval precision := ⟨704837076587479092158941059188951191105661957302, 704837076587479092158941059188951191105661957302⟩
def wholeDLowerExp : DyadicInterval precision := ⟨557064765387537285209117120927584103824744234043, 557064765387537285209117120927584103824744236092⟩
def wholeDLowerLog : DyadicInterval precision := ⟨471952686082951260798866870121334519151396950840, 471952686082951260798866870121334519151396952585⟩
def wholeDLowerYBox : DyadicInterval precision := ⟨3763366716127075014374488444244428775614025981690, 3763366716127075014374488444244428775614026008021⟩
def wholeDLowerInput : Inputs precision :=
  ⟨wholeDLowerAlpha, wholeDLowerExp, wholeDLowerLog, endpointLogTwo⟩
def wholeDLowerExpWitness : ExpWitness precision :=
  ⟨557064765387537285209117120927584103824744234043, scale precision, 557064765387537285209117120927584103824744236092, scale precision,
    1, 128, 1, 128,
    ⟨-1409674153174958184317882118377902382211323917750, -1409674153174958184317882118377902382211323917210⟩, ⟨-1409674153174958184317882118377902382211323912374, -1409674153174958184317882118377902382211323911834⟩⟩

theorem wholeDLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeDLowerAlpha) wholeDLowerExp wholeDLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeDLowerExp) wholeDLowerLog fastLogWitness = true := by decide +kernel

theorem wholeDLower_denominators : DenominatorsPositive wholeDLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeDLower_yBox_eq : (yBox wholeDLowerInput).d0 = wholeDLowerYBox := by decide +kernel

theorem wholeDLower_contains :
    wholeDLowerYBox.Contains (Y (lower E8TAxisProd0295PaddedInputs.wholeDInput.alpha)) := by
  rw [← wholeDLower_yBox_eq]
  apply checked_yBox_d0_contains wholeDLower_primitive_checks.1
    wholeDLower_primitive_checks.2 endpointLogTwo_checked wholeDLower_denominators
  exact point_contains precision 704837076587479092158941059188951191105661957302

def wholeDUpperAlpha : DyadicInterval precision := ⟨716228578308099727358082939138935890959899278031, 716228578308099727358082939138935890959899278031⟩
def wholeDUpperExp : DyadicInterval precision := ⟨548448150163327086956497611001597702787279706141, 548448150163327086956497611001597702787279708190⟩
def wholeDUpperLog : DyadicInterval precision := ⟨465700648921796470149242465934935276152315819394, 465700648921796470149242465934935276152315821147⟩
def wholeDUpperYBox : DyadicInterval precision := ⟨3815889431218654337997433367920170196632911661534, 3815889431218654337997433367920170196632911688376⟩
def wholeDUpperInput : Inputs precision :=
  ⟨wholeDUpperAlpha, wholeDUpperExp, wholeDUpperLog, endpointLogTwo⟩
def wholeDUpperExpWitness : ExpWitness precision :=
  ⟨548448150163327086956497611001597702787279706141, scale precision, 548448150163327086956497611001597702787279708190, scale precision,
    1, 128, 1, 128,
    ⟨-1432457156616199454716165878277871781919798559246, -1432457156616199454716165878277871781919798558706⟩, ⟨-1432457156616199454716165878277871781919798553786, -1432457156616199454716165878277871781919798553246⟩⟩

theorem wholeDUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeDUpperAlpha) wholeDUpperExp wholeDUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeDUpperExp) wholeDUpperLog fastLogWitness = true := by decide +kernel

theorem wholeDUpper_denominators : DenominatorsPositive wholeDUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeDUpper_yBox_eq : (yBox wholeDUpperInput).d0 = wholeDUpperYBox := by decide +kernel

theorem wholeDUpper_contains :
    wholeDUpperYBox.Contains (Y (upper E8TAxisProd0295PaddedInputs.wholeDInput.alpha)) := by
  rw [← wholeDUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeDUpper_primitive_checks.1
    wholeDUpper_primitive_checks.2 endpointLogTwo_checked wholeDUpper_denominators
  exact point_contains precision 716228578308099727358082939138935890959899278031

theorem centerA_covers_slope {s : ℝ} (hs : s ∈ Icc (centerT) (centerT)) :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.centerAInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerALower_contains centerAUpper_contains _ _ hs
  · norm_num [centerALowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerAUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerA_covers :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.centerAInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerT) :=
  centerA_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerB_covers_slope {s : ℝ} (hs : s ∈ Icc (2 * centerS + centerT) (2 * centerS + centerT)) :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.centerBInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerBLower_contains centerBUpper_contains _ _ hs
  · norm_num [centerBLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerBUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerB_covers :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.centerBInput.alpha.Contains a ∧
      0 < a ∧ Y a = (2 * centerS + centerT) :=
  centerB_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerC_covers_slope {s : ℝ} (hs : s ∈ Icc (centerS + centerT) (centerS + centerT)) :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.centerCInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerCLower_contains centerCUpper_contains _ _ hs
  · norm_num [centerCLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerCUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerC_covers :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.centerCInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerS + centerT) :=
  centerC_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerD_covers_slope {s : ℝ} (hs : s ∈ Icc (centerS) (centerS)) :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.centerDInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerDLower_contains centerDUpper_contains _ _ hs
  · norm_num [centerDLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerDUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerD_covers :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.centerDInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerS) :=
  centerD_covers_slope ⟨le_rfl, le_rfl⟩

theorem wholeA_covers_slope {s : ℝ} (hs : s ∈ Icc (tLower) (tUpper)) :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.wholeAInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeALower_contains wholeAUpper_contains _ _ hs
  · norm_num [wholeALowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeAUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeB_covers_slope {s : ℝ} (hs : s ∈ Icc (2 * sLower + tLower) (2 * sUpper + tUpper)) :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.wholeBInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeBLower_contains wholeBUpper_contains _ _ hs
  · norm_num [wholeBLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeBUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeC_covers_slope {s : ℝ} (hs : s ∈ Icc (sLower + tLower) (sUpper + tUpper)) :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.wholeCInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeCLower_contains wholeCUpper_contains _ _ hs
  · norm_num [wholeCLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeCUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeD_covers_slope {s : ℝ} (hs : s ∈ Icc (sLower) (sUpper)) :
    ∃ a : ℝ, E8TAxisProd0295PaddedInputs.wholeDInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeDLower_contains wholeDUpper_contains _ _ hs
  · norm_num [wholeDLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeDUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

#print axioms centerA_covers
#print axioms wholeA_covers_slope
#print axioms wholeB_covers_slope

end GeneralCK.Certificates.E8TAxisProd0295EndpointWitnesses
