import GeneralCK.Certificates.E8TAxisProd0131GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0131GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0131GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0131GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0131GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0131GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0131GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0131GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0131Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0131CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0131GraphCenterA.qJetBox,
   E8TAxisProd0131GraphCenterB.qJetBox,
   E8TAxisProd0131GraphCenterC.qJetBox,
   E8TAxisProd0131GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0131GraphWholeA.qJetBox,
   E8TAxisProd0131GraphWholeB.qJetBox,
   E8TAxisProd0131GraphWholeC.qJetBox,
   E8TAxisProd0131GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨1863193613668600711182565096569195526837302596, 1863193613668600711182565096569216262863870990⟩
  | 0, 2 => ⟨6919144058787543304406921963801778831138522977, 6919144058787543304406921963801838398720036938⟩
  | 1, 1 => ⟨6960827976165244107245437759996470000358525188, 6960827976165244107245437759996566810839051962⟩
  | 0, 3 => ⟨17152183961398845381946891950930633061499442170, 17152183961398845381946891950930806295777945989⟩
  | 1, 2 => ⟨23884757215025269748515764609467921856447886759, 23884757215025269748515764609468205537306453535⟩
  | 2, 1 => ⟨24011042059267388283807069246129856085381192518, 24011042059267388283807069246130343860251243895⟩
  | 0, 4 => ⟨35361884575946674294687014363779860082682132596, 35361884575946674294687014363780394585297277496⟩
  | 1, 3 => ⟨55657107615738364657384262000131756143017161335, 55657107615738364657384262000132657266621211699⟩
  | 2, 2 => ⟨76038055799165583870918659075491413292827253864, 76038055799165583870918659075492995806007294527⟩
  | 3, 1 => ⟨76388734330465790656937209339614739261107576735, 76388734330465790656937209339617564519828878232⟩
  | 0, 5 => ⟨-518856589649918679559757951221303111292717751921454, 520368978277824347161296555207396206702954955871553⟩
  | 1, 4 => ⟨-1008629467544382101337972261009802205773653103033073, 1010717765049321576580679348390178723305854044113057⟩
  | 2, 3 => ⟨-1962790664877202753194196407713909036709963023644337, 1965632947129722477288109905516931893450120488937783⟩
  | 3, 2 => ⟨-3821639732142435273393660322870616966707559484691801, 3825290460547293985813940433986207311439415050458478⟩
  | 4, 1 => ⟨-7443078043726293078035744754915240603486294856587092, 7446959405269724730735703303576899040268224483790675⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0131Geometry.ds, E8TAxisProd0131Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 1302915670046743055141063531608716441433284457 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0131CertifiedArithmetic
