import GeneralCK.Certificates.E8TAxisProd0090GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0090GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0090GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0090GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0090GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0090GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0090GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0090GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0090Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0090CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0090GraphCenterA.qJetBox,
   E8TAxisProd0090GraphCenterB.qJetBox,
   E8TAxisProd0090GraphCenterC.qJetBox,
   E8TAxisProd0090GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0090GraphWholeA.qJetBox,
   E8TAxisProd0090GraphWholeB.qJetBox,
   E8TAxisProd0090GraphWholeC.qJetBox,
   E8TAxisProd0090GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨975504033318090519250283174634679374677676, 975504033318090519250283174636591585647564⟩
  | 0, 2 => ⟨9400394914681133505447943248770269772810779, 9400394914681133505447943248774873321110977⟩
  | 1, 1 => ⟨9653866716977099504623388036251407398019156, 9653866716977099504623388036257042355542832⟩
  | 0, 3 => ⟨47072233016763092146010267411014841127494177, 47072233016763092146010267411023465704191315⟩
  | 1, 2 => ⟨76835278762133686004489236417860985471679864, 76835278762133686004489236417871027710155028⟩
  | 2, 1 => ⟨78432076253061162058093182991263285842143899, 78432076253061162058093182991277155825777081⟩
  | 0, 4 => ⟨128531900526917963606893929536327804452280988, 128531900526917963606893929536351249839884819⟩
  | 1, 3 => ⟨311671263856072958236150196072221394388030875, 311671263856072958236150196072249172701550327⟩
  | 2, 2 => ⟨497906067478024680965589770322514714531802085, 497906067478024680965589770322553781165809107⟩
  | 3, 1 => ⟨505406880548214545347936705379141793042217412, 505406880548214545347936705379202554122142383⟩
  | 0, 5 => ⟨-506566686843881243017482927884942018616598714566, 513122044043712412420372440342912657486157480102⟩
  | 1, 4 => ⟨-845978222333418211386912810721258543632062478347, 847422913801622106713567968022034089560215350672⟩
  | 2, 3 => ⟨-1446041677902937564714076709326737057984875010473, 1441229812444924338481057659728157952757645587876⟩
  | 3, 2 => ⟨-2484508871511866991957192182929448646843881032487, 2473772332312888663904947178267629567379232380587⟩
  | 4, 1 => ⟨-4250304351560758038544552919015450203257864432523, 4240921700236765498319638964406807704595587672785⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0090Geometry.ds, E8TAxisProd0090Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 788726507057132190297500587597723901405042 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0090CertifiedArithmetic
