import GeneralCK.Certificates.E8TAxisProd0113GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0113GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0113GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0113GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0113GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0113GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0113GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0113GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0113Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0113CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0113GraphCenterA.qJetBox,
   E8TAxisProd0113GraphCenterB.qJetBox,
   E8TAxisProd0113GraphCenterC.qJetBox,
   E8TAxisProd0113GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0113GraphWholeA.qJetBox,
   E8TAxisProd0113GraphWholeB.qJetBox,
   E8TAxisProd0113GraphWholeC.qJetBox,
   E8TAxisProd0113GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨742209052284541494983671221773562890001284070, 742209052284541494983671221773575721112435624⟩
  | 0, 2 => ⟨2926153882543984014489324641027988776514182427, 2926153882543984014489324641028022266589154110⟩
  | 1, 1 => ⟨2984582074062997930124691625008238646805498286, 2984582074062997930124691625008290455631174858⟩
  | 0, 3 => ⟨7594859045416984046999793893125059342295151494, 7594859045416984046999793893125152087181391735⟩
  | 1, 2 => ⟨10804895981648577466693738905840048548259640037, 10804895981648577466693738905840193804810074053⟩
  | 2, 1 => ⟨10992655312776546095131396984012433333877991769, 10992655312776546095131396984012677134428163208⟩
  | 0, 4 => ⟨16309831910038631275561369104377800523256304251, 16309831910038631275561369104378076366831274291⟩
  | 1, 3 => ⟨26461495326674936988396052191863738642812351438, 26461495326674936988396052191864185571530988641⟩
  | 2, 2 => ⟨36755013200047956625598331019076559764838342592, 36755013200047956625598331019077327275383963695⟩
  | 3, 1 => ⟨37314144653290507700227946175251271570358920563, 37314144653290507700227946175252618728505153616⟩
  | 0, 5 => ⟨-135650865149724032758425228409907662780413603181355, 136682860747897721229709197119153301057646578123751⟩
  | 1, 4 => ⟨-260601702057189700341879410329995450140121698440056, 262062635117786481859997157281733593589196977575142⟩
  | 2, 3 => ⟨-501792842732458549814814931261985475375689839605101, 503828184658444259492336126180320547786882277561576⟩
  | 3, 2 => ⟨-967252389999516544376702667985009958253032148631770, 969909712113432347956671902781042793082549107466781⟩
  | 4, 1 => ⟨-1865408338560332955316013396996410343798970026279861, 1868261543965004809419212632766663071814229116575125⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0113Geometry.ds, E8TAxisProd0113Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 558675349926949813838996554342748217221693332 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0113CertifiedArithmetic
