import GeneralCK.Certificates.E8TAxisZero0027GraphCenterA
import GeneralCK.Certificates.E8TAxisZero0027GraphCenterB
import GeneralCK.Certificates.E8TAxisZero0027GraphCenterC
import GeneralCK.Certificates.E8TAxisZero0027GraphCenterD
import GeneralCK.Certificates.E8TAxisZero0027GraphWholeA
import GeneralCK.Certificates.E8TAxisZero0027GraphWholeB
import GeneralCK.Certificates.E8TAxisZero0027GraphWholeC
import GeneralCK.Certificates.E8TAxisZero0027GraphWholeD
import GeneralCK.Certificates.E8TAxisRegularInverseBoxes
import GeneralCK.Certificates.E8TAxisZero0027Geometry
import GeneralCK.Certificates.E8TAxisRegularCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisZero0027CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisRegularCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisZero0027GraphCenterA.qJetBox,
   E8TAxisZero0027GraphCenterB.qJetBox,
   E8TAxisZero0027GraphCenterC.qJetBox,
   E8TAxisZero0027GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisZero0027GraphWholeA.qJetBox,
   E8TAxisZero0027GraphWholeB.qJetBox,
   E8TAxisZero0027GraphWholeC.qJetBox,
   E8TAxisZero0027GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨12412894863566379130638699429038911948837853, 12412894863566379130638699429041151763521902⟩
  | 0, 2 => ⟨80027260312646603412330335488934668912638462, 80027260312646603412330335488940321097798514⟩
  | 1, 1 => ⟨80416194821700679825829079146168129036653996, 80416194821700679825829079146176183174393930⟩
  | 0, 3 => ⟨284202126138560269726605849966240179703822612, 284202126138560269726605849967928779042768715⟩
  | 1, 2 => ⟨440630547028074712800212457232196211738296524, 440630547028074712800212457232215068476355189⟩
  | 2, 1 => ⟨442340702760400121104154102632292321504453697, 442340702760400121104154102632321281820050097⟩
  | 0, 4 => ⟨671838660218457209666203409718466850963764284, 671838660218457209666203419107130863289044048⟩
  | 1, 3 => ⟨1356910027475396123280352314371829322870854068, 1356910027475396123280352314374076924566891899⟩
  | 2, 2 => ⟨2044096382308115293975050126268973633166013125, 2044096382308115293975050126269055592896905745⟩
  | 3, 1 => ⟨2050345458293221502613721483596127070282668460, 2050345458293221502613721483596260430442413253⟩
  | 0, 5 => ⟨-7428292802558852074991964899501201770785051568531, 7475381671830414576972435925158598310327461709817⟩
  | 1, 4 => ⟨-13488247998589772302009427849590302183709212648993, 13513472806764683660058535351138694634880548409201⟩
  | 2, 3 => ⟨-24670015693188280348024725124403479486722869218812, 24666695081570351426713629439087766216893119427555⟩
  | 3, 2 => ⟨-45213403318515842780939135946113452777653677132391, 45185087192118097958532541175886102444356987159088⟩
  | 4, 1 => ⟨-82794499021521921968526566609471987438762598979995, 82782243147612390186104714524067282136538811681018⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisZero0027Geometry.ds, E8TAxisZero0027Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 5531832160278881868373820864777301920661859 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsRegularAt s t) :
    data.CenterEnclosed (mixed E8TAxisRegularGermJet.regularQJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_regular_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_regular_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_regular_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_regular_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_regular_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_regular_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_regular_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_regular_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_regular_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_regular_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsRegularAt s t) :
    data.RemainderEnclosed (mixed E8TAxisRegularGermJet.regularQJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_regular_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_regular_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_regular_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_regular_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_regular_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisZero0027CertifiedArithmetic
