import GeneralCK.Certificates.E8TAxisFirstCellInverseCoverage
import GeneralCK.Certificates.E8TAxisProd0326Geometry
import GeneralCK.Certificates.E8TAxisProd0326PaddedInputs

/-!
# Endpoint certificates for all eight padded first-cell inverse brackets

Generated by `scripts/e8_taxis_emit_endpoint_witnesses.py`.
All primitive checks, scalar graph identities, and target comparisons
are checked separately. Coverage follows from the intermediate value theorem.
The exact lower cell boundaries are those in `E8TAxisProd0326Geometry`.
-/

namespace GeneralCK.Certificates.E8TAxisProd0326EndpointWitnesses

open Set DyadicInterval E8TAxisStableInterval E8TAxisStableScalar
open E8TAxisFirstCellInverseCoverage E8TAxisProd0326Geometry

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

def precision : ℕ := 160
def endpointLogTwo : DyadicInterval precision := ⟨1013035739299659071135698605846798551586536899314, 1013035739299659071135698605846798551586536899589⟩
def fastLogWitness : FastLogBoxWitness := ⟨0, 128, 0, 128⟩

theorem endpointLogTwo_checked :
    logBoxCheck (ofInt precision 2) endpointLogTwo fastLogWitness = true := by decide +kernel

def centerALowerAlpha : DyadicInterval precision := ⟨3324030191359282881556817859241043973740922234, 3324030191359282881556817859241043973740922234⟩
def centerALowerExp : DyadicInterval precision := ⟨1454868674354870198336951421367206719759440088169, 1454868674354870198336951421367206719759440090218⟩
def centerALowerLog : DyadicInterval precision := ⟨1009715489181788885783740077569471417172847648668, 1009715489181788885783740077569471417172847649961⟩
def centerALowerYBox : DyadicInterval precision := ⟨19182208989968100801423363429401214632983734910, 19182208989968100801423363429401214632983737952⟩
def centerALowerInput : Inputs precision :=
  ⟨centerALowerAlpha, centerALowerExp, centerALowerLog, endpointLogTwo⟩
def centerALowerExpWitness : ExpWitness precision :=
  ⟨1454868674354870198336951421367206719759440088169, scale precision, 1454868674354870198336951421367206719759440090218, scale precision,
    0, 128, 0, 128, ⟨-6648060382718565763113635718482087947481845753, -6648060382718565763113635718482087947481845486⟩, ⟨-6648060382718565763113635718482087947481843693, -6648060382718565763113635718482087947481843426⟩⟩

theorem centerALower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerALowerAlpha) centerALowerExp centerALowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerALowerExp) centerALowerLog fastLogWitness = true := by decide +kernel

theorem centerALower_denominators : DenominatorsPositive centerALowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerALower_yBox_eq : (yBox centerALowerInput).d0 = centerALowerYBox := by decide +kernel

theorem centerALower_contains :
    centerALowerYBox.Contains (Y (lower E8TAxisProd0326PaddedInputs.centerAInput.alpha)) := by
  rw [← centerALower_yBox_eq]
  apply checked_yBox_d0_contains centerALower_primitive_checks.1
    centerALower_primitive_checks.2 endpointLogTwo_checked centerALower_denominators
  exact point_contains precision 3324030191359282881556817859241043973740922234

def centerAUpperAlpha : DyadicInterval precision := ⟨3324030191359282881556817859241043973741053307, 3324030191359282881556817859241043973741053307⟩
def centerAUpperExp : DyadicInterval precision := ⟨1454868674354870198336951421367206719759439827213, 1454868674354870198336951421367206719759439829262⟩
def centerAUpperLog : DyadicInterval precision := ⟨1009715489181788885783740077569471417172847517894, 1009715489181788885783740077569471417172847519185⟩
def centerAUpperYBox : DyadicInterval precision := ⟨19182208989968100801423363429401214632984491301, 19182208989968100801423363429401214632984494339⟩
def centerAUpperInput : Inputs precision :=
  ⟨centerAUpperAlpha, centerAUpperExp, centerAUpperLog, endpointLogTwo⟩
def centerAUpperExpWitness : ExpWitness precision :=
  ⟨1454868674354870198336951421367206719759439827213, scale precision, 1454868674354870198336951421367206719759439829262, scale precision,
    0, 128, 0, 128, ⟨-6648060382718565763113635718482087947482107897, -6648060382718565763113635718482087947482107632⟩, ⟨-6648060382718565763113635718482087947482105839, -6648060382718565763113635718482087947482105574⟩⟩

theorem centerAUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerAUpperAlpha) centerAUpperExp centerAUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerAUpperExp) centerAUpperLog fastLogWitness = true := by decide +kernel

theorem centerAUpper_denominators : DenominatorsPositive centerAUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerAUpper_yBox_eq : (yBox centerAUpperInput).d0 = centerAUpperYBox := by decide +kernel

theorem centerAUpper_contains :
    centerAUpperYBox.Contains (Y (upper E8TAxisProd0326PaddedInputs.centerAInput.alpha)) := by
  rw [← centerAUpper_yBox_eq]
  apply checked_yBox_d0_contains centerAUpper_primitive_checks.1
    centerAUpper_primitive_checks.2 endpointLogTwo_checked centerAUpper_denominators
  exact point_contains precision 3324030191359282881556817859241043973741053307

def centerBLowerAlpha : DyadicInterval precision := ⟨1779069064604852499668366947178498976076001593780, 1779069064604852499668366947178498976076001593780⟩
def centerBLowerExp : DyadicInterval precision := ⟨128078428938362310091888017588710580459722341386, 128078428938362310091888017588710580459722343435⟩
def centerBLowerLog : DyadicInterval precision := ⟨122774097176940007287474385286924841569284109744, 122774097176940007287474385286924841569284111893⟩
def centerBLowerYBox : DyadicInterval precision := ⟨7703483786518856100419235022945483028917691685339, 7703483786518856100419235022945483028917691789992⟩
def centerBLowerInput : Inputs precision :=
  ⟨centerBLowerAlpha, centerBLowerExp, centerBLowerLog, endpointLogTwo⟩
def centerBLowerExpWitness : ExpWitness precision :=
  ⟨128078428938362310091888017588710580459722341386, scale precision, 128078428938362310091888017588710580459722343435, scale precision,
    3, 128, 3, 128,
    ⟨-3558138129209704999336733894356997952152003200156, -3558138129209704999336733894356997952152003199068⟩, ⟨-3558138129209704999336733894356997952152003176772, -3558138129209704999336733894356997952152003175686⟩⟩

theorem centerBLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerBLowerAlpha) centerBLowerExp centerBLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerBLowerExp) centerBLowerLog fastLogWitness = true := by decide +kernel

theorem centerBLower_denominators : DenominatorsPositive centerBLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerBLower_yBox_eq : (yBox centerBLowerInput).d0 = centerBLowerYBox := by decide +kernel

theorem centerBLower_contains :
    centerBLowerYBox.Contains (Y (lower E8TAxisProd0326PaddedInputs.centerBInput.alpha)) := by
  rw [← centerBLower_yBox_eq]
  apply checked_yBox_d0_contains centerBLower_primitive_checks.1
    centerBLower_primitive_checks.2 endpointLogTwo_checked centerBLower_denominators
  exact point_contains precision 1779069064604852499668366947178498976076001593780

def centerBUpperAlpha : DyadicInterval precision := ⟨1779069064604852499668366947178498976076001724853, 1779069064604852499668366947178498976076001724853⟩
def centerBUpperExp : DyadicInterval precision := ⟨128078428938362310091888017588710580459722318413, 128078428938362310091888017588710580459722320462⟩
def centerBUpperLog : DyadicInterval precision := ⟨122774097176940007287474385286924841569284088620, 122774097176940007287474385286924841569284090771⟩
def centerBUpperYBox : DyadicInterval precision := ⟨7703483786518856100419235022945483028917692086308, 7703483786518856100419235022945483028917692190963⟩
def centerBUpperInput : Inputs precision :=
  ⟨centerBUpperAlpha, centerBUpperExp, centerBUpperLog, endpointLogTwo⟩
def centerBUpperExpWitness : ExpWitness precision :=
  ⟨128078428938362310091888017588710580459722318413, scale precision, 128078428938362310091888017588710580459722320462, scale precision,
    3, 128, 3, 128,
    ⟨-3558138129209704999336733894356997952152003462300, -3558138129209704999336733894356997952152003461212⟩, ⟨-3558138129209704999336733894356997952152003438918, -3558138129209704999336733894356997952152003437832⟩⟩

theorem centerBUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerBUpperAlpha) centerBUpperExp centerBUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerBUpperExp) centerBUpperLog fastLogWitness = true := by decide +kernel

theorem centerBUpper_denominators : DenominatorsPositive centerBUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerBUpper_yBox_eq : (yBox centerBUpperInput).d0 = centerBUpperYBox := by decide +kernel

theorem centerBUpper_contains :
    centerBUpperYBox.Contains (Y (upper E8TAxisProd0326PaddedInputs.centerBInput.alpha)) := by
  rw [← centerBUpper_yBox_eq]
  apply checked_yBox_d0_contains centerBUpper_primitive_checks.1
    centerBUpper_primitive_checks.2 endpointLogTwo_checked centerBUpper_denominators
  exact point_contains precision 1779069064604852499668366947178498976076001724853

def centerCLowerAlpha : DyadicInterval precision := ⟨726138401848208530510351953917022565035490228664, 726138401848208530510351953917022565035490228664⟩
def centerCLowerExp : DyadicInterval precision := ⟨541060764918498579022071367606480126922644272324, 541060764918498579022071367606480126922644274373⟩
def centerCLowerLog : DyadicInterval precision := ⟨460319138626403000604377013164127066268799094846, 460319138626403000604377013164127066268799096613⟩
def centerCLowerYBox : DyadicInterval precision := ⟨3861332997754412100610329193187442121775337712745, 3861332997754412100610329193187442121775337740061⟩
def centerCLowerInput : Inputs precision :=
  ⟨centerCLowerAlpha, centerCLowerExp, centerCLowerLog, endpointLogTwo⟩
def centerCLowerExpWitness : ExpWitness precision :=
  ⟨541060764918498579022071367606480126922644272324, scale precision, 541060764918498579022071367606480126922644274373, scale precision,
    1, 128, 1, 128,
    ⟨-1452276803696417061020703907834045130070980460550, -1452276803696417061020703907834045130070980460010⟩, ⟨-1452276803696417061020703907834045130070980455018, -1452276803696417061020703907834045130070980454478⟩⟩

theorem centerCLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerCLowerAlpha) centerCLowerExp centerCLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerCLowerExp) centerCLowerLog fastLogWitness = true := by decide +kernel

theorem centerCLower_denominators : DenominatorsPositive centerCLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerCLower_yBox_eq : (yBox centerCLowerInput).d0 = centerCLowerYBox := by decide +kernel

theorem centerCLower_contains :
    centerCLowerYBox.Contains (Y (lower E8TAxisProd0326PaddedInputs.centerCInput.alpha)) := by
  rw [← centerCLower_yBox_eq]
  apply checked_yBox_d0_contains centerCLower_primitive_checks.1
    centerCLower_primitive_checks.2 endpointLogTwo_checked centerCLower_denominators
  exact point_contains precision 726138401848208530510351953917022565035490228664

def centerCUpperAlpha : DyadicInterval precision := ⟨726138401848208530510351953917022565035490359737, 726138401848208530510351953917022565035490359737⟩
def centerCUpperExp : DyadicInterval precision := ⟨541060764918498579022071367606480126922644175276, 541060764918498579022071367606480126922644177325⟩
def centerCUpperLog : DyadicInterval precision := ⟨460319138626403000604377013164127066268799024020, 460319138626403000604377013164127066268799025783⟩
def centerCUpperYBox : DyadicInterval precision := ⟨3861332997754412100610329193187442121775338312291, 3861332997754412100610329193187442121775338339590⟩
def centerCUpperInput : Inputs precision :=
  ⟨centerCUpperAlpha, centerCUpperExp, centerCUpperLog, endpointLogTwo⟩
def centerCUpperExpWitness : ExpWitness precision :=
  ⟨541060764918498579022071367606480126922644175276, scale precision, 541060764918498579022071367606480126922644177325, scale precision,
    1, 128, 1, 128,
    ⟨-1452276803696417061020703907834045130070980722696, -1452276803696417061020703907834045130070980722156⟩, ⟨-1452276803696417061020703907834045130070980717160, -1452276803696417061020703907834045130070980716622⟩⟩

theorem centerCUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerCUpperAlpha) centerCUpperExp centerCUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerCUpperExp) centerCUpperLog fastLogWitness = true := by decide +kernel

theorem centerCUpper_denominators : DenominatorsPositive centerCUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerCUpper_yBox_eq : (yBox centerCUpperInput).d0 = centerCUpperYBox := by decide +kernel

theorem centerCUpper_contains :
    centerCUpperYBox.Contains (Y (upper E8TAxisProd0326PaddedInputs.centerCInput.alpha)) := by
  rw [← centerCUpper_yBox_eq]
  apply checked_yBox_d0_contains centerCUpper_primitive_checks.1
    centerCUpper_primitive_checks.2 endpointLogTwo_checked centerCUpper_denominators
  exact point_contains precision 726138401848208530510351953917022565035490359737

def centerDLowerAlpha : DyadicInterval precision := ⟨721949241039261777105100229686264310385356095911, 721949241039261777105100229686264310385356095911⟩
def centerDLowerExp : DyadicInterval precision := ⟨544171400918647169539408046331758483299738784778, 544171400918647169539408046331758483299738786827⟩
def centerDLowerLog : DyadicInterval precision := ⟨462587568506596564045749998967475931231927985916, 462587568506596564045749998967475931231927987671⟩
def centerDLowerYBox : DyadicInterval precision := ⟨3842150788764443999808905829758040907142353597592, 3842150788764443999808905829758040907142353624675⟩
def centerDLowerInput : Inputs precision :=
  ⟨centerDLowerAlpha, centerDLowerExp, centerDLowerLog, endpointLogTwo⟩
def centerDLowerExpWitness : ExpWitness precision :=
  ⟨544171400918647169539408046331758483299738784778, scale precision, 544171400918647169539408046331758483299738786827, scale precision,
    1, 128, 1, 128,
    ⟨-1443898482078523554210200459372528620770712195030, -1443898482078523554210200459372528620770712194490⟩, ⟨-1443898482078523554210200459372528620770712189526, -1443898482078523554210200459372528620770712188986⟩⟩

theorem centerDLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerDLowerAlpha) centerDLowerExp centerDLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerDLowerExp) centerDLowerLog fastLogWitness = true := by decide +kernel

theorem centerDLower_denominators : DenominatorsPositive centerDLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerDLower_yBox_eq : (yBox centerDLowerInput).d0 = centerDLowerYBox := by decide +kernel

theorem centerDLower_contains :
    centerDLowerYBox.Contains (Y (lower E8TAxisProd0326PaddedInputs.centerDInput.alpha)) := by
  rw [← centerDLower_yBox_eq]
  apply checked_yBox_d0_contains centerDLower_primitive_checks.1
    centerDLower_primitive_checks.2 endpointLogTwo_checked centerDLower_denominators
  exact point_contains precision 721949241039261777105100229686264310385356095911

def centerDUpperAlpha : DyadicInterval precision := ⟨721949241039261777105100229686264310385356226984, 721949241039261777105100229686264310385356226984⟩
def centerDUpperExp : DyadicInterval precision := ⟨544171400918647169539408046331758483299738687171, 544171400918647169539408046331758483299738689220⟩
def centerDUpperLog : DyadicInterval precision := ⟨462587568506596564045749998967475931231927914790, 462587568506596564045749998967475931231927916547⟩
def centerDUpperYBox : DyadicInterval precision := ⟨3842150788764443999808905829758040907142354198408, 3842150788764443999808905829758040907142354225514⟩
def centerDUpperInput : Inputs precision :=
  ⟨centerDUpperAlpha, centerDUpperExp, centerDUpperLog, endpointLogTwo⟩
def centerDUpperExpWitness : ExpWitness precision :=
  ⟨544171400918647169539408046331758483299738687171, scale precision, 544171400918647169539408046331758483299738689220, scale precision,
    1, 128, 1, 128,
    ⟨-1443898482078523554210200459372528620770712457176, -1443898482078523554210200459372528620770712456636⟩, ⟨-1443898482078523554210200459372528620770712451674, -1443898482078523554210200459372528620770712451134⟩⟩

theorem centerDUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerDUpperAlpha) centerDUpperExp centerDUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerDUpperExp) centerDUpperLog fastLogWitness = true := by decide +kernel

theorem centerDUpper_denominators : DenominatorsPositive centerDUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerDUpper_yBox_eq : (yBox centerDUpperInput).d0 = centerDUpperYBox := by decide +kernel

theorem centerDUpper_contains :
    centerDUpperYBox.Contains (Y (upper E8TAxisProd0326PaddedInputs.centerDInput.alpha)) := by
  rw [← centerDUpper_yBox_eq]
  apply checked_yBox_d0_contains centerDUpper_primitive_checks.1
    centerDUpper_primitive_checks.2 endpointLogTwo_checked centerDUpper_denominators
  exact point_contains precision 721949241039261777105100229686264310385356226984

def wholeALowerAlpha : DyadicInterval precision := ⟨3165742448647063503620071141085134670978008272, 3165742448647063503620071141085134670978008272⟩
def wholeALowerExp : DyadicInterval precision := ⟨1455183847209450510423929547351191476681365553877, 1455183847209450510423929547351191476681365555926⟩
def wholeALowerLog : DyadicInterval precision := ⟨1009873425488092576137085252579843091174878184430, 1009873425488092576137085252579843091174878185731⟩
def wholeALowerYBox : DyadicInterval precision := ⟨18268770466636286477546060408953537745698777077, 18268770466636286477546060408953537745698780110⟩
def wholeALowerInput : Inputs precision :=
  ⟨wholeALowerAlpha, wholeALowerExp, wholeALowerLog, endpointLogTwo⟩
def wholeALowerExpWitness : ExpWitness precision :=
  ⟨1455183847209450510423929547351191476681365553877, scale precision, 1455183847209450510423929547351191476681365555926, scale precision,
    0, 128, 0, 128, ⟨-6331484897294127007240142282170269341956017827, -6331484897294127007240142282170269341956017562⟩, ⟨-6331484897294127007240142282170269341956015769, -6331484897294127007240142282170269341956015504⟩⟩

theorem wholeALower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeALowerAlpha) wholeALowerExp wholeALowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeALowerExp) wholeALowerLog fastLogWitness = true := by decide +kernel

theorem wholeALower_denominators : DenominatorsPositive wholeALowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeALower_yBox_eq : (yBox wholeALowerInput).d0 = wholeALowerYBox := by decide +kernel

theorem wholeALower_contains :
    wholeALowerYBox.Contains (Y (lower E8TAxisProd0326PaddedInputs.wholeAInput.alpha)) := by
  rw [← wholeALower_yBox_eq]
  apply checked_yBox_d0_contains wholeALower_primitive_checks.1
    wholeALower_primitive_checks.2 endpointLogTwo_checked wholeALower_denominators
  exact point_contains precision 3165742448647063503620071141085134670978008272

def wholeAUpperAlpha : DyadicInterval precision := ⟨3482318024844347500022322904444928295572460789, 3482318024844347500022322904444928295572460789⟩
def wholeAUpperExp : DyadicInterval precision := ⟨1454553569581723058392238696431353225219181165402, 1454553569581723058392238696431353225219181167451⟩
def wholeAUpperLog : DyadicInterval precision := ⟨1009557569928173087760872372803888450927165221654, 1009557569928173087760872372803888450927165222941⟩
def wholeAUpperYBox : DyadicInterval precision := ⟨20095647513299915125300666449848891520269449140, 20095647513299915125300666449848891520269452179⟩
def wholeAUpperInput : Inputs precision :=
  ⟨wholeAUpperAlpha, wholeAUpperExp, wholeAUpperLog, endpointLogTwo⟩
def wholeAUpperExpWitness : ExpWitness precision :=
  ⟨1454553569581723058392238696431353225219181165402, scale precision, 1454553569581723058392238696431353225219181167451, scale precision,
    0, 128, 0, 128, ⟨-6964636049688695000044645808889856591144922861, -6964636049688695000044645808889856591144922596⟩, ⟨-6964636049688695000044645808889856591144920803, -6964636049688695000044645808889856591144920538⟩⟩

theorem wholeAUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeAUpperAlpha) wholeAUpperExp wholeAUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeAUpperExp) wholeAUpperLog fastLogWitness = true := by decide +kernel

theorem wholeAUpper_denominators : DenominatorsPositive wholeAUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeAUpper_yBox_eq : (yBox wholeAUpperInput).d0 = wholeAUpperYBox := by decide +kernel

theorem wholeAUpper_contains :
    wholeAUpperYBox.Contains (Y (upper E8TAxisProd0326PaddedInputs.wholeAInput.alpha)) := by
  rw [← wholeAUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeAUpper_primitive_checks.1
    wholeAUpper_primitive_checks.2 endpointLogTwo_checked wholeAUpper_denominators
  exact point_contains precision 3482318024844347500022322904444928295572460789

def wholeBLowerAlpha : DyadicInterval precision := ⟨1761630872613749578315223637688046152944331337622, 1761630872613749578315223637688046152944331337622⟩
def wholeBLowerExp : DyadicInterval precision := ⟨131171574157568086265269840137981127047213743043, 131171574157568086265269840137981127047213745092⟩
def wholeBLowerLog : DyadicInterval precision := ⟨125615252692523699847363260387482010240479932278, 125615252692523699847363260387482010240479934421⟩
def wholeBLowerYBox : DyadicInterval precision := ⟨7650047632903944962472412796249293931011521652120, 7650047632903944962472412796249293931011521754649⟩
def wholeBLowerInput : Inputs precision :=
  ⟨wholeBLowerAlpha, wholeBLowerExp, wholeBLowerLog, endpointLogTwo⟩
def wholeBLowerExpWitness : ExpWitness precision :=
  ⟨131171574157568086265269840137981127047213743043, scale precision, 131171574157568086265269840137981127047213745092, scale precision,
    3, 128, 3, 128,
    ⟨-3523261745227499156630447275376092305888662687564, -3523261745227499156630447275376092305888662686470⟩, ⟨-3523261745227499156630447275376092305888662664730, -3523261745227499156630447275376092305888662663640⟩⟩

theorem wholeBLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeBLowerAlpha) wholeBLowerExp wholeBLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeBLowerExp) wholeBLowerLog fastLogWitness = true := by decide +kernel

theorem wholeBLower_denominators : DenominatorsPositive wholeBLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeBLower_yBox_eq : (yBox wholeBLowerInput).d0 = wholeBLowerYBox := by decide +kernel

theorem wholeBLower_contains :
    wholeBLowerYBox.Contains (Y (lower E8TAxisProd0326PaddedInputs.wholeBInput.alpha)) := by
  rw [← wholeBLower_yBox_eq]
  apply checked_yBox_d0_contains wholeBLower_primitive_checks.1
    wholeBLower_primitive_checks.2 endpointLogTwo_checked wholeBLower_denominators
  exact point_contains precision 1761630872613749578315223637688046152944331337622

def wholeBUpperAlpha : DyadicInterval precision := ⟨1796565156237215979596483990466467059040684599423, 1796565156237215979596483990466467059040684599423⟩
def wholeBUpperExp : DyadicInterval precision := ⟨125048314545172815726990485764531018194949478365, 125048314545172815726990485764531018194949480414⟩
def wholeBUpperLog : DyadicInterval precision := ⟨119985471733263886206512940327500586392572025492, 119985471733263886206512940327500586392572027643⟩
def wholeBUpperYBox : DyadicInterval precision := ⟨7756919940133767238366057249641672126823862118203, 7756919940133767238366057249641672126823862224986⟩
def wholeBUpperInput : Inputs precision :=
  ⟨wholeBUpperAlpha, wholeBUpperExp, wholeBUpperLog, endpointLogTwo⟩
def wholeBUpperExpWitness : ExpWitness precision :=
  ⟨125048314545172815726990485764531018194949478365, scale precision, 125048314545172815726990485764531018194949480414, scale precision,
    3, 128, 3, 128,
    ⟨-3593130312474431959192967980932934118081369211718, -3593130312474431959192967980932934118081369210628⟩, ⟨-3593130312474431959192967980932934118081369187774, -3593130312474431959192967980932934118081369186682⟩⟩

theorem wholeBUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeBUpperAlpha) wholeBUpperExp wholeBUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeBUpperExp) wholeBUpperLog fastLogWitness = true := by decide +kernel

theorem wholeBUpper_denominators : DenominatorsPositive wholeBUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeBUpper_yBox_eq : (yBox wholeBUpperInput).d0 = wholeBUpperYBox := by decide +kernel

theorem wholeBUpper_contains :
    wholeBUpperYBox.Contains (Y (upper E8TAxisProd0326PaddedInputs.wholeBInput.alpha)) := by
  rw [← wholeBUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeBUpper_primitive_checks.1
    wholeBUpper_primitive_checks.2 endpointLogTwo_checked wholeBUpper_denominators
  exact point_contains precision 1796565156237215979596483990466467059040684599423

def wholeCLowerAlpha : DyadicInterval precision := ⟨720206400288607958471211247095533072076427847162, 720206400288607958471211247095533072076427847162⟩
def wholeCLowerExp : DyadicInterval precision := ⟨545470798661596717495093304191272546428016601859, 545470798661596717495093304191272546428016603908⟩
def wholeCLowerLog : DyadicInterval precision := ⟨463534112130964182759725604875119319315296977200, 463534112130964182759725604875119319315296978963⟩
def wholeCLowerYBox : DyadicInterval precision := ⟨3834158201685290624474979428329123734378610216246, 3834158201685290624474979428329123734378610243295⟩
def wholeCLowerInput : Inputs precision :=
  ⟨wholeCLowerAlpha, wholeCLowerExp, wholeCLowerLog, endpointLogTwo⟩
def wholeCLowerExpWitness : ExpWitness precision :=
  ⟨545470798661596717495093304191272546428016601859, scale precision, 545470798661596717495093304191272546428016603908, scale precision,
    1, 128, 1, 128,
    ⟨-1440412800577215916942422494191066144152855697528, -1440412800577215916942422494191066144152855696984⟩, ⟨-1440412800577215916942422494191066144152855692038, -1440412800577215916942422494191066144152855691494⟩⟩

theorem wholeCLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeCLowerAlpha) wholeCLowerExp wholeCLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeCLowerExp) wholeCLowerLog fastLogWitness = true := by decide +kernel

theorem wholeCLower_denominators : DenominatorsPositive wholeCLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeCLower_yBox_eq : (yBox wholeCLowerInput).d0 = wholeCLowerYBox := by decide +kernel

theorem wholeCLower_contains :
    wholeCLowerYBox.Contains (Y (lower E8TAxisProd0326PaddedInputs.wholeCInput.alpha)) := by
  rw [← wholeCLower_yBox_eq]
  apply checked_yBox_d0_contains wholeCLower_primitive_checks.1
    wholeCLower_primitive_checks.2 endpointLogTwo_checked wholeCLower_denominators
  exact point_contains precision 720206400288607958471211247095533072076427847162

def wholeCUpperAlpha : DyadicInterval precision := ⟨732088450015273885412168945467779610187390603300, 732088450015273885412168945467779610187390603300⟩
def wholeCUpperExp : DyadicInterval precision := ⟨536673131676134175886659866352304690628134468275, 536673131676134175886659866352304690628134470324⟩
def wholeCUpperLog : DyadicInterval precision := ⟨457113461540330669166646829324555652977734579362, 457113461540330669166646829324555652977734581129⟩
def wholeCUpperYBox : DyadicInterval precision := ⟨3888507793823533576745678958045760509172065806961, 3888507793823533576745678958045760509172065834527⟩
def wholeCUpperInput : Inputs precision :=
  ⟨wholeCUpperAlpha, wholeCUpperExp, wholeCUpperLog, endpointLogTwo⟩
def wholeCUpperExpWitness : ExpWitness precision :=
  ⟨536673131676134175886659866352304690628134468275, scale precision, 536673131676134175886659866352304690628134470324, scale precision,
    1, 128, 1, 128,
    ⟨-1464176900030547770824337890935559220374781209842, -1464176900030547770824337890935559220374781209302⟩, ⟨-1464176900030547770824337890935559220374781204264, -1464176900030547770824337890935559220374781203724⟩⟩

theorem wholeCUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeCUpperAlpha) wholeCUpperExp wholeCUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeCUpperExp) wholeCUpperLog fastLogWitness = true := by decide +kernel

theorem wholeCUpper_denominators : DenominatorsPositive wholeCUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeCUpper_yBox_eq : (yBox wholeCUpperInput).d0 = wholeCUpperYBox := by decide +kernel

theorem wholeCUpper_contains :
    wholeCUpperYBox.Contains (Y (upper E8TAxisProd0326PaddedInputs.wholeCInput.alpha)) := by
  rw [← wholeCUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeCUpper_primitive_checks.1
    wholeCUpper_primitive_checks.2 endpointLogTwo_checked wholeCUpper_denominators
  exact point_contains precision 732088450015273885412168945467779610187390603300

def wholeDLowerAlpha : DyadicInterval precision := ⟨716228578308099727358082939138935890959899146958, 716228578308099727358082939138935890959899146958⟩
def wholeDLowerExp : DyadicInterval precision := ⟨548448150163327086956497611001597702787279804515, 548448150163327086956497611001597702787279806564⟩
def wholeDLowerLog : DyadicInterval precision := ⟨465700648921796470149242465934935276152315890924, 465700648921796470149242465934935276152315892677⟩
def wholeDLowerYBox : DyadicInterval precision := ⟨3815889431218654337997433367920170196632911058952, 3815889431218654337997433367920170196632911085788⟩
def wholeDLowerInput : Inputs precision :=
  ⟨wholeDLowerAlpha, wholeDLowerExp, wholeDLowerLog, endpointLogTwo⟩
def wholeDLowerExpWitness : ExpWitness precision :=
  ⟨548448150163327086956497611001597702787279804515, scale precision, 548448150163327086956497611001597702787279806564, scale precision,
    1, 128, 1, 128,
    ⟨-1432457156616199454716165878277871781919798297100, -1432457156616199454716165878277871781919798296560⟩, ⟨-1432457156616199454716165878277871781919798291640, -1432457156616199454716165878277871781919798291100⟩⟩

theorem wholeDLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeDLowerAlpha) wholeDLowerExp wholeDLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeDLowerExp) wholeDLowerLog fastLogWitness = true := by decide +kernel

theorem wholeDLower_denominators : DenominatorsPositive wholeDLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeDLower_yBox_eq : (yBox wholeDLowerInput).d0 = wholeDLowerYBox := by decide +kernel

theorem wholeDLower_contains :
    wholeDLowerYBox.Contains (Y (lower E8TAxisProd0326PaddedInputs.wholeDInput.alpha)) := by
  rw [← wholeDLower_yBox_eq]
  apply checked_yBox_d0_contains wholeDLower_primitive_checks.1
    wholeDLower_primitive_checks.2 endpointLogTwo_checked wholeDLower_denominators
  exact point_contains precision 716228578308099727358082939138935890959899146958

def wholeDUpperAlpha : DyadicInterval precision := ⟨727686670816724440524685346233204921246428566225, 727686670816724440524685346233204921246428566225⟩
def wholeDUpperExp : DyadicInterval precision := ⟨539915612896337333160506278237532712175953638823, 539915612896337333160506278237532712175953640872⟩
def wholeDUpperLog : DyadicInterval precision := ⟨459483149562382791203438629890379327133729720586, 459483149562382791203438629890379327133729722347⟩
def wholeDUpperYBox : DyadicInterval precision := ⟨3868412146310233661620378291595911617651796735276, 3868412146310233661620378291595911617651796762631⟩
def wholeDUpperInput : Inputs precision :=
  ⟨wholeDUpperAlpha, wholeDUpperExp, wholeDUpperLog, endpointLogTwo⟩
def wholeDUpperExpWitness : ExpWitness precision :=
  ⟨539915612896337333160506278237532712175953638823, scale precision, 539915612896337333160506278237532712175953640872, scale precision,
    1, 128, 1, 128,
    ⟨-1455373341633448881049370692466409842492857135672, -1455373341633448881049370692466409842492857135134⟩, ⟨-1455373341633448881049370692466409842492857130124, -1455373341633448881049370692466409842492857129586⟩⟩

theorem wholeDUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeDUpperAlpha) wholeDUpperExp wholeDUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeDUpperExp) wholeDUpperLog fastLogWitness = true := by decide +kernel

theorem wholeDUpper_denominators : DenominatorsPositive wholeDUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeDUpper_yBox_eq : (yBox wholeDUpperInput).d0 = wholeDUpperYBox := by decide +kernel

theorem wholeDUpper_contains :
    wholeDUpperYBox.Contains (Y (upper E8TAxisProd0326PaddedInputs.wholeDInput.alpha)) := by
  rw [← wholeDUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeDUpper_primitive_checks.1
    wholeDUpper_primitive_checks.2 endpointLogTwo_checked wholeDUpper_denominators
  exact point_contains precision 727686670816724440524685346233204921246428566225

theorem centerA_covers_slope {s : ℝ} (hs : s ∈ Icc (centerT) (centerT)) :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.centerAInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerALower_contains centerAUpper_contains _ _ hs
  · norm_num [centerALowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerAUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerA_covers :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.centerAInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerT) :=
  centerA_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerB_covers_slope {s : ℝ} (hs : s ∈ Icc (2 * centerS + centerT) (2 * centerS + centerT)) :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.centerBInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerBLower_contains centerBUpper_contains _ _ hs
  · norm_num [centerBLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerBUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerB_covers :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.centerBInput.alpha.Contains a ∧
      0 < a ∧ Y a = (2 * centerS + centerT) :=
  centerB_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerC_covers_slope {s : ℝ} (hs : s ∈ Icc (centerS + centerT) (centerS + centerT)) :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.centerCInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerCLower_contains centerCUpper_contains _ _ hs
  · norm_num [centerCLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerCUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerC_covers :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.centerCInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerS + centerT) :=
  centerC_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerD_covers_slope {s : ℝ} (hs : s ∈ Icc (centerS) (centerS)) :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.centerDInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerDLower_contains centerDUpper_contains _ _ hs
  · norm_num [centerDLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerDUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerD_covers :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.centerDInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerS) :=
  centerD_covers_slope ⟨le_rfl, le_rfl⟩

theorem wholeA_covers_slope {s : ℝ} (hs : s ∈ Icc (tLower) (tUpper)) :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.wholeAInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeALower_contains wholeAUpper_contains _ _ hs
  · norm_num [wholeALowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeAUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeB_covers_slope {s : ℝ} (hs : s ∈ Icc (2 * sLower + tLower) (2 * sUpper + tUpper)) :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.wholeBInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeBLower_contains wholeBUpper_contains _ _ hs
  · norm_num [wholeBLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeBUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeC_covers_slope {s : ℝ} (hs : s ∈ Icc (sLower + tLower) (sUpper + tUpper)) :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.wholeCInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeCLower_contains wholeCUpper_contains _ _ hs
  · norm_num [wholeCLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeCUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeD_covers_slope {s : ℝ} (hs : s ∈ Icc (sLower) (sUpper)) :
    ∃ a : ℝ, E8TAxisProd0326PaddedInputs.wholeDInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeDLower_contains wholeDUpper_contains _ _ hs
  · norm_num [wholeDLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeDUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

#print axioms centerA_covers
#print axioms wholeA_covers_slope
#print axioms wholeB_covers_slope

end GeneralCK.Certificates.E8TAxisProd0326EndpointWitnesses
