import GeneralCK.Certificates.E8TAxisProd0320GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0320GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0320GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0320GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0320GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0320GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0320GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0320GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0320Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0320CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0320GraphCenterA.qJetBox,
   E8TAxisProd0320GraphCenterB.qJetBox,
   E8TAxisProd0320GraphCenterC.qJetBox,
   E8TAxisProd0320GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0320GraphWholeA.qJetBox,
   E8TAxisProd0320GraphWholeB.qJetBox,
   E8TAxisProd0320GraphWholeC.qJetBox,
   E8TAxisProd0320GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨27701379718010119011192140841028094313871983824, 27701379718010119011192140841028242910907646726⟩
  | 0, 2 => ⟨83032226433944152368764641267535643693837535231, 83032226433944152368764641267536217496287152151⟩
  | 1, 1 => ⟨83874936946956327113275941910821212335709942703, 83874936946956327113275941910822249155152507136⟩
  | 0, 3 => ⟨171216386765142039823003637400834054712204959711, 171216386765142039823003637400835927914303233636⟩
  | 1, 2 => ⟨230866768036364367299675774071194074482954940822, 230866768036364367299675774071197431743340892387⟩
  | 2, 1 => ⟨232919759259032767640664200154744694226138847091, 232919759259032767640664200154750802019991452457⟩
  | 0, 4 => ⟨292375847297366344793681716453697327266522678677, 292375847297366344793681716453703717433440482107⟩
  | 1, 3 => ⟨436432184940208071445604419139075591553510515377, 436432184940208071445604419139087200727007848552⟩
  | 2, 2 => ⟨581498884362629847282947292052475158771421603158, 581498884362629847282947292052496543665738615128⟩
  | 3, 1 => ⟨585995807969337230603800444711454662481960720799, 585995807969337230603800444711494373513191444072⟩
  | 0, 5 => ⟨-1291394322628128351791209731593273718062909082476781, 1298713850608731939938691325836412631334945849300392⟩
  | 1, 4 => ⟨-2527121901551450160965586566120604660507243627159824, 2538159661208636026345010913227469842404295897774239⟩
  | 2, 3 => ⟨-4950352965124950743744536566012591762579412329761310, 4966275238684266348650451355953175455610711377486426⟩
  | 3, 2 => ⟨-9703721389786049178993445545872481270125045392197718, 9724648509166640168113964956874043378105606041039869⟩
  | 4, 1 => ⟨-19031131138736010899649194427392778448736768310830790, 19052578888186731211450859494785741311907225316285080⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0320Geometry.ds, E8TAxisProd0320Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 26012707454364745424163313102171250657191018815 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0320CertifiedArithmetic
