import GeneralCK.Certificates.E8TAxisProd0255GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0255GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0255GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0255GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0255GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0255GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0255GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0255GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0255Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0255CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0255GraphCenterA.qJetBox,
   E8TAxisProd0255GraphCenterB.qJetBox,
   E8TAxisProd0255GraphCenterC.qJetBox,
   E8TAxisProd0255GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0255GraphWholeA.qJetBox,
   E8TAxisProd0255GraphWholeB.qJetBox,
   E8TAxisProd0255GraphWholeC.qJetBox,
   E8TAxisProd0255GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨70275439819156755194900993005416583453074126273, 70275439819156755194900993005416944877051514271⟩
  | 0, 2 => ⟨195538199480995527347228603216891251288859675444, 195538199480995527347228603216892747631616982700⟩
  | 1, 1 => ⟨196864404561158379950877209408617127413327518567, 196864404561158379950877209408619890300301057863⟩
  | 0, 3 => ⟨376202918526280702312638369117316491372603783989, 376202918526280702312638369117321546083940485958⟩
  | 1, 2 => ⟨502530960888955194501448545621389175627409457757, 502530960888955194501448545621398414995605673605⟩
  | 2, 1 => ⟨505547123378649402451901794593636123360563510094, 505547123378649402451901794593653194915238062825⟩
  | 0, 4 => ⟨605159105362129067459427167373620204014983184949, 605159105362129067459427167373638221894283082585⟩
  | 1, 3 => ⟨890799120256525594939376943467608227454689664092, 890799120256525594939376943467641488242993189187⟩
  | 2, 2 => ⟨1177831118416247693453541017198550325017648556369, 1177831118416247693453541017198612366592871825396⟩
  | 3, 1 => ⟨1184143848030480055564258543782875797623383740925, 1184143848030480055564258543782992339706671550670⟩
  | 0, 5 => ⟨-3525772201829812448333177183903561521876569075451582, 3542485108849279998156356523295985877257788626306644⟩
  | 1, 4 => ⟨-6930491630035889483907358847424011098671094458239410, 6955674671309339495591676647203738086645307254476495⟩
  | 2, 3 => ⟨-13635338357059685435726161211515925613758215753031441, 13671619585737478313591244180611604921588403884707143⟩
  | 3, 2 => ⟨-26843900842770065402738481197823561835614279784576992, 26891511093806147011621582720086210926955458207677237⟩
  | 4, 1 => ⟨-52875273108836830735405784284051994758926666705179744, 52923929194751173116913776889277146049519596854372325⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0255Geometry.ds, E8TAxisProd0255Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 66280648809261408595842934808494533156928480932 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0255CertifiedArithmetic
