import GeneralCK.Certificates.E8TAxisProd0458GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0458GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0458GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0458GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0458GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0458GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0458GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0458GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0458Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0458CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0458GraphCenterA.qJetBox,
   E8TAxisProd0458GraphCenterB.qJetBox,
   E8TAxisProd0458GraphCenterC.qJetBox,
   E8TAxisProd0458GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0458GraphWholeA.qJetBox,
   E8TAxisProd0458GraphWholeB.qJetBox,
   E8TAxisProd0458GraphWholeC.qJetBox,
   E8TAxisProd0458GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨17852163706380184197888973101804583383774784701, 17852163706380184197888973101804684824022479745⟩
  | 0, 2 => ⟨55394983583922558387040213191879982568667434519, 55394983583922558387040213191880359419771641234⟩
  | 1, 1 => ⟨56037190866086324508455027512658132233477198261, 56037190866086324508455027512658804786237319114⟩
  | 0, 3 => ⟨118094090167979860334379010116358241169875292993, 118094090167979860334379010116359453967252880418⟩
  | 1, 2 => ⟨160007469700439977730839111754620521450710489192, 160007469700439977730839111754622672204432859973⟩
  | 2, 1 => ⟨161630831325529150854551667868192220660872063056, 161630831325529150854551667868196103490658355641⟩
  | 0, 4 => ⟨208217831004438738595758057867578806683720097678, 208217831004438738595758057867582880693328963834⟩
  | 1, 3 => ⟨313114055575616464999770373274107833604475690430, 313114055575616464999770373274115173468240663819⟩
  | 2, 2 => ⟨418843959431968097874345708300619931987589231182, 418843959431968097874345708300633370332172525009⟩
  | 3, 1 => ⟨422510958874192572269299780816509148047771685373, 422510958874192572269299780816533966666290525556⟩
  | 0, 5 => ⟨-785714284256448816921339037394404343170990391449661, 790317032002136853867624750956647364411906458723935⟩
  | 1, 4 => ⟨-1533607198322498741373297741438050738355578350732784, 1540507922221441108015042448958008233366619322096856⟩
  | 2, 3 => ⟨-2996764004370149216375469588544883731508322255683790, 3006677509808466012692562528475599820307838389566562⟩
  | 3, 2 => ⟨-5860020900852893686718309291196969281762247296548361, 5873015690702195227102482018794548111796891760050063⟩
  | 4, 1 => ⟨-11464924468874115784272678765903932995850805460002124, 11478217854591474401372344436138842889069422529676208⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0458Geometry.ds, E8TAxisProd0458Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 16728755052192401665116676824408942598761174592 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0458CertifiedArithmetic
