import GeneralCK.Certificates.E8TAxisProd0252GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0252GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0252GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0252GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0252GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0252GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0252GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0252GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0252Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0252CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0252GraphCenterA.qJetBox,
   E8TAxisProd0252GraphCenterB.qJetBox,
   E8TAxisProd0252GraphCenterC.qJetBox,
   E8TAxisProd0252GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0252GraphWholeA.qJetBox,
   E8TAxisProd0252GraphWholeB.qJetBox,
   E8TAxisProd0252GraphWholeC.qJetBox,
   E8TAxisProd0252GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨77954345223909083517835136632037507174630856588, 77954345223909083517835136632037908114571940618⟩
  | 0, 2 => ⟨214890838359843627117135103885510125399951744075, 214890838359843627117135103885511795925080149408⟩
  | 1, 1 => ⟨216501153374037585647181144637989933417254977102, 216501153374037585647181144637993024044694917771⟩
  | 0, 3 => ⟨410315154093272865148400647573724802619260409171, 410315154093272865148400647573730465907354377707⟩
  | 1, 2 => ⟨547740817611113023892010763388000189729785094924, 547740817611113023892010763388010560930870445333⟩
  | 2, 1 => ⟨551379403906111667342754929818147626853125720425, 551379403906111667342754929818166819508128185487⟩
  | 0, 4 => ⟨656163976804948358339864385767773737116848399001, 656163976804948358339864385767794026161738189884⟩
  | 1, 3 => ⟨964696451332888076130368318987451296894262052578, 964696451332888076130368318987488807581020203467⟩
  | 2, 2 => ⟨1274899643789465105317222663177616638577098330085, 1274899643789465105317222663177686695725342650954⟩
  | 3, 1 => ⟨1282487432388794159430758566767817006091670874638, 1282487432388794159430758566767948760149081736462⟩
  | 0, 5 => ⟨-3901342311489481780840863220232847485969898273668177, 3919486466247391755098281775936689042146997729597803⟩
  | 1, 4 => ⟨-7671724729572794675097410803267456233781212226044477, 7699051039763573297127757182888382410852664315621012⟩
  | 2, 3 => ⟨-15099512211680826609389507987008217966094597140656144, 15138867900043114066124919481611216934033438180261080⟩
  | 3, 2 => ⟨-29737968203827459704620302513084621830661885901103270, 29789609763225563857493297733188291924315727284790748⟩
  | 4, 1 => ⟨-58598759818561267876307124847129409516351652109682283, 58651565048391897466807053519645705060087815412055398⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0252Geometry.ds, E8TAxisProd0252Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 73559914968985830229473321020142158361029753408 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0252CertifiedArithmetic
