import GeneralCK.Certificates.E8TAxisProd0463GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0463GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0463GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0463GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0463GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0463GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0463GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0463GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0463Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0463CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0463GraphCenterA.qJetBox,
   E8TAxisProd0463GraphCenterB.qJetBox,
   E8TAxisProd0463GraphCenterC.qJetBox,
   E8TAxisProd0463GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0463GraphWholeA.qJetBox,
   E8TAxisProd0463GraphWholeB.qJetBox,
   E8TAxisProd0463GraphWholeC.qJetBox,
   E8TAxisProd0463GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨12667078029776658574235372227266617554425711224, 12667078029776658574235372227266694158461331725⟩
  | 0, 2 => ⟨40385058405535530637713880761786674098946872128, 40385058405535530637713880761786949229219638545⟩
  | 1, 1 => ⟨40872090368625514586151361944832081893651618564, 40872090368625514586151361944832567572269928110⟩
  | 0, 3 => ⟨88328404094920385069292551300322477596384201940, 88328404094920385069292551300323351810948131121⟩
  | 1, 2 => ⟨120132857639219041444310935569186764334262059591, 120132857639219041444310935569188300376864681006⟩
  | 2, 1 => ⟨121401048954655677423381641703359814596283203940, 121401048954655677423381641703362569929750203879⟩
  | 0, 4 => ⟨159819105124383356760793427096861028618630182114, 159819105124383356760793427096863927001052221173⟩
  | 1, 3 => ⟨241780881341448469404823568272126109652089384918, 241780881341448469404823568272131293002147905534⟩
  | 2, 2 => ⟨324419304253318966897287022053639500549849694488, 324419304253318966897287022053648941555242149884⟩
  | 3, 1 => ⟨327365696361651539079472919806228340426400280680, 327365696361651539079472919806245697772622616827⟩
  | 0, 5 => ⟨-522616303111905802445351540786709714313404904882173, 525824997686417837383935606704165803985699263134632⟩
  | 1, 4 => ⟨-1017655842834780304516706898439199156535337967643730, 1022441989431289841745991446581375991835550804738837⟩
  | 2, 3 => ⟨-1984107883823765862448315914916180705695167429277090, 1990959466359725600415985935810733847613665722384465⟩
  | 3, 2 => ⟨-3871333878084354556645178032621411366835985539997269, 3880295923888827422768301253571978081582977143195652⟩
  | 4, 1 => ⟨-7557659184588515609546843192386689676266795042008615, 7566818355222673476693359194728346840822238276639390⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0463Geometry.ds, E8TAxisProd0463Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 11850825149445860128382413048835202218189869926 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0463CertifiedArithmetic
