import GeneralCK.Certificates.E8TAxisZero0007GraphCenterA
import GeneralCK.Certificates.E8TAxisZero0007GraphCenterB
import GeneralCK.Certificates.E8TAxisZero0007GraphCenterC
import GeneralCK.Certificates.E8TAxisZero0007GraphCenterD
import GeneralCK.Certificates.E8TAxisZero0007GraphWholeA
import GeneralCK.Certificates.E8TAxisZero0007GraphWholeB
import GeneralCK.Certificates.E8TAxisZero0007GraphWholeC
import GeneralCK.Certificates.E8TAxisZero0007GraphWholeD
import GeneralCK.Certificates.E8TAxisRegularInverseBoxes
import GeneralCK.Certificates.E8TAxisZero0007Geometry
import GeneralCK.Certificates.E8TAxisRegularCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisZero0007CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisRegularCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisZero0007GraphCenterA.qJetBox,
   E8TAxisZero0007GraphCenterB.qJetBox,
   E8TAxisZero0007GraphCenterC.qJetBox,
   E8TAxisZero0007GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisZero0007GraphWholeA.qJetBox,
   E8TAxisZero0007GraphWholeB.qJetBox,
   E8TAxisZero0007GraphWholeC.qJetBox,
   E8TAxisZero0007GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨87998506334808492595001587623273014190, 87998506334808492595001588326796852242⟩
  | 0, 2 => ⟨4855215759285447758555219424921847581284, 4855215759285447758555220259430604422153⟩
  | 1, 1 => ⟨5326466322698402817389434967588075224019, 5326466322698402817389434973276646204225⟩
  | 0, 3 => ⟨137343530427132501466752067934887127601459, 137343530427132501466754571972290540160819⟩
  | 1, 2 => ⟨240205419243849515053097794540954741382722, 240205419243849515053097804842304988039672⟩
  | 2, 1 => ⟨257790590471250691958507453784909222745284, 257790590471250691958507453789508793430381⟩
  | 0, 4 => ⟨1671749001894009296394243174411435590509566, 1671749001894009296401273009648397437857964⟩
  | 1, 3 => ⟨5187750862722119585521488517811868021395924, 5187750862722119585521519412623760977189559⟩
  | 2, 2 => ⟨8921935224959648078768543077443873088428352, 8921935224959648078768543077808699987732950⟩
  | 3, 1 => ⟨9360720621612458491254177894873757174562110, 9360720621612458491254177894897360492760033⟩
  | 0, 5 => ⟨-52117734427865132849543787625168282303459717545, 52467701850955868364240465987393847381652497574⟩
  | 1, 4 => ⟨-77824412645570371428795185738156455165179001205, 77920301442955968803285684079491390183834090170⟩
  | 2, 3 => ⟨-120464556783870895433813801151989158204887025307, 120304743026261033045886860947069490157523516992⟩
  | 3, 2 => ⟨-188388392049018970500819627586966749388921600715, 188032473136759925438060876019090510954532388089⟩
  | 4, 1 => ⟨-290884558908678108748933225736091846202559416001, 290792112526664189695657716648697109877582364903⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisZero0007Geometry.ds, E8TAxisZero0007Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 20106875275514589028802266822251466078 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsRegularAt s t) :
    data.CenterEnclosed (mixed E8TAxisRegularGermJet.regularQJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_regular_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_regular_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_regular_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_regular_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_regular_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_regular_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_regular_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_regular_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_regular_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_regular_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsRegularAt s t) :
    data.RemainderEnclosed (mixed E8TAxisRegularGermJet.regularQJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_regular_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_regular_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_regular_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_regular_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_regular_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisZero0007CertifiedArithmetic
