import GeneralCK.Certificates.E8TAxisProd0130GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0130GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0130GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0130GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0130GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0130GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0130GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0130GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0130Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0130CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0130GraphCenterA.qJetBox,
   E8TAxisProd0130GraphCenterB.qJetBox,
   E8TAxisProd0130GraphCenterC.qJetBox,
   E8TAxisProd0130GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0130GraphWholeA.qJetBox,
   E8TAxisProd0130GraphWholeB.qJetBox,
   E8TAxisProd0130GraphWholeC.qJetBox,
   E8TAxisProd0130GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨2348395554322727992826470631635207089000547210, 2348395554322727992826470631635230859876632841⟩
  | 0, 2 => ⟨8569795122993707042108076719008790204325370036, 8569795122993707042108076719008860554225706326⟩
  | 1, 1 => ⟨8620092983690322357032828626343708177089021237, 8620092983690322357032828626343823930699191417⟩
  | 0, 3 => ⟨20968944853590465186945921849423271144533291604, 20968944853590465186945921849423478874314856461⟩
  | 1, 2 => ⟨29091588575494230253832652878121779585309344617, 29091588575494230253832652878122123567553904086⟩
  | 2, 1 => ⟨29241547794666458075705139820477457193140407883, 29241547794666458075705139820478052365124195594⟩
  | 0, 4 => ⟨42676073927092898531784067683429931435123168088, 42676073927092898531784067683430580972026613618⟩
  | 1, 3 => ⟨66774684308237154928376202911193663667178935426, 66774684308237154928376202911194769756150671796⟩
  | 2, 2 => ⟨90972243675981407850105669698296943244702860967, 90972243675981407850105669698298897152950701608⟩
  | 3, 1 => ⟨91380329165075057254146475728890761561043803077, 91380329165075057254146475728894265541760960545⟩
  | 0, 5 => ⟨-750197151245723904173917568893091092277424549496093, 751787977573181309623414874281764145908275772394589⟩
  | 1, 4 => ⟨-1462063229254503039422922989564389159009977574154220, 1464222591591759181428313427000502148827637246273686⟩
  | 2, 3 => ⟨-2851870651363050985396702080737461302932135483130910, 2854770319339438350347070798537315532641896703019586⟩
  | 3, 2 => ⟨-5565306071705834539007079778472351704636957840448540, 5569013477267675027973392532923341915010639845614465⟩
  | 4, 1 => ⟨-10863255677273031946073066151948193204722931069851175, 10867249266401291727260814758760296636031073326997433⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0130Geometry.ds, E8TAxisProd0130Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 1584016077378274851935508514756729153426384012 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0130CertifiedArithmetic
