import GeneralCK.Certificates.E8TAxisProd0346GraphCenterA
import GeneralCK.Certificates.E8TAxisProd0346GraphCenterB
import GeneralCK.Certificates.E8TAxisProd0346GraphCenterC
import GeneralCK.Certificates.E8TAxisProd0346GraphCenterD
import GeneralCK.Certificates.E8TAxisProd0346GraphWholeA
import GeneralCK.Certificates.E8TAxisProd0346GraphWholeB
import GeneralCK.Certificates.E8TAxisProd0346GraphWholeC
import GeneralCK.Certificates.E8TAxisProd0346GraphWholeD
import GeneralCK.Certificates.E8TAxisFirstCellBridge
import GeneralCK.Certificates.E8TAxisProd0346Geometry
import GeneralCK.Certificates.E8TAxisGeneralCenteredTaylor

/-! Exact checked mixed outputs from the eight padded stable graphs.
Generated by scripts/e8_taxis_emit_certified_arithmetic.py. -/

namespace GeneralCK.Certificates.E8TAxisProd0346CertifiedArithmetic
open DyadicInterval E8TAxisFirstCellBridge E8TAxisGeneralCenteredTaylor
open E8TAxisMixedCoefficients E8TAxisDeltaDirectionalJet
set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

abbrev precision := 160

def centerBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0346GraphCenterA.qJetBox,
   E8TAxisProd0346GraphCenterB.qJetBox,
   E8TAxisProd0346GraphCenterC.qJetBox,
   E8TAxisProd0346GraphCenterD.qJetBox⟩

def wholeBoxes : InverseBoxes precision :=
  ⟨E8TAxisProd0346GraphWholeA.qJetBox,
   E8TAxisProd0346GraphWholeB.qJetBox,
   E8TAxisProd0346GraphWholeC.qJetBox,
   E8TAxisProd0346GraphWholeD.qJetBox⟩

def coeff : ℕ → ℕ → DyadicInterval precision
  | 0, 1 => ⟨93420740447324622580604598638401772995133016348, 93420740447324622580604598638402259769701220581⟩
  | 0, 2 => ⟨254709885883888858067876859751095416547878005477, 254709885883888858067876859751097467601089223468⟩
  | 1, 1 => ⟨255600052633684108697633828713680506985015616058, 255600052633684108697633828713684315525063557857⟩
  | 0, 3 => ⟨480531694341317842496922250281056491286172852932, 480531694341317842496922250281063490036934067666⟩
  | 1, 2 => ⟨639777956639615627912234448609192316433471842467, 639777956639615627912234448609205178078522433033⟩
  | 2, 1 => ⟨641766279207513257894227584923084573349522651499, 641766279207513257894227584923108444318355783772⟩
  | 0, 4 => ⟨760989959723812732695271905246943291277655443176, 760989959723812732695271905246968594621453605473⟩
  | 1, 3 => ⟨1115625183522754486164518854626474275426337063431, 1115625183522754486164518854626521191612571908262⟩
  | 2, 2 => ⟨1471165535077327118785204500540592877675015124622, 1471165535077327118785204500540680710559529381046⟩
  | 3, 1 => ⟨1475286065470935936296905734861665148591122928444, 1475286065470935936296905734861830702528989789990⟩
  | 0, 5 => ⟨-4670699698415352017369137399533947811920391202245717, 4691670074930550495789046370016145940968663483094524⟩
  | 1, 4 => ⟨-9190909895524565917317459974822494384308357713909817, 9222437166634059216552158999925335859980549900786078⟩
  | 2, 3 => ⟨-18101941447333817553875595592460872297264741610120683, 18147265583095944674830772440584930980250489748694909⟩
  | 3, 2 => ⟨-35675675608741473839254311081118975097495221753888571, 35735012938987927327942887313755160541759804510529742⟩
  | 4, 1 => ⟨-70347939733965391363706608407108576203532602234266905, 70408285348754102596720386942422421193606447472754604⟩
  | _, _ => ofInt precision 0

def data : Data precision :=
  ⟨E8TAxisProd0346Geometry.ds, E8TAxisProd0346Geometry.dt, coeff⟩

theorem center_0_1_checked :
    centerBoxes.coeff 0 1 = data.coeff 0 1 := by decide

theorem center_0_2_checked :
    centerBoxes.coeff 0 2 = data.coeff 0 2 := by decide

theorem center_1_1_checked :
    centerBoxes.coeff 1 1 = data.coeff 1 1 := by decide

theorem center_0_3_checked :
    centerBoxes.coeff 0 3 = data.coeff 0 3 := by decide

theorem center_1_2_checked :
    centerBoxes.coeff 1 2 = data.coeff 1 2 := by decide

theorem center_2_1_checked :
    centerBoxes.coeff 2 1 = data.coeff 2 1 := by decide

theorem center_0_4_checked :
    centerBoxes.coeff 0 4 = data.coeff 0 4 := by decide

theorem center_1_3_checked :
    centerBoxes.coeff 1 3 = data.coeff 1 3 := by decide

theorem center_2_2_checked :
    centerBoxes.coeff 2 2 = data.coeff 2 2 := by decide

theorem center_3_1_checked :
    centerBoxes.coeff 3 1 = data.coeff 3 1 := by decide

theorem whole_0_5_checked :
    wholeBoxes.coeff 0 5 = data.coeff 0 5 := by decide

theorem whole_1_4_checked :
    wholeBoxes.coeff 1 4 = data.coeff 1 4 := by decide

theorem whole_2_3_checked :
    wholeBoxes.coeff 2 3 = data.coeff 2 3 := by decide

theorem whole_3_2_checked :
    wholeBoxes.coeff 3 2 = data.coeff 3 2 := by decide

theorem whole_4_1_checked :
    wholeBoxes.coeff 4 1 = data.coeff 4 1 := by decide

theorem replay_positive : data.replay.positiveCheck = true := by decide

theorem replay_lo : data.replay.lo = 88228262226426200607280497723009902805361060604 := by decide

theorem centerEnclosed_of_contains {s t : ℝ} (h : centerBoxes.ContainsAt s t) :
    data.CenterEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← center_0_1_checked]
    exact InverseBoxes.coeff_sound h 0 1
  · rw [← center_0_2_checked]
    exact InverseBoxes.coeff_sound h 0 2
  · rw [← center_1_1_checked]
    exact InverseBoxes.coeff_sound h 1 1
  · rw [← center_0_3_checked]
    exact InverseBoxes.coeff_sound h 0 3
  · rw [← center_1_2_checked]
    exact InverseBoxes.coeff_sound h 1 2
  · rw [← center_2_1_checked]
    exact InverseBoxes.coeff_sound h 2 1
  · rw [← center_0_4_checked]
    exact InverseBoxes.coeff_sound h 0 4
  · rw [← center_1_3_checked]
    exact InverseBoxes.coeff_sound h 1 3
  · rw [← center_2_2_checked]
    exact InverseBoxes.coeff_sound h 2 2
  · rw [← center_3_1_checked]
    exact InverseBoxes.coeff_sound h 3 1

theorem wholeEnclosed_of_contains {s t : ℝ} (h : wholeBoxes.ContainsAt s t) :
    data.RemainderEnclosed (mixed qJet s t) := by
  refine ⟨?_ , ?_ , ?_ , ?_ , ?_⟩
  · rw [← whole_0_5_checked]
    exact InverseBoxes.coeff_sound h 0 5
  · rw [← whole_1_4_checked]
    exact InverseBoxes.coeff_sound h 1 4
  · rw [← whole_2_3_checked]
    exact InverseBoxes.coeff_sound h 2 3
  · rw [← whole_3_2_checked]
    exact InverseBoxes.coeff_sound h 3 2
  · rw [← whole_4_1_checked]
    exact InverseBoxes.coeff_sound h 4 1

#print axioms center_0_1_checked
#print axioms whole_4_1_checked
#print axioms replay_positive
#print axioms centerEnclosed_of_contains
end GeneralCK.Certificates.E8TAxisProd0346CertifiedArithmetic
