import GeneralCK.Certificates.E8TAxisFirstCellInverseCoverage
import GeneralCK.Certificates.E8TAxisProd0193Geometry
import GeneralCK.Certificates.E8TAxisProd0193PaddedInputs

/-!
# Endpoint certificates for all eight padded first-cell inverse brackets

Generated by `scripts/e8_taxis_emit_endpoint_witnesses.py`.
All primitive checks, scalar graph identities, and target comparisons
are checked separately. Coverage follows from the intermediate value theorem.
The exact lower cell boundaries are those in `E8TAxisProd0193Geometry`.
-/

namespace GeneralCK.Certificates.E8TAxisProd0193EndpointWitnesses

open Set DyadicInterval E8TAxisStableInterval E8TAxisStableScalar
open E8TAxisFirstCellInverseCoverage E8TAxisProd0193Geometry

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

def precision : ℕ := 160
def endpointLogTwo : DyadicInterval precision := ⟨1013035739299659071135698605846798551586536899314, 1013035739299659071135698605846798551586536899589⟩
def fastLogWitness : FastLogBoxWitness := ⟨0, 128, 0, 128⟩

theorem endpointLogTwo_checked :
    logBoxCheck (ofInt precision 2) endpointLogTwo fastLogWitness = true := by decide +kernel

def centerALowerAlpha : DyadicInterval precision := ⟨949721161203312387564849132921065893757532294, 949721161203312387564849132921065893757532294⟩
def centerALowerExp : DyadicInterval precision := ⟨1459603428780171974367103696970164795254323094074, 1459603428780171974367103696970164795254323096123⟩
def centerALowerLog : DyadicInterval precision := ⟨1012086326714990166522051059359330289759945079282, 1012086326714990166522051059359330289759945080577⟩
def centerALowerYBox : DyadicInterval precision := ⟨5480631139990885943263818122686061323709367348, 5480631139990885943263818122686061323709370334⟩
def centerALowerInput : Inputs precision :=
  ⟨centerALowerAlpha, centerALowerExp, centerALowerLog, endpointLogTwo⟩
def centerALowerExpWitness : ExpWitness precision :=
  ⟨1459603428780171974367103696970164795254323094074, scale precision, 1459603428780171974367103696970164795254323096123, scale precision,
    0, 128, 0, 128, ⟨-1899442322406624775129698265842131787515065869, -1899442322406624775129698265842131787515065604⟩, ⟨-1899442322406624775129698265842131787515063817, -1899442322406624775129698265842131787515063552⟩⟩

theorem centerALower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerALowerAlpha) centerALowerExp centerALowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerALowerExp) centerALowerLog fastLogWitness = true := by decide +kernel

theorem centerALower_denominators : DenominatorsPositive centerALowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerALower_yBox_eq : (yBox centerALowerInput).d0 = centerALowerYBox := by decide +kernel

theorem centerALower_contains :
    centerALowerYBox.Contains (Y (lower E8TAxisProd0193PaddedInputs.centerAInput.alpha)) := by
  rw [← centerALower_yBox_eq]
  apply checked_yBox_d0_contains centerALower_primitive_checks.1
    centerALower_primitive_checks.2 endpointLogTwo_checked centerALower_denominators
  exact point_contains precision 949721161203312387564849132921065893757532294

def centerAUpperAlpha : DyadicInterval precision := ⟨949721161203312387564849132921065893757663367, 949721161203312387564849132921065893757663367⟩
def centerAUpperExp : DyadicInterval precision := ⟨1459603428780171974367103696970164795254322832269, 1459603428780171974367103696970164795254322834318⟩
def centerAUpperLog : DyadicInterval precision := ⟨1012086326714990166522051059359330289759944948298, 1012086326714990166522051059359330289759944949587⟩
def centerAUpperYBox : DyadicInterval precision := ⟨5480631139990885943263818122686061323710123741, 5480631139990885943263818122686061323710126727⟩
def centerAUpperInput : Inputs precision :=
  ⟨centerAUpperAlpha, centerAUpperExp, centerAUpperLog, endpointLogTwo⟩
def centerAUpperExpWitness : ExpWitness precision :=
  ⟨1459603428780171974367103696970164795254322832269, scale precision, 1459603428780171974367103696970164795254322834318, scale precision,
    0, 128, 0, 128, ⟨-1899442322406624775129698265842131787515328015, -1899442322406624775129698265842131787515327750⟩, ⟨-1899442322406624775129698265842131787515325963, -1899442322406624775129698265842131787515325698⟩⟩

theorem centerAUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerAUpperAlpha) centerAUpperExp centerAUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerAUpperExp) centerAUpperLog fastLogWitness = true := by decide +kernel

theorem centerAUpper_denominators : DenominatorsPositive centerAUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerAUpper_yBox_eq : (yBox centerAUpperInput).d0 = centerAUpperYBox := by decide +kernel

theorem centerAUpper_contains :
    centerAUpperYBox.Contains (Y (upper E8TAxisProd0193PaddedInputs.centerAInput.alpha)) := by
  rw [← centerAUpper_yBox_eq]
  apply checked_yBox_d0_contains centerAUpper_primitive_checks.1
    centerAUpper_primitive_checks.2 endpointLogTwo_checked centerAUpper_denominators
  exact point_contains precision 949721161203312387564849132921065893757663367

def centerBLowerAlpha : DyadicInterval precision := ⟨782614057170900817822504005131256250178987284917, 782614057170900817822504005131256250178987284917⟩
def centerBLowerExp : DyadicInterval precision := ⟨500820207415007562814187849171050811114679217873, 500820207415007562814187849171050811114679219922⟩
def centerBLowerLog : DyadicInterval precision := ⟨430651861360628452422761837495794547038136522006, 430651861360628452422761837495794547038136523797⟩
def centerBLowerYBox : DyadicInterval precision := ⟨4115953986133155343391127410137232054106019717747, 4115953986133155343391127410137232054106019747608⟩
def centerBLowerInput : Inputs precision :=
  ⟨centerBLowerAlpha, centerBLowerExp, centerBLowerLog, endpointLogTwo⟩
def centerBLowerExpWitness : ExpWitness precision :=
  ⟨500820207415007562814187849171050811114679217873, scale precision, 500820207415007562814187849171050811114679219922, scale precision,
    1, 128, 1, 128,
    ⟨-1565228114341801635645008010262512500357974573274, -1565228114341801635645008010262512500357974572736⟩, ⟨-1565228114341801635645008010262512500357974567294, -1565228114341801635645008010262512500357974566756⟩⟩

theorem centerBLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerBLowerAlpha) centerBLowerExp centerBLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerBLowerExp) centerBLowerLog fastLogWitness = true := by decide +kernel

theorem centerBLower_denominators : DenominatorsPositive centerBLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerBLower_yBox_eq : (yBox centerBLowerInput).d0 = centerBLowerYBox := by decide +kernel

theorem centerBLower_contains :
    centerBLowerYBox.Contains (Y (lower E8TAxisProd0193PaddedInputs.centerBInput.alpha)) := by
  rw [← centerBLower_yBox_eq]
  apply checked_yBox_d0_contains centerBLower_primitive_checks.1
    centerBLower_primitive_checks.2 endpointLogTwo_checked centerBLower_denominators
  exact point_contains precision 782614057170900817822504005131256250178987284917

def centerBUpperAlpha : DyadicInterval precision := ⟨782614057170900817822504005131256250178987415990, 782614057170900817822504005131256250178987415990⟩
def centerBUpperExp : DyadicInterval precision := ⟨500820207415007562814187849171050811114679128042, 500820207415007562814187849171050811114679130091⟩
def centerBUpperLog : DyadicInterval precision := ⟨430651861360628452422761837495794547038136455100, 430651861360628452422761837495794547038136456893⟩
def centerBUpperYBox : DyadicInterval precision := ⟨4115953986133155343391127410137232054106020300149, 4115953986133155343391127410137232054106020330024⟩
def centerBUpperInput : Inputs precision :=
  ⟨centerBUpperAlpha, centerBUpperExp, centerBUpperLog, endpointLogTwo⟩
def centerBUpperExpWitness : ExpWitness precision :=
  ⟨500820207415007562814187849171050811114679128042, scale precision, 500820207415007562814187849171050811114679130091, scale precision,
    1, 128, 1, 128,
    ⟨-1565228114341801635645008010262512500357974835418, -1565228114341801635645008010262512500357974834880⟩, ⟨-1565228114341801635645008010262512500357974829440, -1565228114341801635645008010262512500357974828900⟩⟩

theorem centerBUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerBUpperAlpha) centerBUpperExp centerBUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerBUpperExp) centerBUpperLog fastLogWitness = true := by decide +kernel

theorem centerBUpper_denominators : DenominatorsPositive centerBUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerBUpper_yBox_eq : (yBox centerBUpperInput).d0 = centerBUpperYBox := by decide +kernel

theorem centerBUpper_contains :
    centerBUpperYBox.Contains (Y (upper E8TAxisProd0193PaddedInputs.centerBInput.alpha)) := by
  rw [← centerBUpper_yBox_eq]
  apply checked_yBox_d0_contains centerBUpper_primitive_checks.1
    centerBUpper_primitive_checks.2 endpointLogTwo_checked centerBUpper_denominators
  exact point_contains precision 782614057170900817822504005131256250178987415990

def centerCLowerAlpha : DyadicInterval precision := ⟨365495677680231603136273874252305548538442043498, 365495677680231603136273874252305548538442043498⟩
def centerCLowerExp : DyadicInterval precision := ⟨886299671386099936049759412508262969706791115988, 886299671386099936049759412508262969706791118037⟩
def centerCLowerLog : DyadicInterval precision := ⟨692773480867016193619185737701900735352445440046, 692773480867016193619185737701900735352445441587⟩
def centerCLowerYBox : DyadicInterval precision := ⟨2060717308636573114667195614129959057714864525847, 2060717308636573114667195614129959057714864538942⟩
def centerCLowerInput : Inputs precision :=
  ⟨centerCLowerAlpha, centerCLowerExp, centerCLowerLog, endpointLogTwo⟩
def centerCLowerExpWitness : ExpWitness precision :=
  ⟨886299671386099936049759412508262969706791115988, scale precision, 886299671386099936049759412508262969706791118037, scale precision,
    0, 128, 0, 128, ⟨-730991355360463206272547748504611097076884088905, -730991355360463206272547748504611097076884088638⟩, ⟨-730991355360463206272547748504611097076884085529, -730991355360463206272547748504611097076884085258⟩⟩

theorem centerCLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerCLowerAlpha) centerCLowerExp centerCLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerCLowerExp) centerCLowerLog fastLogWitness = true := by decide +kernel

theorem centerCLower_denominators : DenominatorsPositive centerCLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerCLower_yBox_eq : (yBox centerCLowerInput).d0 = centerCLowerYBox := by decide +kernel

theorem centerCLower_contains :
    centerCLowerYBox.Contains (Y (lower E8TAxisProd0193PaddedInputs.centerCInput.alpha)) := by
  rw [← centerCLower_yBox_eq]
  apply checked_yBox_d0_contains centerCLower_primitive_checks.1
    centerCLower_primitive_checks.2 endpointLogTwo_checked centerCLower_denominators
  exact point_contains precision 365495677680231603136273874252305548538442043498

def centerCUpperAlpha : DyadicInterval precision := ⟨365495677680231603136273874252305548538442174571, 365495677680231603136273874252305548538442174571⟩
def centerCUpperExp : DyadicInterval precision := ⟨886299671386099936049759412508262969706790957014, 886299671386099936049759412508262969706790959063⟩
def centerCUpperLog : DyadicInterval precision := ⟨692773480867016193619185737701900735352445341088, 692773480867016193619185737701900735352445342627⟩
def centerCUpperYBox : DyadicInterval precision := ⟨2060717308636573114667195614129959057714865231922, 2060717308636573114667195614129959057714865245017⟩
def centerCUpperInput : Inputs precision :=
  ⟨centerCUpperAlpha, centerCUpperExp, centerCUpperLog, endpointLogTwo⟩
def centerCUpperExpWitness : ExpWitness precision :=
  ⟨886299671386099936049759412508262969706790957014, scale precision, 886299671386099936049759412508262969706790959063, scale precision,
    0, 128, 0, 128, ⟨-730991355360463206272547748504611097076884351053, -730991355360463206272547748504611097076884350784⟩, ⟨-730991355360463206272547748504611097076884347675, -730991355360463206272547748504611097076884347406⟩⟩

theorem centerCUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerCUpperAlpha) centerCUpperExp centerCUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerCUpperExp) centerCUpperLog fastLogWitness = true := by decide +kernel

theorem centerCUpper_denominators : DenominatorsPositive centerCUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerCUpper_yBox_eq : (yBox centerCUpperInput).d0 = centerCUpperYBox := by decide +kernel

theorem centerCUpper_contains :
    centerCUpperYBox.Contains (Y (upper E8TAxisProd0193PaddedInputs.centerCInput.alpha)) := by
  rw [← centerCUpper_yBox_eq]
  apply checked_yBox_d0_contains centerCUpper_primitive_checks.1
    centerCUpper_primitive_checks.2 endpointLogTwo_checked centerCUpper_denominators
  exact point_contains precision 365495677680231603136273874252305548538442174571

def centerDLowerAlpha : DyadicInterval precision := ⟨364478458648618710654128585069611790600183034707, 364478458648618710654128585069611790600183034707⟩
def centerDLowerExp : DyadicInterval precision := ⟨887534276475298848733503786031227103192362145204, 887534276475298848733503786031227103192362147253⟩
def centerDLowerLog : DyadicInterval precision := ⟨693541818075819702070900853962455107553310850572, 693541818075819702070900853962455107553310852115⟩
def centerDLowerYBox : DyadicInterval precision := ⟨2055236677496582228723931796007272996391154778695, 2055236677496582228723931796007272996391154791765⟩
def centerDLowerInput : Inputs precision :=
  ⟨centerDLowerAlpha, centerDLowerExp, centerDLowerLog, endpointLogTwo⟩
def centerDLowerExpWitness : ExpWitness precision :=
  ⟨887534276475298848733503786031227103192362145204, scale precision, 887534276475298848733503786031227103192362147253, scale precision,
    0, 128, 0, 128, ⟨-728956917297237421308257170139223581200366071327, -728956917297237421308257170139223581200366071062⟩, ⟨-728956917297237421308257170139223581200366067953, -728956917297237421308257170139223581200366067690⟩⟩

theorem centerDLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerDLowerAlpha) centerDLowerExp centerDLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerDLowerExp) centerDLowerLog fastLogWitness = true := by decide +kernel

theorem centerDLower_denominators : DenominatorsPositive centerDLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerDLower_yBox_eq : (yBox centerDLowerInput).d0 = centerDLowerYBox := by decide +kernel

theorem centerDLower_contains :
    centerDLowerYBox.Contains (Y (lower E8TAxisProd0193PaddedInputs.centerDInput.alpha)) := by
  rw [← centerDLower_yBox_eq]
  apply checked_yBox_d0_contains centerDLower_primitive_checks.1
    centerDLower_primitive_checks.2 endpointLogTwo_checked centerDLower_denominators
  exact point_contains precision 364478458648618710654128585069611790600183034707

def centerDUpperAlpha : DyadicInterval precision := ⟨364478458648618710654128585069611790600183165780, 364478458648618710654128585069611790600183165780⟩
def centerDUpperExp : DyadicInterval precision := ⟨887534276475298848733503786031227103192361986009, 887534276475298848733503786031227103192361988058⟩
def centerDUpperLog : DyadicInterval precision := ⟨693541818075819702070900853962455107553310751526, 693541818075819702070900853962455107553310753069⟩
def centerDUpperYBox : DyadicInterval precision := ⟨2055236677496582228723931796007272996391155485029, 2055236677496582228723931796007272996391155498094⟩
def centerDUpperInput : Inputs precision :=
  ⟨centerDUpperAlpha, centerDUpperExp, centerDUpperLog, endpointLogTwo⟩
def centerDUpperExpWitness : ExpWitness precision :=
  ⟨887534276475298848733503786031227103192361986009, scale precision, 887534276475298848733503786031227103192361988058, scale precision,
    0, 128, 0, 128, ⟨-728956917297237421308257170139223581200366333473, -728956917297237421308257170139223581200366333208⟩, ⟨-728956917297237421308257170139223581200366330099, -728956917297237421308257170139223581200366329836⟩⟩

theorem centerDUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul centerDUpperAlpha) centerDUpperExp centerDUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add centerDUpperExp) centerDUpperLog fastLogWitness = true := by decide +kernel

theorem centerDUpper_denominators : DenominatorsPositive centerDUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem centerDUpper_yBox_eq : (yBox centerDUpperInput).d0 = centerDUpperYBox := by decide +kernel

theorem centerDUpper_contains :
    centerDUpperYBox.Contains (Y (upper E8TAxisProd0193PaddedInputs.centerDInput.alpha)) := by
  rw [← centerDUpper_yBox_eq]
  apply checked_yBox_d0_contains centerDUpper_primitive_checks.1
    centerDUpper_primitive_checks.2 endpointLogTwo_checked centerDUpper_denominators
  exact point_contains precision 364478458648618710654128585069611790600183165780

def wholeALowerAlpha : DyadicInterval precision := ⟨633147383168915695688804483341311756669058530, 633147383168915695688804483341311756669058530⟩
def wholeALowerExp : DyadicInterval precision := ⟨1460235890986607494244084883518378977884642869754, 1460235890986607494244084883518378977884642871803⟩
def wholeALowerLog : DyadicInterval precision := ⟨1012402729061596953461092784027353938661488962794, 1012402729061596953461092784027353938661488964083⟩
def wholeALowerYBox : DyadicInterval precision := ⟨3653754093327257295509212081790707549139451670, 3653754093327257295509212081790707549139454653⟩
def wholeALowerInput : Inputs precision :=
  ⟨wholeALowerAlpha, wholeALowerExp, wholeALowerLog, endpointLogTwo⟩
def wholeALowerExpWitness : ExpWitness precision :=
  ⟨1460235890986607494244084883518378977884642869754, scale precision, 1460235890986607494244084883518378977884642871803, scale precision,
    0, 128, 0, 128, ⟨-1266294766337831391377608966682623513338118343, -1266294766337831391377608966682623513338118074⟩, ⟨-1266294766337831391377608966682623513338116291, -1266294766337831391377608966682623513338116022⟩⟩

theorem wholeALower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeALowerAlpha) wholeALowerExp wholeALowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeALowerExp) wholeALowerLog fastLogWitness = true := by decide +kernel

theorem wholeALower_denominators : DenominatorsPositive wholeALowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeALower_yBox_eq : (yBox wholeALowerInput).d0 = wholeALowerYBox := by decide +kernel

theorem wholeALower_contains :
    wholeALowerYBox.Contains (Y (lower E8TAxisProd0193PaddedInputs.wholeAInput.alpha)) := by
  rw [← wholeALower_yBox_eq]
  apply checked_yBox_d0_contains wholeALower_primitive_checks.1
    wholeALower_primitive_checks.2 endpointLogTwo_checked wholeALower_denominators
  exact point_contains precision 633147383168915695688804483341311756669058530

def wholeAUpperAlpha : DyadicInterval precision := ⟨1266295042977660303900587558721132456011255132, 1266295042977660303900587558721132456011255132⟩
def wholeAUpperExp : DyadicInterval precision := ⟨1458971240300741788424025014233787499648220849486, 1458971240300741788424025014233787499648220851535⟩
def wholeAUpperLog : DyadicInterval precision := ⟨1011769992837296815097311935000023818281148541070, 1011769992837296815097311935000023818281148542359⟩
def wholeAUpperYBox : DyadicInterval precision := ⟨7307508186654514591018424163581415098280039414, 7307508186654514591018424163581415098280042406⟩
def wholeAUpperInput : Inputs precision :=
  ⟨wholeAUpperAlpha, wholeAUpperExp, wholeAUpperLog, endpointLogTwo⟩
def wholeAUpperExpWitness : ExpWitness precision :=
  ⟨1458971240300741788424025014233787499648220849486, scale precision, 1458971240300741788424025014233787499648220851535, scale precision,
    0, 128, 0, 128, ⟨-2532590085955320607801175117442264912022511543, -2532590085955320607801175117442264912022511280⟩, ⟨-2532590085955320607801175117442264912022509491, -2532590085955320607801175117442264912022509228⟩⟩

theorem wholeAUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeAUpperAlpha) wholeAUpperExp wholeAUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeAUpperExp) wholeAUpperLog fastLogWitness = true := by decide +kernel

theorem wholeAUpper_denominators : DenominatorsPositive wholeAUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeAUpper_yBox_eq : (yBox wholeAUpperInput).d0 = wholeAUpperYBox := by decide +kernel

theorem wholeAUpper_contains :
    wholeAUpperYBox.Contains (Y (upper E8TAxisProd0193PaddedInputs.wholeAInput.alpha)) := by
  rw [← wholeAUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeAUpper_primitive_checks.1
    wholeAUpper_primitive_checks.2 endpointLogTwo_checked wholeAUpper_denominators
  exact point_contains precision 1266295042977660303900587558721132456011255132

def wholeBLowerAlpha : DyadicInterval precision := ⟨761758005536359898319332737195518341687286387974, 761758005536359898319332737195518341687286387974⟩
def wholeBLowerExp : DyadicInterval precision := ⟨515319835893299332300907623465546831391977956379, 515319835893299332300907623465546831391977958428⟩
def wholeBLowerLog : DyadicInterval precision := ⟨441411219301797065124766232562135555650932338816, 441411219301797065124766232562135555650932340597⟩
def wholeBLowerYBox : DyadicInterval precision := ⟨4022783256753310282355642502051569011602954015473, 4022783256753310282355642502051569011602954044377⟩
def wholeBLowerInput : Inputs precision :=
  ⟨wholeBLowerAlpha, wholeBLowerExp, wholeBLowerLog, endpointLogTwo⟩
def wholeBLowerExpWitness : ExpWitness precision :=
  ⟨515319835893299332300907623465546831391977956379, scale precision, 515319835893299332300907623465546831391977958428, scale precision,
    1, 128, 1, 128,
    ⟨-1523516011072719796638665474391036683374572779312, -1523516011072719796638665474391036683374572778772⟩, ⟨-1523516011072719796638665474391036683374572773500, -1523516011072719796638665474391036683374572772960⟩⟩

theorem wholeBLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeBLowerAlpha) wholeBLowerExp wholeBLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeBLowerExp) wholeBLowerLog fastLogWitness = true := by decide +kernel

theorem wholeBLower_denominators : DenominatorsPositive wholeBLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeBLower_yBox_eq : (yBox wholeBLowerInput).d0 = wholeBLowerYBox := by decide +kernel

theorem wholeBLower_contains :
    wholeBLowerYBox.Contains (Y (lower E8TAxisProd0193PaddedInputs.wholeBInput.alpha)) := by
  rw [← wholeBLower_yBox_eq]
  apply checked_yBox_d0_contains wholeBLower_primitive_checks.1
    wholeBLower_primitive_checks.2 endpointLogTwo_checked wholeBLower_denominators
  exact point_contains precision 761758005536359898319332737195518341687286387974

def wholeBUpperAlpha : DyadicInterval precision := ⟨803696310944812440969022459738225718904065416726, 803696310944812440969022459738225718904065416726⟩
def wholeBUpperExp : DyadicInterval precision := ⟨486577914747696709790903248729443373811420690907, 486577914747696709790903248729443373811420692956⟩
def wholeBUpperLog : DyadicInterval precision := ⟨420005779804942359384841535882528921502693887646, 420005779804942359384841535882528921502693889445⟩
def wholeBUpperYBox : DyadicInterval precision := ⟨4209124715513000404426612318222895096609085996130, 4209124715513000404426612318222895096609086026974⟩
def wholeBUpperInput : Inputs precision :=
  ⟨wholeBUpperAlpha, wholeBUpperExp, wholeBUpperLog, endpointLogTwo⟩
def wholeBUpperExpWitness : ExpWitness precision :=
  ⟨486577914747696709790903248729443373811420690907, scale precision, 486577914747696709790903248729443373811420692956, scale precision,
    1, 128, 1, 128,
    ⟨-1607392621889624881938044919476451437808130836980, -1607392621889624881938044919476451437808130836436⟩, ⟨-1607392621889624881938044919476451437808130830824, -1607392621889624881938044919476451437808130830280⟩⟩

theorem wholeBUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeBUpperAlpha) wholeBUpperExp wholeBUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeBUpperExp) wholeBUpperLog fastLogWitness = true := by decide +kernel

theorem wholeBUpper_denominators : DenominatorsPositive wholeBUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeBUpper_yBox_eq : (yBox wholeBUpperInput).d0 = wholeBUpperYBox := by decide +kernel

theorem wholeBUpper_contains :
    wholeBUpperYBox.Contains (Y (upper E8TAxisProd0193PaddedInputs.wholeBInput.alpha)) := by
  rw [← wholeBUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeBUpper_primitive_checks.1
    wholeBUpper_primitive_checks.2 endpointLogTwo_checked wholeBUpper_denominators
  exact point_contains precision 803696310944812440969022459738225718904065416726

def wholeCLowerAlpha : DyadicInterval precision := ⟨356691905071146287929656593976527943665705823403, 356691905071146287929656593976527943665705823403⟩
def wholeCLowerExp : DyadicInterval precision := ⟨897042009503459323947563467667192977118535581508, 897042009503459323947563467667192977118535583557⟩
def wholeCLowerLog : DyadicInterval precision := ⟨699445313110822652797813327213962721901810641604, 699445313110822652797813327213962721901810643139⟩
def wholeCLowerYBox : DyadicInterval precision := ⟨2013218505423318769825575857066679859576046717249, 2013218505423318769825575857066679859576046730054⟩
def wholeCLowerInput : Inputs precision :=
  ⟨wholeCLowerAlpha, wholeCLowerExp, wholeCLowerLog, endpointLogTwo⟩
def wholeCLowerExpWitness : ExpWitness precision :=
  ⟨897042009503459323947563467667192977118535581508, scale precision, 897042009503459323947563467667192977118535583557, scale precision,
    0, 128, 0, 128, ⟨-713383810142292575859313187953055887331411648705, -713383810142292575859313187953055887331411648436⟩, ⟨-713383810142292575859313187953055887331411645367, -713383810142292575859313187953055887331411645096⟩⟩

theorem wholeCLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeCLowerAlpha) wholeCLowerExp wholeCLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeCLowerExp) wholeCLowerLog fastLogWitness = true := by decide +kernel

theorem wholeCLower_denominators : DenominatorsPositive wholeCLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeCLower_yBox_eq : (yBox wholeCLowerInput).d0 = wholeCLowerYBox := by decide +kernel

theorem wholeCLower_contains :
    wholeCLowerYBox.Contains (Y (lower E8TAxisProd0193PaddedInputs.wholeCInput.alpha)) := by
  rw [← wholeCLower_yBox_eq]
  apply checked_yBox_d0_contains wholeCLower_primitive_checks.1
    wholeCLower_primitive_checks.2 endpointLogTwo_checked wholeCLower_denominators
  exact point_contains precision 356691905071146287929656593976527943665705823403

def wholeCUpperAlpha : DyadicInterval precision := ⟨374327121979865748895978949729971482563056564754, 374327121979865748895978949729971482563056564754⟩
def wholeCUpperExp : DyadicInterval precision := ⟨875652816490321812361935498064993326937483204003, 875652816490321812361935498064993326937483206052⟩
def wholeCUpperLog : DyadicInterval precision := ⟨686130761729925310680128142047483589445199791376, 686130761729925310680128142047483589445199792923⟩
def wholeCUpperYBox : DyadicInterval precision := ⟨2108216111849827459508815371193238255853683038292, 2108216111849827459508815371193238255853683051695⟩
def wholeCUpperInput : Inputs precision :=
  ⟨wholeCUpperAlpha, wholeCUpperExp, wholeCUpperLog, endpointLogTwo⟩
def wholeCUpperExpWitness : ExpWitness precision :=
  ⟨875652816490321812361935498064993326937483204003, scale precision, 875652816490321812361935498064993326937483206052, scale precision,
    0, 128, 0, 128, ⟨-748654243959731497791957899459942965126113131445, -748654243959731497791957899459942965126113131178⟩, ⟨-748654243959731497791957899459942965126113128025, -748654243959731497791957899459942965126113127760⟩⟩

theorem wholeCUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeCUpperAlpha) wholeCUpperExp wholeCUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeCUpperExp) wholeCUpperLog fastLogWitness = true := by decide +kernel

theorem wholeCUpper_denominators : DenominatorsPositive wholeCUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeCUpper_yBox_eq : (yBox wholeCUpperInput).d0 = wholeCUpperYBox := by decide +kernel

theorem wholeCUpper_contains :
    wholeCUpperYBox.Contains (Y (upper E8TAxisProd0193PaddedInputs.wholeCInput.alpha)) := by
  rw [← wholeCUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeCUpper_primitive_checks.1
    wholeCUpper_primitive_checks.2 endpointLogTwo_checked wholeCUpper_denominators
  exact point_contains precision 374327121979865748895978949729971482563056564754

def wholeDLowerAlpha : DyadicInterval precision := ⟨356015818146773315735630103594046256346147427244, 356015818146773315735630103594046256346147427244⟩
def wholeDLowerExp : DyadicInterval precision := ⟨897872332234039104779267097055247455427821035185, 897872332234039104779267097055247455427821037234⟩
def wholeDLowerLog : DyadicInterval precision := ⟨699959742628865241142888209739517590877192078440, 699959742628865241142888209739517590877192079975⟩
def wholeDLowerYBox : DyadicInterval precision := ⟨2009564751329991512530066644984889152026906885824, 2009564751329991512530066644984889152026906898605⟩
def wholeDLowerInput : Inputs precision :=
  ⟨wholeDLowerAlpha, wholeDLowerExp, wholeDLowerLog, endpointLogTwo⟩
def wholeDLowerExpWitness : ExpWitness precision :=
  ⟨897872332234039104779267097055247455427821035185, scale precision, 897872332234039104779267097055247455427821037234, scale precision,
    0, 128, 0, 128, ⟨-712031636293546631471260207188092512692294856383, -712031636293546631471260207188092512692294856114⟩, ⟨-712031636293546631471260207188092512692294853049, -712031636293546631471260207188092512692294852782⟩⟩

theorem wholeDLower_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeDLowerAlpha) wholeDLowerExp wholeDLowerExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeDLowerExp) wholeDLowerLog fastLogWitness = true := by decide +kernel

theorem wholeDLower_denominators : DenominatorsPositive wholeDLowerInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeDLower_yBox_eq : (yBox wholeDLowerInput).d0 = wholeDLowerYBox := by decide +kernel

theorem wholeDLower_contains :
    wholeDLowerYBox.Contains (Y (lower E8TAxisProd0193PaddedInputs.wholeDInput.alpha)) := by
  rw [← wholeDLower_yBox_eq]
  apply checked_yBox_d0_contains wholeDLower_primitive_checks.1
    wholeDLower_primitive_checks.2 endpointLogTwo_checked wholeDLower_denominators
  exact point_contains precision 356015818146773315735630103594046256346147427244

def wholeDUpperAlpha : DyadicInterval precision := ⟨372966609392870424646531471060848444542040916117, 372966609392870424646531471060848444542040916117⟩
def wholeDUpperExp : DyadicInterval precision := ⟨877284626339432933560204346302551151336440666863, 877284626339432933560204346302551151336440668912⟩
def wholeDUpperLog : DyadicInterval precision := ⟨687150831490084437187371430673459276874589843238, 687150831490084437187371430673459276874589844785⟩
def wholeDUpperYBox : DyadicInterval precision := ⟨2100908603663172944917796947029656840755403375774, 2100908603663172944917796947029656840755403389131⟩
def wholeDUpperInput : Inputs precision :=
  ⟨wholeDUpperAlpha, wholeDUpperExp, wholeDUpperLog, endpointLogTwo⟩
def wholeDUpperExpWitness : ExpWitness precision :=
  ⟨877284626339432933560204346302551151336440666863, scale precision, 877284626339432933560204346302551151336440668912, scale precision,
    0, 128, 0, 128, ⟨-745933218785740849293062942121696889084081834167, -745933218785740849293062942121696889084081833898⟩, ⟨-745933218785740849293062942121696889084081830751, -745933218785740849293062942121696889084081830482⟩⟩

theorem wholeDUpper_primitive_checks :
    expBoxCheck ((ofInt precision (-2)).mul wholeDUpperAlpha) wholeDUpperExp wholeDUpperExpWitness = true ∧
    logBoxCheck ((ofInt precision 1).add wholeDUpperExp) wholeDUpperLog fastLogWitness = true := by decide +kernel

theorem wholeDUpper_denominators : DenominatorsPositive wholeDUpperInput := by
  unfold DenominatorsPositive
  decide +kernel

theorem wholeDUpper_yBox_eq : (yBox wholeDUpperInput).d0 = wholeDUpperYBox := by decide +kernel

theorem wholeDUpper_contains :
    wholeDUpperYBox.Contains (Y (upper E8TAxisProd0193PaddedInputs.wholeDInput.alpha)) := by
  rw [← wholeDUpper_yBox_eq]
  apply checked_yBox_d0_contains wholeDUpper_primitive_checks.1
    wholeDUpper_primitive_checks.2 endpointLogTwo_checked wholeDUpper_denominators
  exact point_contains precision 372966609392870424646531471060848444542040916117

theorem centerA_covers_slope {s : ℝ} (hs : s ∈ Icc (centerT) (centerT)) :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.centerAInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerALower_contains centerAUpper_contains _ _ hs
  · norm_num [centerALowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerAUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerA_covers :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.centerAInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerT) :=
  centerA_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerB_covers_slope {s : ℝ} (hs : s ∈ Icc (2 * centerS + centerT) (2 * centerS + centerT)) :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.centerBInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerBLower_contains centerBUpper_contains _ _ hs
  · norm_num [centerBLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerBUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerB_covers :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.centerBInput.alpha.Contains a ∧
      0 < a ∧ Y a = (2 * centerS + centerT) :=
  centerB_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerC_covers_slope {s : ℝ} (hs : s ∈ Icc (centerS + centerT) (centerS + centerT)) :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.centerCInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerCLower_contains centerCUpper_contains _ _ hs
  · norm_num [centerCLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerCUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerC_covers :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.centerCInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerS + centerT) :=
  centerC_covers_slope ⟨le_rfl, le_rfl⟩

theorem centerD_covers_slope {s : ℝ} (hs : s ∈ Icc (centerS) (centerS)) :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.centerDInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    centerDLower_contains centerDUpper_contains _ _ hs
  · norm_num [centerDLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [centerDUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem centerD_covers :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.centerDInput.alpha.Contains a ∧
      0 < a ∧ Y a = (centerS) :=
  centerD_covers_slope ⟨le_rfl, le_rfl⟩

theorem wholeA_covers_slope {s : ℝ} (hs : s ∈ Icc (tLower) (tUpper)) :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.wholeAInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeALower_contains wholeAUpper_contains _ _ hs
  · norm_num [wholeALowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeAUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeB_covers_slope {s : ℝ} (hs : s ∈ Icc (2 * sLower + tLower) (2 * sUpper + tUpper)) :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.wholeBInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeBLower_contains wholeBUpper_contains _ _ hs
  · norm_num [wholeBLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeBUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeC_covers_slope {s : ℝ} (hs : s ∈ Icc (sLower + tLower) (sUpper + tUpper)) :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.wholeCInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeCLower_contains wholeCUpper_contains _ _ hs
  · norm_num [wholeCLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeCUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

theorem wholeD_covers_slope {s : ℝ} (hs : s ∈ Icc (sLower) (sUpper)) :
    ∃ a : ℝ, E8TAxisProd0193PaddedInputs.wholeDInput.alpha.Contains a ∧
      0 < a ∧ Y a = s := by
  apply covers_of_endpoint_enclosures (by decide) (by decide)
    wholeDLower_contains wholeDUpper_contains _ _ hs
  · norm_num [wholeDLowerYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]
  · norm_num [wholeDUpperYBox, scale, precision, centerS, centerT, sLower, sUpper, tLower, tUpper]

#print axioms centerA_covers
#print axioms wholeA_covers_slope
#print axioms wholeB_covers_slope

end GeneralCK.Certificates.E8TAxisProd0193EndpointWitnesses
