import CKLaneG3.SChunkBind
import CKLaneG3.SCover
import CKLaneG3.S.Chunk.C_4
import CKLaneG3.S.Chunk.C_50202020204
import CKLaneG3.S.Chunk.C_50202020205
import CKLaneG3.S.Chunk.C_5020202021
import CKLaneG3.S.Chunk.C_502020203040
import CKLaneG3.S.Chunk.C_5020202030414
import CKLaneG3.S.Chunk.C_5020202030415
import CKLaneM1.MLPopulationDfs

/-! Lane G3b: (S) owner label 1, chunk block 0 (7 chunks, 1190 label leaves; generated by G3/pipeline/g3chunk.py). -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace CKLaneG3.S.C1.B0

open CKLaneD CKLaneG3

/-- chunk `4`: 1190 label-1 leaves. -/
theorem c_4 : ∀ q ∈ CKLaneG3.S.Chunk.C_4.t.leavesR [4], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_range (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_4.t 1 [4] CKLaneM1.ML.Population.dfsList CKLaneM1.ML.Population.dfsList_sLeafOK 0 1190 (by decide +kernel)

/-- chunk `50202020204`: 0 label-1 leaves. -/
theorem c_50202020204 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202020204.t.leavesR [4, 0, 2, 0, 2, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202020204.t 1 [4, 0, 2, 0, 2, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `50202020205`: 0 label-1 leaves. -/
theorem c_50202020205 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202020205.t.leavesR [5, 0, 2, 0, 2, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202020205.t 1 [5, 0, 2, 0, 2, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `5020202021`: 0 label-1 leaves. -/
theorem c_5020202021 : ∀ q ∈ CKLaneG3.S.Chunk.C_5020202021.t.leavesR [1, 2, 0, 2, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_5020202021.t 1 [1, 2, 0, 2, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `502020203040`: 0 label-1 leaves. -/
theorem c_502020203040 : ∀ q ∈ CKLaneG3.S.Chunk.C_502020203040.t.leavesR [0, 4, 0, 3, 0, 2, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_502020203040.t 1 [0, 4, 0, 3, 0, 2, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `5020202030414`: 0 label-1 leaves. -/
theorem c_5020202030414 : ∀ q ∈ CKLaneG3.S.Chunk.C_5020202030414.t.leavesR [4, 1, 4, 0, 3, 0, 2, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_5020202030414.t 1 [4, 1, 4, 0, 3, 0, 2, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `5020202030415`: 0 label-1 leaves. -/
theorem c_5020202030415 : ∀ q ∈ CKLaneG3.S.Chunk.C_5020202030415.t.leavesR [5, 1, 4, 0, 3, 0, 2, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_5020202030415.t 1 [5, 1, 4, 0, 3, 0, 2, 0, 2, 0, 2, 0, 5] (by decide +kernel)

end CKLaneG3.S.C1.B0
