import CKLaneG3.SChunkBind
import CKLaneG3.SCover
import CKLaneG3.S.Chunk.C_50202020305
import CKLaneG3.S.Chunk.C_50202020314
import CKLaneG3.S.ChunkG.G_50202020315
import CKLaneG3.S.Chunk.C_50202021
import CKLaneG3.S.Chunk.C_502020300420
import CKLaneG3.S.Chunk.C_5020203004214
import CKLaneG3.S.Chunk.C_50202030042152
import CKLaneG3.S.Chunk.C_50202030042153
import CKLaneG3.S.Chunk.C_502020300430
import CKLaneG3.S.Chunk.C_5020203004314
import CKLaneG3.S.Chunk.C_50202030043150
import CKLaneM1.MLPopulationDfs

/-! Lane G3b: (S) owner label 1, chunk block 1 (11 chunks, 44 label leaves; generated by G3/pipeline/g3chunk.py). -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace CKLaneG3.S.C1.B1

open CKLaneD CKLaneG3

/-- chunk `50202020305`: 0 label-1 leaves. -/
theorem c_50202020305 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202020305.t.leavesR [5, 0, 3, 0, 2, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202020305.t 1 [5, 0, 3, 0, 2, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `50202020314`: 25 label-1 leaves. -/
theorem c_50202020314 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202020314.t.leavesR [4, 1, 3, 0, 2, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_range (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202020314.t 1 [4, 1, 3, 0, 2, 0, 2, 0, 2, 0, 5] CKLaneM1.ML.Population.dfsList CKLaneM1.ML.Population.dfsList_sLeafOK 1190 25 (by decide +kernel)

/-- chunk `50202020315`: 0 label-1 leaves. -/
theorem c_50202020315 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202020315.t.leavesR [5, 1, 3, 0, 2, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202020315.t 1 [5, 1, 3, 0, 2, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `50202021`: 19 label-1 leaves. -/
theorem c_50202021 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202021.t.leavesR [1, 2, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_range (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202021.t 1 [1, 2, 0, 2, 0, 2, 0, 5] CKLaneM1.ML.Population.dfsList CKLaneM1.ML.Population.dfsList_sLeafOK 1215 19 (by decide +kernel)

/-- chunk `502020300420`: 0 label-1 leaves. -/
theorem c_502020300420 : ∀ q ∈ CKLaneG3.S.Chunk.C_502020300420.t.leavesR [0, 2, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_502020300420.t 1 [0, 2, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `5020203004214`: 0 label-1 leaves. -/
theorem c_5020203004214 : ∀ q ∈ CKLaneG3.S.Chunk.C_5020203004214.t.leavesR [4, 1, 2, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_5020203004214.t 1 [4, 1, 2, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `50202030042152`: 0 label-1 leaves. -/
theorem c_50202030042152 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202030042152.t.leavesR [2, 5, 1, 2, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202030042152.t 1 [2, 5, 1, 2, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `50202030042153`: 0 label-1 leaves. -/
theorem c_50202030042153 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202030042153.t.leavesR [3, 5, 1, 2, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202030042153.t 1 [3, 5, 1, 2, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `502020300430`: 0 label-1 leaves. -/
theorem c_502020300430 : ∀ q ∈ CKLaneG3.S.Chunk.C_502020300430.t.leavesR [0, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_502020300430.t 1 [0, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `5020203004314`: 0 label-1 leaves. -/
theorem c_5020203004314 : ∀ q ∈ CKLaneG3.S.Chunk.C_5020203004314.t.leavesR [4, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_5020203004314.t 1 [4, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `50202030043150`: 0 label-1 leaves. -/
theorem c_50202030043150 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202030043150.t.leavesR [0, 5, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202030043150.t 1 [0, 5, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

end CKLaneG3.S.C1.B1
