import CKLaneG3.SChunkBind
import CKLaneG3.SCover
import CKLaneG3.S.Chunk.C_502020300431512
import CKLaneG3.S.Chunk.C_502020300431513
import CKLaneG3.S.Chunk.C_50202030052
import CKLaneG3.S.Chunk.C_50202030053
import CKLaneG3.S.Chunk.C_50202030142
import CKLaneM1.MLPopulationDfs

/-! Lane G3b: (S) owner label 1, chunk block 2 (5 chunks, 486 label leaves; generated by G3/pipeline/g3chunk.py). -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace CKLaneG3.S.C1.B2

open CKLaneD CKLaneG3

/-- chunk `502020300431512`: 0 label-1 leaves. -/
theorem c_502020300431512 : ∀ q ∈ CKLaneG3.S.Chunk.C_502020300431512.t.leavesR [2, 1, 5, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_502020300431512.t 1 [2, 1, 5, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `502020300431513`: 11 label-1 leaves. -/
theorem c_502020300431513 : ∀ q ∈ CKLaneG3.S.Chunk.C_502020300431513.t.leavesR [3, 1, 5, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_range (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_502020300431513.t 1 [3, 1, 5, 1, 3, 4, 0, 0, 3, 0, 2, 0, 2, 0, 5] CKLaneM1.ML.Population.dfsList CKLaneM1.ML.Population.dfsList_sLeafOK 1234 11 (by decide +kernel)

/-- chunk `50202030052`: 0 label-1 leaves. -/
theorem c_50202030052 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202030052.t.leavesR [2, 5, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202030052.t 1 [2, 5, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `50202030053`: 0 label-1 leaves. -/
theorem c_50202030053 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202030053.t.leavesR [3, 5, 0, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_none (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202030053.t 1 [3, 5, 0, 0, 3, 0, 2, 0, 2, 0, 5] (by decide +kernel)

/-- chunk `50202030142`: 475 label-1 leaves. -/
theorem c_50202030142 : ∀ q ∈ CKLaneG3.S.Chunk.C_50202030142.t.leavesR [2, 4, 1, 0, 3, 0, 2, 0, 2, 0, 5], q.2 = 1 → SLeafOK (sBox q.1) :=
  sub_family_of_range (Q := fun p => SLeafOK (sBox p)) CKLaneG3.S.Chunk.C_50202030142.t 1 [2, 4, 1, 0, 3, 0, 2, 0, 2, 0, 5] CKLaneM1.ML.Population.dfsList CKLaneM1.ML.Population.dfsList_sLeafOK 1245 475 (by decide +kernel)

end CKLaneG3.S.C1.B2
